      SUBROUTINE READRZX (CROP, EFINOC, EFNFIX, FILEC, FILEE, FILEG, 
     + FROP, IDETC, IDETD, IDETG, IDETL, IDETN, IDETO, IDETP, IDETS, 
     + IDETW, IOX, ISWDIS, ISWNIT, ISWPHO, ISWPOT, ISWSYM, ISWWAT, 
     + PATHCR, PATHEC, PATHGE, SLNF, SLPF, SPECIES, WR, TRTNO,MEPHO,
     + iswpar,nlayro)

      PARAMETER (IPDSSAT = 69)
      PARAMETER (MXNOD=300)

      INTEGER FROP, NUMPLNT, NLAYRO, TRTNO

      REAL EFINOC, EFNFIX, SLNF, SLPF, WR(20)

      CHARACTER CROP*2, FILEC*12, FILEE*12, FILEG*12, 
     + FILENAME*255, IDETC*1, IDETD*1, IDETG*1, IDETL*1, 
     + IDETN*1, IDETO*1, IDETP*1, IDETS*1, IDETW*1, IOX*1, 
     + ISWDIS*1, ISWNIT*1, ISWPHO*1, ISWPOT*1, ISWSYM*1, 
     + ISWWAT*1, PATHCR*255, PATHEC*255, PATHGE*255, SPECIES*3,
     + MEPHO*1,ISWPAR*1
      CHARACTER DSSATFILE*11

      DSSATFILE = CROP//"DSSAT.RZX"

      OPEN (IPDSSAT,FILE=DSSATFILE,STATUS='UNKNOWN', ERR=500)
      
      CALL ECHO(IPDSSAT)
      READ(IPDSSAT,*) SLNF,SLPF,EFINOC,EFNFIX

      CALL ECHO(IPDSSAT)
      READ(IPDSSAT,*) ISWWAT,ISWNIT,ISWSYM,ISWPHO,ISWPOT,ISWDIS
     +               ,ISWPAR,MEPHO
      IF ((MEPHO.EQ.'=').OR.(MEPHO.EQ.' ')) 
     +  STOP 'PLEASE RESET DSSAT.RZX FILE FOR DSSAT SIMULATION CONTROL'       
      CALL ECHO(IPDSSAT)
      READ(IPDSSAT,*) IOX,IDETO,IDETS,FROP,IDETG,IDETC,IDETW,IDETN,IDETP
     +,IDETD,IDETL,TRTNO

      CALL ECHO(IPDSSAT)
      READ(IPDSSAT,*) NLAYRO
      DO 222 I=1,NLAYRO
        READ(IPDSSAT,*) WR(I)      !ROOT DISTRIBUTION
222   CONTINUE

      CALL ECHO(IPDSSAT)
      READ (IPDSSAT,100)FILENAME
      PATHCR=FILENAME(1:255)                 !PATH TO SPECIES DATABASES
      PATHEC=PATHCR(1:255)                   !PATH TO ECOTYPE FILES
      READ (IPDSSAT,100)FILENAME
      PATHGE=FILENAME(1:255)                 !PATH TO CULTIVAR FILES
      READ (IPDSSAT,*) NUMPLNT
      DO 111 I = 1,NUMPLNT
        READ (IPDSSAT,100) FILENAME
        IF (INDEX(FILENAME,SPECIES) .GT. 0) THEN
          !IT'S A CERES FILE NAME
          IF (INDEX(FILENAME,CROP) .GT. 0) THEN
            !IT'S A MATCH
            FILENAME(9:12)=".CUL"  !CULTIVAR FILE NAME
            FILEG = FILENAME(1:12)
            FILENAME(9:12)=".ECO"  !ECOTYPE FILE NAME
            FILEE = FILENAME(1:12)
            FILENAME(9:12)=".SPE"  !SPECIES FILE NAME
            FILEC = FILENAME(1:12)
          ENDIF
        ENDIF
111   CONTINUE

100   FORMAT(A255)
      CLOSE (IPDSSAT)
      RETURN
500   PRINT*,' -- ERROR -- ERROR -- UNABLE TO OPEN IPDSSAT --'
      END
