! RZinterrupt.for Balaji Pokuri, Jan 2022
C Utility code to save plant state and resume on next run
      SUBROUTINE PLSTATWRITE()
C
C======================================================================
C
C       PURPOSE:  SAVE PLANT GROWTH STATE VARIABLES TO PLSTAT.DAT
C
C
C       VARIABLE DEFINITIONS:
C       VARIABLE  I/O DESCRIPTION
C       --------  --- -----------
C
C       EXTERNAL REFERENCES: None
C
C       CALLED FROM: MAIN
C
C       PROGRAMMER: BALAJI POKURI
C
C       VERSION: 0.1
C       COMMON blocks taken primarily from MAPLNT()
C======================================================================
C
      USE ModuleDefs
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C     LOAD ALL VARIABLES WE CAN GET
C
C     Variables from RZmain.for
C
      PARAMETER(MXNOD=300,MXNODT=3001,MAXHOR=12,MAXSCT=11,MXCHEM=15,
     +    MXPEST=3,MXAPP=200,MXSPEC=10,MXANA=135,MHR=24)
      PARAMETER(MXTN=39,MXTNC=27,MXTP=19)
      PARAMETER(MXTSTP=5000,rhoi=9.2d2,rhol=1.0d3)
      PARAMETER(R2D=180.0D0/3.141592654D0,FCR=0.4d0)
      PARAMETER(MX2=MXNOD*2,MXC=MXNOD*MXCHEM,MXN=MXNOD*25,MXP=MXNOD*
     +    MXPEST,MAPA=MXAPP*4,MXTPP=MXPEST*MXTP)
      PARAMETER(MAXBP=50)
      PARAMETER(LX2=MAXHOR*13,LX3=MAXHOR*8,LX4=MAXHOR*5,LX5=MXAPP*2,LX6=
     +    MAXHOR*MAXSCT*3,MXPE=MXNOD*MXPEST,LX7=MXNOD*3,LST=5*MXSPEC,LDV
     +    =6*MXSPEC,MXAPP3=MXAPP*3,MXAPP20=MXAPP*20,MXAPP00=MXAPP*200)
      PARAMETER(MXHCH=MXNOD*MXCHEM,MXNCH=MXNODT*MXCHEM,MXTCH=MXTSTP*
     +    MXCHEM)
      PARAMETER(NUMSCN=7,NUMSCA=107,NUMVEC=59,IHZNUM=21,MAXSCA=41,MAXVEC
     +    =23)
      PARAMETER(TTN=-50.0D0,TTX=50.0D0,TUN=45.0D0,TUX=4700.0D0,TRN=
     +    0.0D0,TRX=45.0D0,TRHN=0.0D0,TRHX=100.0D0,UBREEZ=100.0D0)
      PARAMETER(IKEN=8+13+5+3*MAXSCT+8)
      PARAMETER(MXTNCA=9)
      PARAMETER(IFILE=432,CARBCV=1.0D0/0.58D0)
      INTEGER YESMAC

      COMMON /HEAT/ CSH(MXNOD),T(MXNOD),SOLTP1(MAXHOR,5),
     +    SOLTP2(MAXSCT,MAXHOR,3)
      COMMON /GEOMTR/XLONG,ASPECT,DELZ(MXNOD),ELEV,HORTHK(MAXHOR),SLOPE,
     +    AREA,TL(MXNOD),TLT(MXNOD),XLAT,ZN(MXNOD),NHOR,NN,NNT
      COMMON /HYDROL/ AEF,BOTFLX,DRDEP,DRSPAC,DRRAD,CLAT(MAXHOR),
     +    HEAT(MXNOD),HKBAR(MXNOD),QF(MXNOD),SOILHP(13,MAXHOR),HFC,HWP,
     +    THETA(MXNOD),thetai(mxnod),RICH_EPS,IREBOT,ITBL,IDRAIN,
     +    MAXITER_RICH,MAXCYCLE_RICH
      COMMON /IPMACF/ AGSZ(MAXHOR),FDEP(MAXHOR),MCPOR(MAXHOR),PI,
     +    PL(MAXHOR),RP(MAXHOR),SFCT,TWOPI,WP(MAXHOR),NHCMP,YESMAC,
     +    EFFWR,EFFWC,XPRESF
      COMMON /PLNTG/ PLDEN(MXAPP),PLTDAY(MXAPP,2),ROWSP(MXAPP),
     +    PLDEPTH(MXAPP),sdwtplr(mxapp),sdager(mxapp),sprlapr(mxapp),
     +    PLNTSW(MXAPP),PLNTWD(MXAPP),LAYNDX(MXAPP),NPGS,NPR(MXAPP),
     +    NGPL(MXAPP),iptype(mxapp),iemrg(mxapp)
      common /gleams/rzrainfall,rzirrigation,rzrunoff
      common /Gleams_hydsol/gleams_clay,gleams_silt,gleams_por,
     +        gleams_om1,gleams_sand,gleams_BulkDn,gleams_Dacre, 
     +        gleams_CHS,gleams_ei,gleams_exrain,thirtyRR,  
     +        IBYEAR,IEYEAR 
      common /po4log/ErosionActive,UseEnrichment
      COMMON /SOIL/ SOILPP(8,MAXHOR),pori(mxnod)
      COMMON /NDEX/ NDXN2H(MXNOD),NDXH2N(MAXHOR),NDXN2T(MXNOD),
     +    NDXT2N(MXNODT)
      COMMON /RZPEST/ HALFF(MXPEST),HALFFP(MXPEST),HALFFB(MXPEST),
     +    HALFR(MXPEST),HALFRP(MXPEST),HALFRB(MXPEST),HALFSSA(MXPEST),
     +    HALFSSV(MXPEST),HALFSSP(MXPEST),HALFSSB(MXPEST),
     +    HALFSA(MXPEST),HALFSN(MXPEST),HALFSB(MXPEST),HALFBD(MXPEST),
     +    XKH(MXPEST),XKOC(MXPEST),XMW(MXPEST),THETAR(MXPEST),
     +    TMPR(MXPEST),EA(MXPEST),EN(MXPEST),WALKERB(MXPEST),
     +    VMAX(MXPEST),DYIELD(4,MXPEST),FREUND(MXPEST),XPKA(MXPEST),
     +    XPKB(MXPEST),REFPH(MXPEST),CATKOC(MXPEST),ANKOC(MXPEST),
     +    PCOEFF(MXPEST),PPOWER(MXPEST),RCOEFF(MXPEST),RPOWER(MXPEST),
     +    XKOW(MXPEST),PBIND(MXPEST),IPCODE(4,MXPEST),IPANC(MXPEST),
     +    IPDEP(MXPEST),IPACTV(MXPEST),NPEST
      common /maxbal/IDmxH2O,IMmxH2O,IYYYmxH2O,IDmxN,IMmxN,IYYYmxN,
     +              IDmxC,IMmxC,IYYYmxC,IDmxP,IMmxP,IYYYmxP,
     +              DTMASSmxH2O,BalmxN,BalmxC,BalmxP,IWCINIT1
     +            ,ireset1
      COMMON /KNTCS/ CONCX2(MXNOD,MXPEST),EK2(MXNOD,MXPEST),
     +    RK2(MXPEST),RDIF(MXPEST),FEK2(MXPEST),IEK2(MXPEST)
      COMMON /RESID/ RM,RESAGE,CRES,HR,RCN,NADLY,NSDLY,NAREC,NSREC,WORM,
     +               SAI,HSTUBL,WSTUBL
      COMMON /PLNTDA/ CLSIZE(0:7),PSTATE(9),PWRTS,DMDNIT,TNITUP,GS,
     +    CNUP1(MXSPEC),CNUP2(MXSPEC),UPLUX
      COMMON /NUTPAR/ R14,R23,R34,R43,R45,R53,R15,R25,EFFMAX,EFFNIT,
     +    EFFDEN,DENC,RPOP(3),ADCAY,ANIT,ADENIT,AUREA,ADEATH(3),CN(9),
     +    ADCAYV(5),XKP(3),AMETH,FRN2O_NIT,FRN2O_DEN,RNO_N2O,RAINNO,
     +    O2LIM,EFFMETH,ISBUG
      COMMON /PINFO/ TSOTP0(MXPEST),TAPAP(MXPEST),TLPRS(MXPEST),
     +    TLPCN(MXPEST),TLPSL(MXPEST),TLPRO(MXPEST),TLPLC(MXPEST),
     +    TDPPLNT(MXPEST),TLPDT(MXPEST),TLPDTD(MXPEST),
     +    TLPDTL(MXPEST),TLPDMA(MXPEST)
      COMMON /SC1/ ISTAB,IVTAB,ISPLT,IVPLT
      COMMON /IPOTEV/ A0,AW,AC,ARI,XW,FSUN,COEPAN,rss,RST(MXSPEC)
     +    ,RXANGLE(MXSPEC),RTCCRIT(MXSPEC),RPLEAF0(MXSPEC),
     +      RRSTEXP(MXSPEC),RRLEAF0(MXSPEC)
      common /sumet/sumAET,sumCropET,sumPET,sumPT,sumAT,sumrain,deltheta
      common /hourweather/ hrt,hrts,hru,hrh,HRZPAR,HRTH
      common /wsi/ wsi, alaireset, heightset, iresetlai, iresetht1
C
C     BLOCK DATA BLOCK1
C
      COMMON /IRRIG/ DOIMAX(MXAPP),FDOI(MXAPP),VDOI(MXAPP,MXAPP),
     +    XKU(MXAPP,20),XMAD(MXAPP,20),RRATE(MXAPP),amxirr,
     +    totaliw,DOIMONTH(12,200),TOTALMONTH,airrdepth,amirr,
     +    RRDUR(MXAPP),IIPL(MXAPP),ISPT(MXAPP),ITOI(MXAPP),
     +    JDIRRB(MXAPP),JDIRRE(MXAPP),NAPPI,NDAIRR(MXAPP),NKU(MXAPP),
     +    NMAD(MXAPP),JDOI(MXAPP,MXAPP),JKU(MXAPP,20),JMAD(MXAPP,20),
     +    IDOI(MXAPP),id_depth,MONTHIRR
      COMMON /PLNTIN/ AHLDG(MXSPEC),ALA(MXSPEC),ALNAVL(MXSPEC),
     +    ALNGER(MXSPEC),ALNLW(MXSPEC),ALPHA(MXSPEC),ALX(MXSPEC),
     +    BETA(MXSPEC),BGSEED(MXSPEC),CAA(MXSPEC),CANK(MXSPEC),
     +    CAX(MXSPEC),CONVLA(MXSPEC),CVLBIO(MXSPEC),DEVRAT(2:7,MXSPEC),
     +    DROTOL(MXSPEC),EFFN(MXSPEC),DTSEED(MXSPEC),GITEMP(MXSPEC),
     +    GIWAT(MXSPEC),GMN(MXSPEC),GRMRAT(MXSPEC),GSR(MXSPEC),
     +    HFMAX(MXSPEC),PCLDG(MXSPEC),PGDVRT(MXSPEC),PGNTGT(MXSPEC),
     +    PLALFA(MXSPEC),PLBIO(MXSPEC),PLDIAM(MXSPEC),PLHGHT(MXSPEC),
     +    PLTMNT(MXSPEC),PLTMXT(MXSPEC),PLTOPT(MXSPEC),PMAX(MXSPEC),
     +    PMAXN(MXSPEC),PNRED(MXSPEC),PMNNIT(MXSPEC),PRNLW(MXSPEC),
     +    PTLAMX(MXSPEC),R20(MXSPEC),RATLS(MXSPEC),RATRSX(MXSPEC),
     +    RATRSN(MXSPEC),RDR(MXSPEC),RDX(MXSPEC),RQ10(MXSPEC),
     +    RTNLW(MXSPEC),SDAMAX(MXSPEC),SDDVRT(MXSPEC),SDSVRT(MXSPEC),
     +    SDTMGM(MXSPEC),SDWMAX(MXSPEC),SFREEZ(MXSPEC),SLA1(MXSPEC),
     +    SLA2(MXSPEC),SLA3(MXSPEC),SLA4(MXSPEC),STEND(2:6,MXSPEC),
     +    STNAVL(MXSPEC),STNGER(MXSPEC),STNLW(MXSPEC),TBS(MXSPEC),
     +    TOP(MXSPEC),TOT4WT(MXSPEC),WCG(MXSPEC),WCP(MXSPEC),
     +    WDLDG(MXSPEC),CNST(MXSPEC),PRB(7,7,MXSPEC),GSGDD(2:6,MXSPEC),
     +    GDDFLG(MXSPEC),VRNLZ(MXSPEC),SUFNDX(MXSPEC),IPLTYP(MXSPEC),
     +    LWM(MXSPEC),LWS(MXSPEC),NPL,INFIXN(MXSPEC)
      COMMON /HRVST/ HSTAGE(MXAPP),HPERC(MXAPP),HRVEFF(MXAPP),YIELD(3),
     +    STUBHT(MXAPP),IHTYPE(MXAPP),IHDAY(MXAPP,3),IHARV(MXAPP),
     +    IHCL(MXAPP)
      COMMON /SCCONC/ AL,ALOH,ALSO4,CA,CASO4,H,HCO3,SO4,XMG,XMGSO4,XNA,
     +    XNASO4,XNAORG,XNH4,ORG,CO3,ALORG,ALI,ALOHI,ALSO4I,CAI,CO3I,HI,
     +    HCO3I,ORGI,SO4I,XMGI,XNAI,XNH4I,ALIS,ALOHIS,ALSOIS,CAIS,CO3IS,
     +    HIS,HCO3IS,ORGIS,SO4IS,XMGIS,XNAIS,XNASIS,XNH4IS,ALORIS
      COMMON /SCHMIN/ ECA(MXNOD),ENA(MXNOD),EMG(MXNOD),ENH4(MXNOD),
     +    EAL(MXNOD),SCL(MXNOD,3),CEC(MXNOD)
      COMMON /INFILC/ RAC(11),RRC(11),FERTIR(4),PESTIR(MXPEST),FMNRIR
      COMMON /OPINF/ RO,SWF(MXnod),TR(MXTSTP),CI(MXTSTP),CRFD(MAXBP),
     +    CRFT(MAXBP),RFI(MAXBP),RFDD,RFD
      COMMON /OPCHEM/ THSMS(MXNOD,MXCHEM),CUPRO,CUPCHM(MXCHEM),CDNCI,
     +    CDNCHM(MXCHEM),CMESO(MXNODT,MXCHEM),CMICR(MXNODT,MXCHEM),
     +    CRO(MXTSTP,MXCHEM)
      COMMON /OPMACF/ CDBET(MXNODT,MXCHEM),CFLOW(MXNODT,MXCHEM),
     +    CDFLOW(MXNODT,MXCHEM),CUMCLM(MXTSTP,MXCHEM),
     +    CUMCLR(MXTSTP,MXCHEM),CUMMF(MXTSTP),CUMRO(MXTSTP),
     +    DBET(MXNODT),DFLOW(MXNODT),FLOW(MXNODT),TDFLOW(MXNODT),
     +    TFLOW(MXNODT)
      COMMON /IPCHEM/ A,ALH(MXNOD,MXCHEM),B,BDH(MAXHOR),DEG(MAXHOR),
     +    BDHR(MAXHOR),MICP(MAXHOR),NMICP
      COMMON /IPINF/ CRUSTK,OCRUST,ICRUST,INFLPD,NHZ,NSLT,POND,RR,
     +    DHB(MAXHOR),NSL(MAXHOR),WI(MXnod),DSL(MXNODT),VWC(MXNODT),
     +    IUGFLW
      COMMON /INTMCF/ FLXMAX(MAXHOR),DB(MAXHOR),NPOR(MAXHOR)
      COMMON /MMNUR/ AMNH4(MXAPP),AMOW(MXAPP),AMBED(MXAPP),
     +    CNBED(MXAPP),AMCN(15),CNMANR(MXAPP),FCMANR(MXAPP),
     +    IWMANR(MXAPP),IMOFF(MXAPP,2),IMMETH(MXAPP),IMTYPE(MXAPP),
     +    NAPPM,IMPL(MXAPP),IMANDECOMP(MXAPP)
      COMMON /MFERT/ FNH4IN(MXAPP),FNO3IN(MXAPP),FUREIN(MXAPP),
     +    SPLTST(MXAPP),SPLTAP(MXAPP),IFOFF(MXAPP,2),IFMETH(MXAPP),
     +    IWFERT(MXAPP),NAPPF,IBMPAP(MXAPP),IBMPMD(MXAPP),
     +    IDSPLT(MXAPP),IFPL(MXAPP)
      COMMON /MPEST/ APP(MXAPP),PDR(MXAPP),IAPP(MXAPP),IPOFF(MXAPP,2),
     +    IWPEST(MXAPP),IPMETH(MXAPP),NAPP,IPPL(MXAPP)
      COMMON /TILLIN/ OBD(2),OFDP(2),TDEPTH(30),TILINT(30,2),
     +    TNDX(MXAPP),UDEPTH(MXAPP), PManureMix(MXAPP), IMP(MXAPP),  
     +    ITL(MXAPP), ITOFF(MXAPP,2),IWTILL(MXAPP),NUMTL, ITPL(MXAPP)
C
C     BLOCK DATA BLKOUT
C
      COMMON /SSLIST/ SCASSL,USSSL,VECSSL,UVSSL,ASSSL,AVSSL
      COMMON /FUNIT/ SC,CNTRL,SCAPLT,VECPLT,SCATAB,VECTAB,ISCA,IVEC
      COMMON /LABLS/ SCNRIO,SCALAR,VECTOR,HZLABS

      TYPE (PLANTVARType) PLANTVAR
      TYPE (SwitchType) ISWITCH
      TYPE (ControlType) CONTROL

      INTEGER IRPL, NYR, NYRC
      DIMENSION ADIW(MXAPP),NYRP(MXPEST),ADIWMONTH(12,200),totadiw(20)
      LOGICAL SPLT1,FIRST7

      CHARACTER*1 IDETW, ISWWAT, RNMODE
      INTEGER DAS, DOY, DYNAMIC, ERRNUM, FROP, NAVWB, NAP, NOUTDW,
     + RUN, YEAR, YRDOY, REPNO
      REAL AVWTD, PESW, TLL, TOTBUNDRO, TOTIR, TSW

      INTEGER NVALP0
      INTEGER YREMRG, MDATE
      integer istage
      INTEGER STGDOY(20)

      REAL CANHT, EORATIO
      REAL KCAN, KEP, KSEVAP, KTRANS, NSTRES
      REAL PORMIN, RWUEP1, RWUMX
      REAL XLAI, XHLAI

      REAL LFWT,STMWT,XSTAGE,DTT,BIOMAS,SDWT,GRNWT,EARS
      REAL RTWT,STOVWT,STOVN,ROOTN,GRAINN,RTDEP
      REAL NFIXN,TOPWT,WTLF,PCNL,PCNST,PCNRT,PCNSD
      real trnu,swfac,grwt,cwad,tfg,wfg,cnad,stwt,nupd,gnad,rtwts
      REAL, DIMENSION(20) :: RLV, UNO3, UNH4
      LOGICAL FixCanht
      TYPE (ResidueType) HARVRES, SENESCE


      CHARACTER*6     SECTION       
      CHARACTER*30    FILEIO 
      CHARACTER*80    C80
      CHARACTER*255   FILECC

      REAL        AREALF, ASMDOT, BD(20), CANWH, CARBOT, 
     + CO2X(10), CO2Y(10), DUMMY, EP1, pp1, pp2, FSLFW, FSLFN, 
     + GRF, GROEAR, GROGRN, GROLF, GROSTM, HI, HIP, LAIDOT, LEAFNOE,
     + CumLeafSenes, CumLeafSenesY, CumLfNSenes, LFWTE, LIFAC, TAW,DTAW, 
     + NDEF3, NFAC, NPOOL, NPOOL1, NPOOL2, NSDR, NSINK, P3, PAR, 
     + PARSR, PC, PCARB, PCNGRN, PCO2, 
     + PRFTC(4), SLPF, PLAE, PLAS, PODNO, PODWT, PPLTD, PRFT, RANC, 
     + RANCE, RGFILL, RGFIL(4), RLWR, RMNC, RNLAB, RNOUT, RSGR, RSGRT, 
     + RTWO, RTWTE, RTWTO, RUE, SATFAC, SDSIZE, SDSZ, 
     + SEEDNO, SEEDRV, SEEDRVE, SFAC, SHELPC, SI1(6), SI2(6), SI3(6), 
     + SI4(6), SLAN, SLA, SLFC, SLFN, SLFT, SLFW, Stg2CLS, STMWTO, 
     + STMWTE, SUMEX, SUMRL, SWEXF, SWIDOT, SWMAX, SWMIN, 
     + TANCE, TAVGD, TCNP, TEMPM, TFAC, TI, TMNC, TNLAB, 
     + TSS(20), VANC, VSTAGE, WLIDOT, WRIDOT, WSIDOT, XANC, 
     + XLFWT, XNF, YIELDB, RZrwu(300), RZtrwup, AVG_HROOT, WTDEP, 
     + qsr(300), TRWUP1
      INTEGER     CMAT, EMAT, FOUND, I, ICOLD, ISECT, L, LINC, LNUM, 
     + LUNCRP, LUNIO, NWSD, RSTAGE, PATHL, yrplt, ISTRESS, iresetlai, 
     + iresetht1
      DOUBLE PRECISION alaireset, WSI(10),heightset

      REAL            ABSTRES         
      REAL            ACOEF           
      REAL            BARFAC 
      REAL            C1              
      REAL            CUMDTT          
      REAL            DEC             
      REAL            DGET
      REAL            DJTI
      REAL            DLV             
      REAL            DOPT                      
      REAL            DSGT
      REAL            DSGFT
      REAL            GDDE
      REAL            GPP            
      REAL            P2O            
      REAL            P9             
      REAL            PDTT
      REAL            PSKER          
      REAL            RATEIN         
      REAL            ROPT           
      REAL            S1             
      REAL            SIND           
      REAL            SNDN           
      REAL            SNUP           
      REAL            SUMDTT         
      REAL            SWCG
      REAL            SWSD           
      REAL            TBASE          
      REAL            TDSOIL         
      REAL            TEMPCN         
                                     
      REAL            TEMPCR         
      REAL            TEMPCX         
      REAL            TH             
      REAL            TLNO           
      REAL            TMSOIL         
      REAL            TNSOIL         
      REAL            TOPT           
      REAL            XNTI           
      REAL            XS             
      REAL            tdsoil1,tnsoil1,tmsoil1         

      INTEGER         L0             
      INTEGER         NDAS           
      INTEGER ISDATE          
      INTEGER IPATH
      INTEGER LUNECO

      CHARACTER*6 ECOTYP
      CHARACTER*255 C255
      CHARACTER*255    FILEGC
      CHARACTER*16  ECONAM

C
C
C    Now Open the dat file to write
C
C
      OPEN(IFILE,FILE='PLSTAT.DAT',STATUS='UNKNOWN', ERR=50)
C
C
C    Write each set of common variables in sequence
C
C
      PRINT *, "WRITING PLSTAT.DAT"
C     Explicitly specify sequence for custom datatypes

      CALL GETPUT_MZ_PHENOL('GET', ABSTRES, ACOEF, BARFAC, C1, 
     + DEC, DGET, DJTI, DLV, DOPT, DSGT, DSGFT, DUMMY, 
     + GDDE, P2O, P9, PDTT, PSKER, RATEIN, 
     + ROPT, S1, SIND, SNDN, SNUP, SWCG, SWSD, TBASE, 
     + TDSOIL, TEMPCN, TEMPCR, TEMPCX, TH, TMSOIL, TNSOIL, TOPT, 
     + XS, tdsoil1, tnsoil1, tmsoil1, FOUND, L, 
     + L0, LINC, LNUM, LUNIO, NDAS, PATHL, 
     + LUNECO, ISECT, LUNCRP, SECTION, ECOTYP, C255, FILEGC, 
     + ECONAM, C80)
      WRITE(IFILE, *) ABSTRES, ACOEF, BARFAC, C1, 
     + DEC, DGET, DJTI, DLV, DOPT, DSGT, DSGFT, DUMMY, 
     + GDDE, P2O, P9, PDTT, PSKER, RATEIN, 
     + ROPT, S1, SIND, SNDN, SNUP, SWCG, SWSD, TBASE, 
     + TDSOIL, TEMPCN, TEMPCR, TEMPCX, TH, TMSOIL, TNSOIL, TOPT, 
     + XS, tdsoil1, tnsoil1, tmsoil1, FOUND, L, 
     + L0, LINC, LNUM, LUNIO, NDAS, PATHL, 
     + LUNECO, ISECT, LUNCRP
      WRITE(IFILE, '(A6,A6,A255,A255,A16,A80)') SECTION, ECOTYP, C255,
     +  FILEGC, ECONAM, C80


      WRITE(IFILE,*) '==============MZ_GROSUB========================'
      CALL GETPUT_MZ_GROSUB('GET', SECTION, C80, FILECC, 
     +  CARBOT, CO2X, CO2Y, 
     +  DUMMY, EP1, pp1, pp2, FSLFW, FSLFN, GRF, GROEAR, GROGRN, 
     +  GROLF, GROSTM, LAIDOT, LEAFNOE, CumLeafSenes, 
     +  CumLeafSenesY, CumLfNSenes, LFWTE, LIFAC, TAW, DTAW, NDEF3, 
     +  NFAC, NPOOL, NPOOL1, NPOOL2, NSDR, NSINK, PAR, 
     +  PARSR, PC, PCARB, PCO2, 
     +  PRFTC, SLPF, PLAE, PLAS, PRFT, RANC, 
     +  RANCE, RGFILL, RGFIL, RMNC, RNLAB, RNOUT, RSGR, RSGRT, RTWTE,
     +  SEEDRV, SEEDRVE, SFAC, SI1, SI2, SI3, SI4, 
     +  SLAN, SLFC, SLFN, SLFT, SLFW, Stg2CLS, STMWTE, 
     +  SUMEX, SUMRL, SWEXF, SWMAX, SWMIN, TANCE, 
     +  TAVGD, TCNP, TEMPM, TFAC, TI, TMNC, TNLAB, TSS, 
     +  VANC, XANC, XLFWT, 
     +  XNF, YIELDB, RZrwu, RZtrwup, AVG_HROOT, WTDEP, qsr, TRWUP1, 
     +  CMAT, EMAT, FOUND, I, ICOLD, ISECT, L, LINC, LNUM, LUNCRP, 
     +  LUNIO, NWSD, PATHL, ISTRESS, iresetlai,iresetht1,
     +  alaireset, WSI, heightset)
      WRITE(IFILE,'(A6,A80,A255)') SECTION, C80, FILECC
      WRITE(IFILE,*) CARBOT, CO2X, CO2Y, 
     +  DUMMY, EP1, pp1, pp2, FSLFW, FSLFN, GRF, GROEAR, GROGRN, 
     +  GROLF, GROSTM, LAIDOT, LEAFNOE, CumLeafSenes, 
     +  CumLeafSenesY, CumLfNSenes, LFWTE, LIFAC, TAW, DTAW, NDEF3, 
     +  NFAC, NPOOL, NPOOL1, NPOOL2, NSDR, NSINK, PAR, 
     +  PARSR, PC, PCARB, PCO2, 
     +  PRFTC, SLPF, PLAE, PLAS, PRFT, RANC, 
     +  RANCE, RGFILL, RGFIL, RMNC, RNLAB, RNOUT, RSGR, RSGRT, RTWTE,
     +  SEEDRV, SEEDRVE, SFAC, SI1, SI2, SI3, SI4, 
     +  SLAN, SLFC, SLFN, SLFT, SLFW, Stg2CLS, STMWTE, 
     +  SUMEX, SUMRL, SWEXF, SWMAX, SWMIN, TANCE, 
     +  TAVGD, TCNP, TEMPM, TFAC, TI, TMNC, TNLAB, TSS, 
     +  VANC, XANC, XLFWT, 
     +  XNF, YIELDB, RZrwu, RZtrwup, AVG_HROOT, WTDEP, qsr, TRWUP1, 
     +  CMAT, EMAT, FOUND, I, ICOLD, ISECT, L, LINC, LNUM, LUNCRP, 
     +  LUNIO, NWSD, PATHL, ISTRESS, iresetlai,iresetht1,
     +  alaireset, WSI, heightset

C       WRITE(IFILE,*) CMAT, EMAT, FOUND, I, ICOLD, ISECT, L, LINC, LNUM, 
C      + LUNCRP, LUNIO, NWSD, RSTAGE, PATHL, yrplt, ISTRESS, iresetlai, 
C      + iresetht1
C       WRITE(IFILE,*) alaireset, WSI,heightset



      CALL GETPUT_MZ_NFACTO('GET', AGEFAC, NDEF3, NFAC, NSTRES)
      WRITE(IFILE,*) AGEFAC, NDEF3, NFAC, NSTRES

      CALL Alt_Plant_Memory('GET', NVALP0, YREMRG, MDATE, STGDOY, 
     +  CANHT, EORATIO, KCAN, KEP, KSEVAP, KTRANS, NSTRES, PORMIN, 
     +  RWUEP1, RWUMX, XLAI, XHLAI, RLV, UNO3, UNH4, LFWT, STMWT, 
     +  XSTAGE, DTT, BIOMAS, SDWT, GRNWT, EARS, RTWT, STOVWT, STOVN, 
     +  ROOTN, GRAINN, RTDEP, NFIXN, TOPWT, WTLF, PCNL, PCNST, PCNRT, 
     +  PCNSD, trnu, swfac, grwt, cwad, tfg, wfg, cnad, stwt, nupd, 
     +  gnad, rtwts, istage, FixCanht, HARVRES, SENESCE)      
      WRITE(IFILE, *) NVALP0, YREMRG, MDATE, istage
      WRITE(IFILE, *) STGDOY(20)

      WRITE(IFILE, *) CANHT, EORATIO, KCAN, KEP, KSEVAP, KTRANS, NSTRES, 
     + PORMIN, RWUEP1, RWUMX, XLAI, XHLAI, LFWT, STMWT, XSTAGE, DTT, 
     + BIOMAS, SDWT, GRNWT, EARS, RTWT, STOVWT, STOVN, ROOTN, GRAINN, 
     + RTDEP, NFIXN, TOPWT, WTLF, PCNL, PCNST, PCNRT, PCNSD
      WRITE(IFILE, *) trnu, swfac, grwt, cwad, tfg, wfg, cnad, stwt, 
     + nupd, gnad, rtwts
      WRITE(IFILE, *) RLV, UNO3, UNH4
      WRITE(IFILE, *) FixCanht

      WRITE(IFILE, *) HARVRES
      WRITE(IFILE, *) SENESCE


      CALL OPWBAL_Memory('GET', IDETW, ISWWAT, RNMODE, DAS, DOY, 
     +  DYNAMIC, ERRNUM, FROP, NAVWB, NAP, NOUTDW, RUN, YEAR, 
     +  YRDOY, REPNO, AVWTD, PESW, TLL, TOTBUNDRO, TOTIR, TSW)
      WRITE(IFILE,'(3A1)') IDETW, ISWWAT, RNMODE
      WRITE(IFILE,'(12I)') DAS,DOY, DYNAMIC, ERRNUM, FROP, NAVWB, NAP,
     + NOUTDW, RUN, YEAR, YRDOY, REPNO
      WRITE(IFILE,'(6e)') AVWTD, PESW, TLL, TOTBUNDRO, TOTIR, TSW

      CALL MAPLNT_Memory('GET',nreps,FIRST11,first15,PCN,TTPLNT,
     +  TMPLNT,TXPLNT,IJ)
      WRITE(IFILE,*) nreps,FIRST11,first15,PCN,TTPLNT,TMPLNT,TXPLNT,IJ
      CALL DSSATDRV_Memory('GET', oldhgt,PLHGHT,PLALFA)
      WRITE(IFILE, *) oldhgt,PLHGHT,PLALFA
      CALL DAYJACK_Memory('GET',LID,LIM,LIYYY,JSEQDAY,CURSTATE)
      WRITE(IFILE,*) LID,LIM,LIYYY,JSEQDAY,CURSTATE
      CALL MAQUE_Memory('GET',ADIW,JSPLT,SPLT1,FIRST7,NYR,IRPL,NYRC,
     +  NYRP,ADIWMONTH,totadiw,curradiw)
      WRITE(IFILE, *) ADIW,JSPLT,SPLT1,FIRST7,NYR,IRPL,NYRC,
     +  NYRP,ADIWMONTH,totadiw,curradiw

      CALL GETPUT_PLANTVAR('GET', PLANTVAR)
C       WRITE(IFILE,*) PLANTVAR%VARNO,PLANTVAR%ECONO          
C       WRITE(IFILE,*) PLANTVAR%VRNAME
C       WRITE(IFILE,*) PLANTVAR%PLME
      WRITE(IFILE,*) PLANTVAR%HDATE
      WRITE(IFILE,*) PLANTVAR%HPC, PLANTVAR%HBPC, PLANTVAR%HRPC
      WRITE(IFILE,*) PLANTVAR%PLTPOP,PLANTVAR%ROWSPC,PLANTVAR%SDEPTH,
     + PLANTVAR%AZIR,PLANTVAR%SDWTPL,PLANTVAR%SDAGE,PLANTVAR%SPRLAP
      WRITE(IFILE,*) PLANTVAR%P1,PLANTVAR%P1V,PLANTVAR%P1D,PLANTVAR%P2,
     + PLANTVAR%P2O,PLANTVAR%P2R,PLANTVAR%P3,PLANTVAR%P4,PLANTVAR%P5,
     + PLANTVAR%G1,PLANTVAR%G2,PLANTVAR%G3,PLANTVAR%G4
      WRITE(IFILE,*) PLANTVAR%PHINT,PLANTVAR%PD,PLANTVAR%TC,PLANTVAR%O1,
     + PLANTVAR%GPROT,PLANTVAR%LT50H
      WRITE(IFILE,*) PLANTVAR%CSDVAR,PLANTVAR%PHTHRS,PLANTVAR%SDPDVR,
     + PLANTVAR%SLAVAR,PLANTVAR%LFMAX,PLANTVAR%XFRUIT,PLANTVAR%WTPSD
      WRITE(IFILE,*) PLANTVAR%SFDUR,PLANTVAR%PODUR,PLANTVAR%PPSEN,
     + PLANTVAR%PH2T5,PLANTVAR%SIZELF
      WRITE(IFILE,*) PLANTVAR%RATPOT,PLANTVAR%PI1,PLANTVAR%PI2,
     + PLANTVAR%DTTPI
      WRITE(IFILE,*) PLANTVAR%PCINT,PLANTVAR%PCGRD
      WRITE(IFILE,*) PLANTVAR%GCOEFF
      WRITE(IFILE,*) PLANTVAR%SCPB,PLANTVAR%RESPC,PLANTVAR%SQCON,
     + PLANTVAR%FCUT,PLANTVAR%FLAI,PLANTVAR%DDISQ
      WRITE(IFILE,*) PLANTVAR%EFINOC,PLANTVAR% EFNFIX
      WRITE(IFILE,*) PLANTVAR%RESAMT,PLANTVAR%ATEMP

      CALL GETPUT_CONTROL('GET', CONTROL)
      WRITE(IFILE,'(A1,A1,A2,A12)') CONTROL%MESIC, CONTROL%RNMODE,
     + CONTROL%CROP, CONTROL%MODEL
      WRITE(IFILE,*) CONTROL%DAS, CONTROL%DYNAMIC, CONTROL%FROP, 
     + CONTROL%MULTI, CONTROL%REPNO, CONTROL%RUN
      WRITE(IFILE,*) CONTROL%TRTNO, CONTROL%YRDOY, CONTROL%YRSIM, 
     + CONTROL%NYRS, CONTROL%YRDIF, CONTROL%ROTNUM
      WRITE(IFILE,*) CONTROL%EXPER
      WRITE(IFILE,*) CONTROL%ENAME
      WRITE(IFILE,*) CONTROL%TITLET
      WRITE(IFILE,*) CONTROL%YRPLT, CONTROL%IEMRG

      CALL GETPUT_ISWITCH('GET', ISWITCH)
      WRITE(IFILE,'(21A1,I)') ISWITCH%IDETC,ISWITCH%IDETD,ISWITCH%IDETG, 
     + ISWITCH%IDETL, ISWITCH%IDETN, ISWITCH%IDETO, ISWITCH%IDETR, 
     + ISWITCH%IDETS, ISWITCH%IDETW, ISWITCH%IHARI, ISWITCH%IPLTI, 
     + ISWITCH%IIRRI, ISWITCH%ISWDIS, ISWITCH%ISWNIT, 
     + ISWITCH%ISWSYM, ISWITCH%ISWWAT,
     + ISWITCH%MEEVP, ISWITCH%MEPHO, ISWITCH%MESOM,
     + ISWITCH%IFERI, ISWITCH%IRESI, ISWITCH%NSWI


C       Now save the variables from common directories
      WRITE(IFILE,*) CSH(MXNOD),T(MXNOD),SOLTP1(MAXHOR,5),
     +    SOLTP2(MAXSCT,MAXHOR,3)
      WRITE(IFILE,*)XLONG,ASPECT,DELZ(MXNOD),ELEV,HORTHK(MAXHOR),SLOPE,
     +    AREA,TL(MXNOD),TLT(MXNOD),XLAT,ZN(MXNOD),NHOR,NN,NNT
      WRITE(IFILE,*) AEF,BOTFLX,DRDEP,DRSPAC,DRRAD,CLAT(MAXHOR),
     +    HEAT(MXNOD),HKBAR(MXNOD),QF(MXNOD),SOILHP(13,MAXHOR),HFC,HWP,
     +    THETA(MXNOD),thetai(mxnod),RICH_EPS,IREBOT,ITBL,IDRAIN,
     +    MAXITER_RICH,MAXCYCLE_RICH
      WRITE(IFILE,*) AGSZ(MAXHOR),FDEP(MAXHOR),MCPOR(MAXHOR),PI,
     +    PL(MAXHOR),RP(MAXHOR),SFCT,TWOPI,WP(MAXHOR),NHCMP,YESMAC,
     +    EFFWR,EFFWC,XPRESF
      WRITE(IFILE,*) PLDEN(MXAPP),PLTDAY(MXAPP,2),ROWSP(MXAPP),
     +    PLDEPTH(MXAPP),sdwtplr(mxapp),sdager(mxapp),sprlapr(mxapp),
     +    PLNTSW(MXAPP),PLNTWD(MXAPP),LAYNDX(MXAPP),NPGS,NPR(MXAPP),
     +    NGPL(MXAPP),iptype(mxapp),iemrg(mxapp)
      WRITE(IFILE,*)rzrainfall,rzirrigation,rzrunoff
      WRITE(IFILE,*)gleams_clay,gleams_silt,gleams_por,
     +        gleams_om1,gleams_sand,gleams_BulkDn,gleams_Dacre, 
     +        gleams_CHS,gleams_ei,gleams_exrain,thirtyRR,  
     +        IBYEAR,IEYEAR 
      WRITE(IFILE,*)ErosionActive,UseEnrichment
      WRITE(IFILE,*) SOILPP(8,MAXHOR),pori(mxnod)
      WRITE(IFILE,*) NDXN2H(MXNOD),NDXH2N(MAXHOR),NDXN2T(MXNOD),
     +    NDXT2N(MXNODT)
      WRITE(IFILE,*) HALFF(MXPEST),HALFFP(MXPEST),HALFFB(MXPEST),
     +    HALFR(MXPEST),HALFRP(MXPEST),HALFRB(MXPEST),HALFSSA(MXPEST),
     +    HALFSSV(MXPEST),HALFSSP(MXPEST),HALFSSB(MXPEST),
     +    HALFSA(MXPEST),HALFSN(MXPEST),HALFSB(MXPEST),HALFBD(MXPEST),
     +    XKH(MXPEST),XKOC(MXPEST),XMW(MXPEST),THETAR(MXPEST),
     +    TMPR(MXPEST),EA(MXPEST),EN(MXPEST),WALKERB(MXPEST),
     +    VMAX(MXPEST),DYIELD(4,MXPEST),FREUND(MXPEST),XPKA(MXPEST),
     +    XPKB(MXPEST),REFPH(MXPEST),CATKOC(MXPEST),ANKOC(MXPEST),
     +    PCOEFF(MXPEST),PPOWER(MXPEST),RCOEFF(MXPEST),RPOWER(MXPEST),
     +    XKOW(MXPEST),PBIND(MXPEST),IPCODE(4,MXPEST),IPANC(MXPEST),
     +    IPDEP(MXPEST),IPACTV(MXPEST),NPEST
      WRITE(IFILE,*)IDmxH2O,IMmxH2O,IYYYmxH2O,IDmxN,IMmxN,IYYYmxN,
     +              IDmxC,IMmxC,IYYYmxC,IDmxP,IMmxP,IYYYmxP,
     +              DTMASSmxH2O,BalmxN,BalmxC,BalmxP,IWCINIT1
     +            ,ireset1
      WRITE(IFILE,*) CONCX2(MXNOD,MXPEST),EK2(MXNOD,MXPEST),
     +    RK2(MXPEST),RDIF(MXPEST),FEK2(MXPEST),IEK2(MXPEST)
      WRITE(IFILE,*) RM,RESAGE,CRES,HR,RCN,NADLY,NSDLY,NAREC,NSREC,WORM,
     +               SAI,HSTUBL,WSTUBL
      WRITE(IFILE,*) CLSIZE(0:7),PSTATE(9),PWRTS,DMDNIT,TNITUP,GS,
     +    CNUP1(MXSPEC),CNUP2(MXSPEC),UPLUX
      WRITE(IFILE,*) R14,R23,R34,R43,R45,R53,R15,R25,EFFMAX,EFFNIT,
     +    EFFDEN,DENC,RPOP(3),ADCAY,ANIT,ADENIT,AUREA,ADEATH(3),CN(9),
     +    ADCAYV(5),XKP(3),AMETH,FRN2O_NIT,FRN2O_DEN,RNO_N2O,RAINNO,
     +    O2LIM,EFFMETH,ISBUG
      WRITE(IFILE,*) TSOTP0(MXPEST),TAPAP(MXPEST),TLPRS(MXPEST),
     +    TLPCN(MXPEST),TLPSL(MXPEST),TLPRO(MXPEST),TLPLC(MXPEST),
     +    TDPPLNT(MXPEST),TLPDT(MXPEST),TLPDTD(MXPEST),
     +    TLPDTL(MXPEST),TLPDMA(MXPEST)
      WRITE(IFILE,*) ISTAB,IVTAB,ISPLT,IVPLT
      WRITE(IFILE,*) A0,AW,AC,ARI,XW,FSUN,COEPAN,rss,RST(MXSPEC)
     +    ,RXANGLE(MXSPEC),RTCCRIT(MXSPEC),RPLEAF0(MXSPEC),
     +      RRSTEXP(MXSPEC),RRLEAF0(MXSPEC)
      WRITE(IFILE,*)sumAET,sumCropET,sumPET,sumPT,sumAT,sumrain,deltheta
      WRITE(IFILE,*) hrt,hrts,hru,hrh,HRZPAR,HRTH
      WRITE(IFILE,*) wsi, alaireset, heightset, iresetlai, iresetht1
C
C     BLOCK DATA BLOCK1
C
      WRITE(IFILE,*) DOIMAX(MXAPP),FDOI(MXAPP),VDOI(MXAPP,MXAPP),
     +    XKU(MXAPP,20),XMAD(MXAPP,20),RRATE(MXAPP),amxirr,
     +    totaliw,DOIMONTH(12,200),TOTALMONTH,airrdepth,amirr,
     +    RRDUR(MXAPP),IIPL(MXAPP),ISPT(MXAPP),ITOI(MXAPP),
     +    JDIRRB(MXAPP),JDIRRE(MXAPP),NAPPI,NDAIRR(MXAPP),NKU(MXAPP),
     +    NMAD(MXAPP),JDOI(MXAPP,MXAPP),JKU(MXAPP,20),JMAD(MXAPP,20),
     +    IDOI(MXAPP),id_depth,MONTHIRR
      WRITE(IFILE,*) AHLDG(MXSPEC),ALA(MXSPEC),ALNAVL(MXSPEC),
     +    ALNGER(MXSPEC),ALNLW(MXSPEC),ALPHA(MXSPEC),ALX(MXSPEC),
     +    BETA(MXSPEC),BGSEED(MXSPEC),CAA(MXSPEC),CANK(MXSPEC),
     +    CAX(MXSPEC),CONVLA(MXSPEC),CVLBIO(MXSPEC),DEVRAT(2:7,MXSPEC),
     +    DROTOL(MXSPEC),EFFN(MXSPEC),DTSEED(MXSPEC),GITEMP(MXSPEC),
     +    GIWAT(MXSPEC),GMN(MXSPEC),GRMRAT(MXSPEC),GSR(MXSPEC),
     +    HFMAX(MXSPEC),PCLDG(MXSPEC),PGDVRT(MXSPEC),PGNTGT(MXSPEC),
     +    PLALFA(MXSPEC),PLBIO(MXSPEC),PLDIAM(MXSPEC),PLHGHT(MXSPEC),
     +    PLTMNT(MXSPEC),PLTMXT(MXSPEC),PLTOPT(MXSPEC),PMAX(MXSPEC),
     +    PMAXN(MXSPEC),PNRED(MXSPEC),PMNNIT(MXSPEC),PRNLW(MXSPEC),
     +    PTLAMX(MXSPEC),R20(MXSPEC),RATLS(MXSPEC),RATRSX(MXSPEC),
     +    RATRSN(MXSPEC),RDR(MXSPEC),RDX(MXSPEC),RQ10(MXSPEC),
     +    RTNLW(MXSPEC),SDAMAX(MXSPEC),SDDVRT(MXSPEC),SDSVRT(MXSPEC),
     +    SDTMGM(MXSPEC),SDWMAX(MXSPEC),SFREEZ(MXSPEC),SLA1(MXSPEC),
     +    SLA2(MXSPEC),SLA3(MXSPEC),SLA4(MXSPEC),STEND(2:6,MXSPEC),
     +    STNAVL(MXSPEC),STNGER(MXSPEC),STNLW(MXSPEC),TBS(MXSPEC),
     +    TOP(MXSPEC),TOT4WT(MXSPEC),WCG(MXSPEC),WCP(MXSPEC),
     +    WDLDG(MXSPEC),CNST(MXSPEC),PRB(7,7,MXSPEC),GSGDD(2:6,MXSPEC),
     +    GDDFLG(MXSPEC),VRNLZ(MXSPEC),SUFNDX(MXSPEC),IPLTYP(MXSPEC),
     +    LWM(MXSPEC),LWS(MXSPEC),NPL,INFIXN(MXSPEC)
      WRITE(IFILE,*) HSTAGE(MXAPP),HPERC(MXAPP),HRVEFF(MXAPP),YIELD(3),
     +    STUBHT(MXAPP),IHTYPE(MXAPP),IHDAY(MXAPP,3),IHARV(MXAPP),
     +    IHCL(MXAPP)
      WRITE(IFILE,*) AL,ALOH,ALSO4,CA,CASO4,H,HCO3,SO4,XMG,XMGSO4,XNA,
     +    XNASO4,XNAORG,XNH4,ORG,CO3,ALORG,ALI,ALOHI,ALSO4I,CAI,CO3I,HI,
     +    HCO3I,ORGI,SO4I,XMGI,XNAI,XNH4I,ALIS,ALOHIS,ALSOIS,CAIS,CO3IS,
     +    HIS,HCO3IS,ORGIS,SO4IS,XMGIS,XNAIS,XNASIS,XNH4IS,ALORIS
      WRITE(IFILE,*) ECA(MXNOD),ENA(MXNOD),EMG(MXNOD),ENH4(MXNOD),
     +    EAL(MXNOD),SCL(MXNOD,3),CEC(MXNOD)
      WRITE(IFILE,*) RAC(11),RRC(11),FERTIR(4),PESTIR(MXPEST),FMNRIR
      WRITE(IFILE,*) RO,SWF(MXnod),TR(MXTSTP),CI(MXTSTP),CRFD(MAXBP),
     +    CRFT(MAXBP),RFI(MAXBP),RFDD,RFD
      WRITE(IFILE,*) THSMS(MXNOD,MXCHEM),CUPRO,CUPCHM(MXCHEM),CDNCI,
     +    CDNCHM(MXCHEM),CMESO(MXNODT,MXCHEM),CMICR(MXNODT,MXCHEM),
     +    CRO(MXTSTP,MXCHEM)
      WRITE(IFILE,*) CDBET(MXNODT,MXCHEM),CFLOW(MXNODT,MXCHEM),
     +    CDFLOW(MXNODT,MXCHEM),CUMCLM(MXTSTP,MXCHEM),
     +    CUMCLR(MXTSTP,MXCHEM),CUMMF(MXTSTP),CUMRO(MXTSTP),
     +    DBET(MXNODT),DFLOW(MXNODT),FLOW(MXNODT),TDFLOW(MXNODT),
     +    TFLOW(MXNODT)
      WRITE(IFILE,*) A,ALH(MXNOD,MXCHEM),B,BDH(MAXHOR),DEG(MAXHOR),
     +    BDHR(MAXHOR),MICP(MAXHOR),NMICP
      WRITE(IFILE,*) CRUSTK,OCRUST,ICRUST,INFLPD,NHZ,NSLT,POND,RR,
     +    DHB(MAXHOR),NSL(MAXHOR),WI(MXnod),DSL(MXNODT),VWC(MXNODT),
     +    IUGFLW
      WRITE(IFILE,*) FLXMAX(MAXHOR),DB(MAXHOR),NPOR(MAXHOR)
      WRITE(IFILE,*) AMNH4(MXAPP),AMOW(MXAPP),AMBED(MXAPP),
     +    CNBED(MXAPP),AMCN(15),CNMANR(MXAPP),FCMANR(MXAPP),
     +    IWMANR(MXAPP),IMOFF(MXAPP,2),IMMETH(MXAPP),IMTYPE(MXAPP),
     +    NAPPM,IMPL(MXAPP),IMANDECOMP(MXAPP)
      WRITE(IFILE,*) FNH4IN(MXAPP),FNO3IN(MXAPP),FUREIN(MXAPP),
     +    SPLTST(MXAPP),SPLTAP(MXAPP),IFOFF(MXAPP,2),IFMETH(MXAPP),
     +    IWFERT(MXAPP),NAPPF,IBMPAP(MXAPP),IBMPMD(MXAPP),
     +    IDSPLT(MXAPP),IFPL(MXAPP)
      WRITE(IFILE,*) APP(MXAPP),PDR(MXAPP),IAPP(MXAPP),IPOFF(MXAPP,2),
     +    IWPEST(MXAPP),IPMETH(MXAPP),NAPP,IPPL(MXAPP)
      WRITE(IFILE,*) OBD(2),OFDP(2),TDEPTH(30),TILINT(30,2),
     +    TNDX(MXAPP),UDEPTH(MXAPP), PManureMix(MXAPP), IMP(MXAPP),  
     +    ITL(MXAPP), ITOFF(MXAPP,2),IWTILL(MXAPP),NUMTL, ITPL(MXAPP)
C
C     BLOCK DATA BLKOUT
C
      WRITE(IFILE,*) SCASSL,USSSL,VECSSL,UVSSL,ASSSL,AVSSL
      WRITE(IFILE,*) SC,CNTRL,SCAPLT,VECPLT,SCATAB,VECTAB,ISCA,IVEC
      WRITE(IFILE,*) SCNRIO,SCALAR,VECTOR,HZLABS

C       WRITE(IFILE,*) RFDD,JDAY,IYYY,TMAX,TMIN,RTS,TPP,W,HEIGHT,LAI,T,
C      +    SOILPP,NDXN2H,RDF,JGS,NSC,PLTSLV,RPOOL,UPNIT,EWP,SDEAD,TLPLNT,
C      +    XNIT,BASE,FIXN,IPL,IPM,JGROW,IMAGIC,ODMDN,CN,RM,RESAGE,RCN,
C      +    SDCN,CORES,COPLNT,NPEST,CHLRFL,TDAY,IQUE,INXPL,IRTYPE,OMSEA,
C      +    TLAI,IPR,SDEAD_HEIGHT,AIRR,CC,RZPAR,JBDAY,IYB,CO2R,ndxt2n,
C      +    iswpar,tmday,iweather,ssurft,IPDEPTH,TUP,DAYL


C
C
C     Close file and exit
C
C
      CLOSE(UNIT=IFILE)
      RETURN
C     ..ERROR CONDITIONS FOR OPENNING FILE
   50 PRINT*,'ERROR OPENING THE FILE: PLSTAT.DAT'
      PRINT*
      PRINT*,' CHECK TO MAKE SURE THE FILE IS IN THE CURRENT DIR.'
      STOP
     	END SUBROUTINE PLSTATWRITE

      SUBROUTINE PLSTATREAD()
C
C======================================================================
C
C       PURPOSE:  SAVE PLANT GROWTH STATE VARIABLES TO PLSTAT.DAT
C
C
C       VARIABLE DEFINITIONS:
C       VARIABLE  I/O DESCRIPTION
C       --------  --- -----------
C
C       EXTERNAL REFERENCES: None
C
C       CALLED FROM: MAIN
C
C       PROGRAMMER: BALAJI POKURI
C
C       VERSION: 0.1
C           VARIABLE LIST COPIED FROM MAPLNT(), CODE FROM STATOT()
C======================================================================
C
      USE ModuleDefs
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C     LOAD ALL VARIABLES WE CAN GET
C
C     Variables from RZmain.for
C
      PARAMETER(MXNOD=300,MXNODT=3001,MAXHOR=12,MAXSCT=11,MXCHEM=15,
     +    MXPEST=3,MXAPP=200,MXSPEC=10,MXANA=135,MHR=24)
      PARAMETER(MXTN=39,MXTNC=27,MXTP=19)
      PARAMETER(MXTSTP=5000,rhoi=9.2d2,rhol=1.0d3)
      PARAMETER(R2D=180.0D0/3.141592654D0,FCR=0.4d0)
      PARAMETER(MX2=MXNOD*2,MXC=MXNOD*MXCHEM,MXN=MXNOD*25,MXP=MXNOD*
     +    MXPEST,MAPA=MXAPP*4,MXTPP=MXPEST*MXTP)
      PARAMETER(MAXBP=50)
      PARAMETER(LX2=MAXHOR*13,LX3=MAXHOR*8,LX4=MAXHOR*5,LX5=MXAPP*2,LX6=
     +    MAXHOR*MAXSCT*3,MXPE=MXNOD*MXPEST,LX7=MXNOD*3,LST=5*MXSPEC,LDV
     +    =6*MXSPEC,MXAPP3=MXAPP*3,MXAPP20=MXAPP*20,MXAPP00=MXAPP*200)
      PARAMETER(MXHCH=MXNOD*MXCHEM,MXNCH=MXNODT*MXCHEM,MXTCH=MXTSTP*
     +    MXCHEM)
      PARAMETER(NUMSCN=7,NUMSCA=107,NUMVEC=59,IHZNUM=21,MAXSCA=41,MAXVEC
     +    =23)
      PARAMETER(TTN=-50.0D0,TTX=50.0D0,TUN=45.0D0,TUX=4700.0D0,TRN=
     +    0.0D0,TRX=45.0D0,TRHN=0.0D0,TRHX=100.0D0,UBREEZ=100.0D0)
      PARAMETER(IKEN=8+13+5+3*MAXSCT+8)
      PARAMETER(MXTNCA=9)
      PARAMETER(IFILE=432,CARBCV=1.0D0/0.58D0)
      INTEGER YESMAC

      integer :: IOS
      character(len=100) :: IOMSG, STRING

      COMMON /HEAT/ CSH(MXNOD),T(MXNOD),SOLTP1(MAXHOR,5),
     +    SOLTP2(MAXSCT,MAXHOR,3)
      COMMON /GEOMTR/XLONG,ASPECT,DELZ(MXNOD),ELEV,HORTHK(MAXHOR),SLOPE,
     +    AREA,TL(MXNOD),TLT(MXNOD),XLAT,ZN(MXNOD),NHOR,NN,NNT
      COMMON /HYDROL/ AEF,BOTFLX,DRDEP,DRSPAC,DRRAD,CLAT(MAXHOR),
     +    HEAT(MXNOD),HKBAR(MXNOD),QF(MXNOD),SOILHP(13,MAXHOR),HFC,HWP,
     +    THETA(MXNOD),thetai(mxnod),RICH_EPS,IREBOT,ITBL,IDRAIN,
     +    MAXITER_RICH,MAXCYCLE_RICH
      COMMON /IPMACF/ AGSZ(MAXHOR),FDEP(MAXHOR),MCPOR(MAXHOR),PI,
     +    PL(MAXHOR),RP(MAXHOR),SFCT,TWOPI,WP(MAXHOR),NHCMP,YESMAC,
     +    EFFWR,EFFWC,XPRESF
      COMMON /PLNTG/ PLDEN(MXAPP),PLTDAY(MXAPP,2),ROWSP(MXAPP),
     +    PLDEPTH(MXAPP),sdwtplr(mxapp),sdager(mxapp),sprlapr(mxapp),
     +    PLNTSW(MXAPP),PLNTWD(MXAPP),LAYNDX(MXAPP),NPGS,NPR(MXAPP),
     +    NGPL(MXAPP),iptype(mxapp),iemrg(mxapp)
      common /gleams/rzrainfall,rzirrigation,rzrunoff
      common /Gleams_hydsol/gleams_clay,gleams_silt,gleams_por,
     +        gleams_om1,gleams_sand,gleams_BulkDn,gleams_Dacre, 
     +        gleams_CHS,gleams_ei,gleams_exrain,thirtyRR,  
     +        IBYEAR,IEYEAR 
      common /po4log/ErosionActive,UseEnrichment
      COMMON /SOIL/ SOILPP(8,MAXHOR),pori(mxnod)
      COMMON /NDEX/ NDXN2H(MXNOD),NDXH2N(MAXHOR),NDXN2T(MXNOD),
     +    NDXT2N(MXNODT)
      COMMON /RZPEST/ HALFF(MXPEST),HALFFP(MXPEST),HALFFB(MXPEST),
     +    HALFR(MXPEST),HALFRP(MXPEST),HALFRB(MXPEST),HALFSSA(MXPEST),
     +    HALFSSV(MXPEST),HALFSSP(MXPEST),HALFSSB(MXPEST),
     +    HALFSA(MXPEST),HALFSN(MXPEST),HALFSB(MXPEST),HALFBD(MXPEST),
     +    XKH(MXPEST),XKOC(MXPEST),XMW(MXPEST),THETAR(MXPEST),
     +    TMPR(MXPEST),EA(MXPEST),EN(MXPEST),WALKERB(MXPEST),
     +    VMAX(MXPEST),DYIELD(4,MXPEST),FREUND(MXPEST),XPKA(MXPEST),
     +    XPKB(MXPEST),REFPH(MXPEST),CATKOC(MXPEST),ANKOC(MXPEST),
     +    PCOEFF(MXPEST),PPOWER(MXPEST),RCOEFF(MXPEST),RPOWER(MXPEST),
     +    XKOW(MXPEST),PBIND(MXPEST),IPCODE(4,MXPEST),IPANC(MXPEST),
     +    IPDEP(MXPEST),IPACTV(MXPEST),NPEST
      common /maxbal/IDmxH2O,IMmxH2O,IYYYmxH2O,IDmxN,IMmxN,IYYYmxN,
     +              IDmxC,IMmxC,IYYYmxC,IDmxP,IMmxP,IYYYmxP,
     +              DTMASSmxH2O,BalmxN,BalmxC,BalmxP,IWCINIT1
     +            ,ireset1
      COMMON /KNTCS/ CONCX2(MXNOD,MXPEST),EK2(MXNOD,MXPEST),
     +    RK2(MXPEST),RDIF(MXPEST),FEK2(MXPEST),IEK2(MXPEST)
      COMMON /RESID/ RM,RESAGE,CRES,HR,RCN,NADLY,NSDLY,NAREC,NSREC,WORM,
     +               SAI,HSTUBL,WSTUBL
      COMMON /PLNTDA/ CLSIZE(0:7),PSTATE(9),PWRTS,DMDNIT,TNITUP,GS,
     +    CNUP1(MXSPEC),CNUP2(MXSPEC),UPLUX
      COMMON /NUTPAR/ R14,R23,R34,R43,R45,R53,R15,R25,EFFMAX,EFFNIT,
     +    EFFDEN,DENC,RPOP(3),ADCAY,ANIT,ADENIT,AUREA,ADEATH(3),CN(9),
     +    ADCAYV(5),XKP(3),AMETH,FRN2O_NIT,FRN2O_DEN,RNO_N2O,RAINNO,
     +    O2LIM,EFFMETH,ISBUG
      COMMON /PINFO/ TSOTP0(MXPEST),TAPAP(MXPEST),TLPRS(MXPEST),
     +    TLPCN(MXPEST),TLPSL(MXPEST),TLPRO(MXPEST),TLPLC(MXPEST),
     +    TDPPLNT(MXPEST),TLPDT(MXPEST),TLPDTD(MXPEST),
     +    TLPDTL(MXPEST),TLPDMA(MXPEST)
      COMMON /SC1/ ISTAB,IVTAB,ISPLT,IVPLT
      COMMON /IPOTEV/ A0,AW,AC,ARI,XW,FSUN,COEPAN,rss,RST(MXSPEC)
     +    ,RXANGLE(MXSPEC),RTCCRIT(MXSPEC),RPLEAF0(MXSPEC),
     +      RRSTEXP(MXSPEC),RRLEAF0(MXSPEC)
      common /sumet/sumAET,sumCropET,sumPET,sumPT,sumAT,sumrain,deltheta
      common /hourweather/ hrt,hrts,hru,hrh,HRZPAR,HRTH
      common /wsi/ wsi, alaireset, heightset, iresetlai, iresetht1
C
C     BLOCK DATA BLOCK1
C
      COMMON /IRRIG/ DOIMAX(MXAPP),FDOI(MXAPP),VDOI(MXAPP,MXAPP),
     +    XKU(MXAPP,20),XMAD(MXAPP,20),RRATE(MXAPP),amxirr,
     +    totaliw,DOIMONTH(12,200),TOTALMONTH,airrdepth,amirr,
     +    RRDUR(MXAPP),IIPL(MXAPP),ISPT(MXAPP),ITOI(MXAPP),
     +    JDIRRB(MXAPP),JDIRRE(MXAPP),NAPPI,NDAIRR(MXAPP),NKU(MXAPP),
     +    NMAD(MXAPP),JDOI(MXAPP,MXAPP),JKU(MXAPP,20),JMAD(MXAPP,20),
     +    IDOI(MXAPP),id_depth,MONTHIRR
      COMMON /PLNTIN/ AHLDG(MXSPEC),ALA(MXSPEC),ALNAVL(MXSPEC),
     +    ALNGER(MXSPEC),ALNLW(MXSPEC),ALPHA(MXSPEC),ALX(MXSPEC),
     +    BETA(MXSPEC),BGSEED(MXSPEC),CAA(MXSPEC),CANK(MXSPEC),
     +    CAX(MXSPEC),CONVLA(MXSPEC),CVLBIO(MXSPEC),DEVRAT(2:7,MXSPEC),
     +    DROTOL(MXSPEC),EFFN(MXSPEC),DTSEED(MXSPEC),GITEMP(MXSPEC),
     +    GIWAT(MXSPEC),GMN(MXSPEC),GRMRAT(MXSPEC),GSR(MXSPEC),
     +    HFMAX(MXSPEC),PCLDG(MXSPEC),PGDVRT(MXSPEC),PGNTGT(MXSPEC),
     +    PLALFA(MXSPEC),PLBIO(MXSPEC),PLDIAM(MXSPEC),PLHGHT(MXSPEC),
     +    PLTMNT(MXSPEC),PLTMXT(MXSPEC),PLTOPT(MXSPEC),PMAX(MXSPEC),
     +    PMAXN(MXSPEC),PNRED(MXSPEC),PMNNIT(MXSPEC),PRNLW(MXSPEC),
     +    PTLAMX(MXSPEC),R20(MXSPEC),RATLS(MXSPEC),RATRSX(MXSPEC),
     +    RATRSN(MXSPEC),RDR(MXSPEC),RDX(MXSPEC),RQ10(MXSPEC),
     +    RTNLW(MXSPEC),SDAMAX(MXSPEC),SDDVRT(MXSPEC),SDSVRT(MXSPEC),
     +    SDTMGM(MXSPEC),SDWMAX(MXSPEC),SFREEZ(MXSPEC),SLA1(MXSPEC),
     +    SLA2(MXSPEC),SLA3(MXSPEC),SLA4(MXSPEC),STEND(2:6,MXSPEC),
     +    STNAVL(MXSPEC),STNGER(MXSPEC),STNLW(MXSPEC),TBS(MXSPEC),
     +    TOP(MXSPEC),TOT4WT(MXSPEC),WCG(MXSPEC),WCP(MXSPEC),
     +    WDLDG(MXSPEC),CNST(MXSPEC),PRB(7,7,MXSPEC),GSGDD(2:6,MXSPEC),
     +    GDDFLG(MXSPEC),VRNLZ(MXSPEC),SUFNDX(MXSPEC),IPLTYP(MXSPEC),
     +    LWM(MXSPEC),LWS(MXSPEC),NPL,INFIXN(MXSPEC)
      COMMON /HRVST/ HSTAGE(MXAPP),HPERC(MXAPP),HRVEFF(MXAPP),YIELD(3),
     +    STUBHT(MXAPP),IHTYPE(MXAPP),IHDAY(MXAPP,3),IHARV(MXAPP),
     +    IHCL(MXAPP)
      COMMON /SCCONC/ AL,ALOH,ALSO4,CA,CASO4,H,HCO3,SO4,XMG,XMGSO4,XNA,
     +    XNASO4,XNAORG,XNH4,ORG,CO3,ALORG,ALI,ALOHI,ALSO4I,CAI,CO3I,HI,
     +    HCO3I,ORGI,SO4I,XMGI,XNAI,XNH4I,ALIS,ALOHIS,ALSOIS,CAIS,CO3IS,
     +    HIS,HCO3IS,ORGIS,SO4IS,XMGIS,XNAIS,XNASIS,XNH4IS,ALORIS
      COMMON /SCHMIN/ ECA(MXNOD),ENA(MXNOD),EMG(MXNOD),ENH4(MXNOD),
     +    EAL(MXNOD),SCL(MXNOD,3),CEC(MXNOD)
      COMMON /INFILC/ RAC(11),RRC(11),FERTIR(4),PESTIR(MXPEST),FMNRIR
      COMMON /OPINF/ RO,SWF(MXnod),TR(MXTSTP),CI(MXTSTP),CRFD(MAXBP),
     +    CRFT(MAXBP),RFI(MAXBP),RFDD,RFD
      COMMON /OPCHEM/ THSMS(MXNOD,MXCHEM),CUPRO,CUPCHM(MXCHEM),CDNCI,
     +    CDNCHM(MXCHEM),CMESO(MXNODT,MXCHEM),CMICR(MXNODT,MXCHEM),
     +    CRO(MXTSTP,MXCHEM)
      COMMON /OPMACF/ CDBET(MXNODT,MXCHEM),CFLOW(MXNODT,MXCHEM),
     +    CDFLOW(MXNODT,MXCHEM),CUMCLM(MXTSTP,MXCHEM),
     +    CUMCLR(MXTSTP,MXCHEM),CUMMF(MXTSTP),CUMRO(MXTSTP),
     +    DBET(MXNODT),DFLOW(MXNODT),FLOW(MXNODT),TDFLOW(MXNODT),
     +    TFLOW(MXNODT)
      COMMON /IPCHEM/ A,ALH(MXNOD,MXCHEM),B,BDH(MAXHOR),DEG(MAXHOR),
     +    BDHR(MAXHOR),MICP(MAXHOR),NMICP
      COMMON /IPINF/ CRUSTK,OCRUST,ICRUST,INFLPD,NHZ,NSLT,POND,RR,
     +    DHB(MAXHOR),NSL(MAXHOR),WI(MXnod),DSL(MXNODT),VWC(MXNODT),
     +    IUGFLW
      COMMON /INTMCF/ FLXMAX(MAXHOR),DB(MAXHOR),NPOR(MAXHOR)
      COMMON /MMNUR/ AMNH4(MXAPP),AMOW(MXAPP),AMBED(MXAPP),
     +    CNBED(MXAPP),AMCN(15),CNMANR(MXAPP),FCMANR(MXAPP),
     +    IWMANR(MXAPP),IMOFF(MXAPP,2),IMMETH(MXAPP),IMTYPE(MXAPP),
     +    NAPPM,IMPL(MXAPP),IMANDECOMP(MXAPP)
      COMMON /MFERT/ FNH4IN(MXAPP),FNO3IN(MXAPP),FUREIN(MXAPP),
     +    SPLTST(MXAPP),SPLTAP(MXAPP),IFOFF(MXAPP,2),IFMETH(MXAPP),
     +    IWFERT(MXAPP),NAPPF,IBMPAP(MXAPP),IBMPMD(MXAPP),
     +    IDSPLT(MXAPP),IFPL(MXAPP)
      COMMON /MPEST/ APP(MXAPP),PDR(MXAPP),IAPP(MXAPP),IPOFF(MXAPP,2),
     +    IWPEST(MXAPP),IPMETH(MXAPP),NAPP,IPPL(MXAPP)
      COMMON /TILLIN/ OBD(2),OFDP(2),TDEPTH(30),TILINT(30,2),
     +    TNDX(MXAPP),UDEPTH(MXAPP), PManureMix(MXAPP), IMP(MXAPP),  
     +    ITL(MXAPP), ITOFF(MXAPP,2),IWTILL(MXAPP),NUMTL, ITPL(MXAPP)
C
C     BLOCK DATA BLKOUT
C
      COMMON /SSLIST/ SCASSL,USSSL,VECSSL,UVSSL,ASSSL,AVSSL
      COMMON /FUNIT/ SC,CNTRL,SCAPLT,VECPLT,SCATAB,VECTAB,ISCA,IVEC
      COMMON /LABLS/ SCNRIO,SCALAR,VECTOR,HZLABS

      TYPE (PLANTVARType) PLANTVAR
      TYPE (SwitchType) ISWITCH
      TYPE (ControlType) CONTROL

      INTEGER IRPL, NYR, NYRC
      DIMENSION ADIW(MXAPP),NYRP(MXPEST),ADIWMONTH(12,200),totadiw(20)
      LOGICAL SPLT1,FIRST7

      CHARACTER*1 IDETW, ISWWAT, RNMODE
      INTEGER DAS, DOY, DYNAMIC, ERRNUM, FROP, NAVWB, NAP, NOUTDW,
     + RUN, YEAR, YRDOY, REPNO
      REAL AVWTD, PESW, TLL, TOTBUNDRO, TOTIR, TSW

      INTEGER NVALP0
      INTEGER YREMRG, MDATE
      integer istage
      INTEGER STGDOY(20)

      REAL CANHT, EORATIO
      REAL KCAN, KEP, KSEVAP, KTRANS, NSTRES
      REAL PORMIN, RWUEP1, RWUMX
      REAL XLAI, XHLAI

      REAL LFWT,STMWT,XSTAGE,DTT,BIOMAS,SDWT,GRNWT,EARS
      REAL RTWT,STOVWT,STOVN,ROOTN,GRAINN,RTDEP
      REAL NFIXN,TOPWT,WTLF,PCNL,PCNST,PCNRT,PCNSD
      real trnu,swfac,grwt,cwad,tfg,wfg,cnad,stwt,nupd,gnad,rtwts
      REAL, DIMENSION(20) :: RLV, UNO3, UNH4
      LOGICAL FixCanht
      TYPE (ResidueType) HARVRES, SENESCE

      CHARACTER*6     SECTION 
      CHARACTER*30    FILEIO 
      CHARACTER*80    C80
      CHARACTER*255   FILECC

      REAL        AREALF, ASMDOT, BD(20), CANWH, CARBOT, 
     + CO2X(10), CO2Y(10), DUMMY, EP1, pp1, pp2, FSLFW, FSLFN, 
     + GRF, GROEAR, GROGRN, GROLF, GROSTM, HI, HIP, LAIDOT, LEAFNOE,
     + CumLeafSenes, CumLeafSenesY, CumLfNSenes, LFWTE, LIFAC, TAW,DTAW, 
     + NDEF3, NFAC, NPOOL, NPOOL1, NPOOL2, NSDR, NSINK, P3, PAR, 
     + PARSR, PC, PCARB, PCNGRN, PCO2, 
     + PRFTC(4), SLPF, PLAE, PLAS, PODNO, PODWT, PPLTD, PRFT, RANC, 
     + RANCE, RGFILL, RGFIL(4), RLWR, RMNC, RNLAB, RNOUT, RSGR, RSGRT, 
     + RTWO, RTWTE, RTWTO, RUE, SATFAC, SDSIZE, SDSZ, 
     + SEEDNO, SEEDRV, SEEDRVE, SFAC, SHELPC, SI1(6), SI2(6), SI3(6), 
     + SI4(6), SLAN, SLA, SLFC, SLFN, SLFT, SLFW, Stg2CLS, STMWTO, 
     + STMWTE, SUMEX, SUMRL, SWEXF, SWIDOT, SWMAX, SWMIN, 
     + TANCE, TAVGD, TCNP, TEMPM, TFAC, TI, TMNC, TNLAB, 
     + TSS(20), VANC, VSTAGE, WLIDOT, WRIDOT, WSIDOT, XANC, 
     + XLFWT, XNF, YIELDB, RZrwu(300), RZtrwup, AVG_HROOT, WTDEP, 
     + qsr(300), TRWUP1
      INTEGER     CMAT, EMAT, FOUND, I, ICOLD, ISECT, L, LINC, LNUM, 
     + LUNCRP, LUNIO, NWSD, RSTAGE, PATHL, yrplt, ISTRESS, iresetlai, 
     + iresetht1
      DOUBLE PRECISION alaireset, WSI(10),heightset


      REAL            ABSTRES         
      REAL            ACOEF           
      REAL            BARFAC 
      REAL            C1              
      REAL            CUMDTT          
      REAL            DEC             
      REAL            DGET
      REAL            DJTI
      REAL            DLV             
      REAL            DOPT                      
      REAL            DSGT
      REAL            DSGFT
      REAL            GDDE
      REAL            GPP            
      REAL            P2O            
      REAL            P9             
      REAL            PDTT
      REAL            PSKER          
      REAL            RATEIN         
      REAL            ROPT           
      REAL            S1             
      REAL            SIND           
      REAL            SNDN           
      REAL            SNUP           
      REAL            SUMDTT         
      REAL            SWCG
      REAL            SWSD           
      REAL            TBASE          
      REAL            TDSOIL         
      REAL            TEMPCN         
                                     
      REAL            TEMPCR         
      REAL            TEMPCX         
      REAL            TH             
      REAL            TLNO           
      REAL            TMSOIL         
      REAL            TNSOIL         
      REAL            TOPT           
      REAL            XNTI           
      REAL            XS             
      REAL            tdsoil1,tnsoil1,tmsoil1         

      INTEGER         L0             
      INTEGER         NDAS           
      INTEGER ISDATE          
      INTEGER IPATH
      INTEGER LUNECO

      CHARACTER*6 ECOTYP
      CHARACTER*255 C255
      CHARACTER*255    FILEGC
      CHARACTER*16  ECONAM

C
C
C    Now Open the dat file to write
C
C
      PRINT *, "ENTER PLSTATREAD, now trying to load the file"
      OPEN(IFILE,FILE="PLSTAT.DAT",ACTION="READ",IOSTAT=IOS,IOMSG=IOMSG)
      IF(IOS.NE.0) then
          PRINT *, "File not found, skipping initialization"
          RETURN  ! file not found, start fresh
      ENDIF
      READ(IFILE, *, IOSTAT=IOS, IOMSG=IOMSG) STRING
      IF(IOS.NE.0)  then
          PRINT *, "File empty, skipping initialization"
          RETURN  ! file empty, nothing to read
      ENDIF 
      BACKSPACE(IFILE)
      PRINT *, "PLSTAT not empty, trying to read"


      READ(IFILE, *) ABSTRES, ACOEF, BARFAC, C1, 
     + DEC, DGET, DJTI, DLV, DOPT, DSGT, DSGFT, DUMMY, 
     + GDDE, P2O, P9, PDTT, PSKER, RATEIN, 
     + ROPT, S1, SIND, SNDN, SNUP, SWCG, SWSD, TBASE, 
     + TDSOIL, TEMPCN, TEMPCR, TEMPCX, TH, TMSOIL, TNSOIL, TOPT, 
     + XS, tdsoil1, tnsoil1, tmsoil1, FOUND, L, 
     + L0, LINC, LNUM, LUNIO, NDAS, PATHL, 
     + LUNECO, ISECT, LUNCRP
      READ(IFILE, '(A6,A6,A255,A255,A16,A80)') SECTION, ECOTYP, C255,
     +  FILEGC, ECONAM, C80
      CALL GETPUT_MZ_PHENOL('GET', ABSTRES, ACOEF, BARFAC, C1, 
     + DEC, DGET, DJTI, DLV, DOPT, DSGT, DSGFT, DUMMY, 
     + GDDE, P2O, P9, PDTT, PSKER, RATEIN, 
     + ROPT, S1, SIND, SNDN, SNUP, SWCG, SWSD, TBASE, 
     + TDSOIL, TEMPCN, TEMPCR, TEMPCX, TH, TMSOIL, TNSOIL, TOPT, 
     + XS, tdsoil1, tnsoil1, tmsoil1, FOUND, L, 
     + L0, LINC, LNUM, LUNIO, NDAS, PATHL, 
     + LUNECO, ISECT, LUNCRP, SECTION, ECOTYP, C255, FILEGC, 
     + ECONAM, C80)

      READ(IFILE, *) STRING
      PRINT *, STRING
      READ(IFILE,'(A6,A80,A255)') SECTION, C80, FILECC
      READ(IFILE,*) CARBOT, CO2X, CO2Y, 
     +  DUMMY, EP1, pp1, pp2, FSLFW, FSLFN, GRF, GROEAR, GROGRN, 
     +  GROLF, GROSTM, LAIDOT, LEAFNOE, CumLeafSenes, 
     +  CumLeafSenesY, CumLfNSenes, LFWTE, LIFAC, TAW, DTAW, NDEF3, 
     +  NFAC, NPOOL, NPOOL1, NPOOL2, NSDR, NSINK, PAR, 
     +  PARSR, PC, PCARB, PCO2, 
     +  PRFTC, SLPF, PLAE, PLAS, PRFT, RANC, 
     +  RANCE, RGFILL, RGFIL, RMNC, RNLAB, RNOUT, RSGR, RSGRT, RTWTE,
     +  SEEDRV, SEEDRVE, SFAC, SI1, SI2, SI3, SI4, 
     +  SLAN, SLFC, SLFN, SLFT, SLFW, Stg2CLS, STMWTE, 
     +  SUMEX, SUMRL, SWEXF, SWMAX, SWMIN, TANCE, 
     +  TAVGD, TCNP, TEMPM, TFAC, TI, TMNC, TNLAB, TSS, 
     +  VANC, XANC, XLFWT, 
     +  XNF, YIELDB, RZrwu, RZtrwup, AVG_HROOT, WTDEP, qsr, TRWUP1, 
     +  CMAT, EMAT, FOUND, I, ICOLD, ISECT, L, LINC, LNUM, LUNCRP, 
     +  LUNIO, NWSD, PATHL, ISTRESS, iresetlai,iresetht1,
     +  alaireset, WSI, heightset

C       READ(IFILE,*) CMAT, EMAT, FOUND, I, ICOLD, ISECT, L, LINC, LNUM, 
C      + LUNCRP, LUNIO, NWSD, RSTAGE, PATHL, yrplt, ISTRESS, iresetlai, 
C      + iresetht1
C       READ(IFILE,*) alaireset, WSI,heightset

      CALL GETPUT_MZ_GROSUB('PUT', SECTION, C80, FILECC, 
     +  CARBOT, CO2X, CO2Y, 
     +  DUMMY, EP1, pp1, pp2, FSLFW, FSLFN, GRF, GROEAR, GROGRN, 
     +  GROLF, GROSTM, LAIDOT, LEAFNOE, CumLeafSenes, 
     +  CumLeafSenesY, CumLfNSenes, LFWTE, LIFAC, TAW, DTAW, NDEF3, 
     +  NFAC, NPOOL, NPOOL1, NPOOL2, NSDR, NSINK, PAR, 
     +  PARSR, PC, PCARB, PCO2, 
     +  PRFTC, SLPF, PLAE, PLAS, PRFT, RANC, 
     +  RANCE, RGFILL, RGFIL, RMNC, RNLAB, RNOUT, RSGR, RSGRT, RTWTE,
     +  SEEDRV, SEEDRVE, SFAC, SI1, SI2, SI3, SI4, 
     +  SLAN, SLFC, SLFN, SLFT, SLFW, Stg2CLS, STMWTE, 
     +  SUMEX, SUMRL, SWEXF, SWMAX, SWMIN, TANCE, 
     +  TAVGD, TCNP, TEMPM, TFAC, TI, TMNC, TNLAB, TSS, 
     +  VANC, XANC, XLFWT, 
     +  XNF, YIELDB, RZrwu, RZtrwup, AVG_HROOT, WTDEP, qsr, TRWUP1, 
     +  CMAT, EMAT, FOUND, I, ICOLD, ISECT, L, LINC, LNUM, LUNCRP, 
     +  LUNIO, NWSD, PATHL, ISTRESS, iresetlai,iresetht1,
     +  alaireset, WSI, heightset)




      READ(IFILE,*) AGEFAC, NDEF3, NFAC, NSTRES
      CALL GETPUT_MZ_NFACTO('GET', AGEFAC, NDEF3, NFAC, NSTRES)

      READ(IFILE, *) NVALP0, YREMRG, MDATE, istage
      READ(IFILE, *) STGDOY(20)

      READ(IFILE, *) CANHT, EORATIO, KCAN, KEP, KSEVAP, KTRANS, NSTRES, 
     + PORMIN, RWUEP1, RWUMX, XLAI, XHLAI, LFWT, STMWT, XSTAGE, DTT, 
     + BIOMAS, SDWT, GRNWT, EARS, RTWT, STOVWT, STOVN, ROOTN, GRAINN, 
     + RTDEP, NFIXN, TOPWT, WTLF, PCNL, PCNST, PCNRT, PCNSD
      READ(IFILE, *) trnu, swfac, grwt, cwad, tfg, wfg, cnad, stwt, 
     + nupd, gnad, rtwts
      READ(IFILE, *) RLV, UNO3, UNH4
      READ(IFILE, *) FixCanht

      READ(IFILE, *) HARVRES
      READ(IFILE, *) SENESCE
      CALL Alt_Plant_Memory('PUT', NVALP0, YREMRG, MDATE, STGDOY, 
     +  CANHT, EORATIO, KCAN, KEP, KSEVAP, KTRANS, NSTRES, PORMIN, 
     +  RWUEP1, RWUMX, XLAI, XHLAI, RLV, UNO3, UNH4, LFWT, STMWT, 
     +  XSTAGE, DTT, BIOMAS, SDWT, GRNWT, EARS, RTWT, STOVWT, STOVN, 
     +  ROOTN, GRAINN, RTDEP, NFIXN, TOPWT, WTLF, PCNL, PCNST, PCNRT, 
     +  PCNSD, trnu, swfac, grwt, cwad, tfg, wfg, cnad, stwt, nupd, 
     +  gnad, rtwts, istage, FixCanht, HARVRES, SENESCE)      


      READ(IFILE,'(3A1)') IDETW, ISWWAT, RNMODE
      READ(IFILE,'(12I)') DAS,DOY, DYNAMIC, ERRNUM, FROP, NAVWB, NAP,
     + NOUTDW, RUN, YEAR, YRDOY, REPNO
      READ(IFILE,'(6e)') AVWTD, PESW, TLL, TOTBUNDRO, TOTIR, TSW
C       READ(IFILE,*) IDETW, ISWWAT, RNMODE
C       PRINT *, "LOADED CHARS"
C       READ(IFILE,*) DAS, DOY, DYNAMIC, ERRNUM, FROP, NAVWB, NAP, NOUTDW,
C      + RUN, YEAR, YRDOY, REPNO
C       PRINT *, "LOADED INTS"
C       READ(IFILE,*) AVWTD, PESW, TLL, TOTBUNDRO, TOTIR, TSW
C       PRINT *, "LOADED REALS"
C       CALL OPWBAL_Memory('PUT', IDETW, ISWWAT, RNMODE, DAS, DOY, 
C      +  DYNAMIC, ERRNUM, FROP, NAVWB, NAP, NOUTDW, RUN, YEAR, 
C      +  YRDOY, REPNO, AVWTD, PESW, TLL, TOTBUNDRO, TOTIR, TSW)
C       PRINT *, "OPWBAL success"
      READ(IFILE,*) nreps,FIRST11,first15,PCN,TTPLNT,TMPLNT,TXPLNT,IJ
      CALL MAPLNT_Memory('PUT',nreps,FIRST11,first15,PCN,TTPLNT,
     +  TMPLNT,TXPLNT,IJ)

      READ(IFILE, *) oldhgt,PLHGHT,PLALFA
      CALL DSSATDRV_Memory('PUT', oldhgt,PLHGHT,PLALFA)
      
      READ(IFILE,*) LID,LIM,LIYYY,JSEQDAY,CURSTATE
      CALL DAYJACK_Memory('PUT',LID,LIM,LIYYY,JSEQDAY,CURSTATE)

      READ(IFILE, *) ADIW,JSPLT,SPLT1,FIRST7,NYR,IRPL,NYRC,
     +  NYRP,ADIWMONTH,totadiw,curradiw
      CALL MAQUE_Memory('PUT',ADIW,JSPLT,SPLT1,FIRST7,NYR,IRPL,NYRC,
     +  NYRP,ADIWMONTH,totadiw,curradiw)

      ! explicitly specify sequence for custom datatype 
C       READ(IFILE,*) PLANTVAR%VARNO,PLANTVAR%ECONO 
C       READ(IFILE,*) PLANTVAR%VRNAME 
C       READ(IFILE,*) PLANTVAR%PLME 
      READ(IFILE,*) PLANTVAR%HDATE 
      READ(IFILE,*) PLANTVAR%HPC, PLANTVAR%HBPC, PLANTVAR%HRPC                   
      READ(IFILE,*) PLANTVAR%PLTPOP,PLANTVAR%ROWSPC,PLANTVAR%SDEPTH,
     + PLANTVAR%AZIR,PLANTVAR%SDWTPL,PLANTVAR%SDAGE,PLANTVAR%SPRLAP 
      READ(IFILE,*) PLANTVAR%P1,PLANTVAR%P1V,PLANTVAR%P1D,PLANTVAR%P2,
     + PLANTVAR%P2O,PLANTVAR%P2R,PLANTVAR%P3,PLANTVAR%P4,PLANTVAR%P5,
     + PLANTVAR%G1,PLANTVAR%G2,PLANTVAR%G3,PLANTVAR%G4 
      READ(IFILE,*) PLANTVAR%PHINT,PLANTVAR%PD,PLANTVAR%TC,PLANTVAR%O1,
     + PLANTVAR%GPROT,PLANTVAR%LT50H 
      READ(IFILE,*) PLANTVAR%CSDVAR,PLANTVAR%PHTHRS,PLANTVAR%SDPDVR,
     + PLANTVAR%SLAVAR,PLANTVAR%LFMAX,PLANTVAR%XFRUIT,PLANTVAR%WTPSD 
      READ(IFILE,*) PLANTVAR%SFDUR,PLANTVAR%PODUR,PLANTVAR%PPSEN,
     + PLANTVAR%PH2T5,PLANTVAR%SIZELF 
      READ(IFILE,*) PLANTVAR%RATPOT,PLANTVAR%PI1,PLANTVAR%PI2,
     + PLANTVAR%DTTPI 
      READ(IFILE,*) PLANTVAR%PCINT,PLANTVAR%PCGRD 
      READ(IFILE,*) PLANTVAR%GCOEFF 
      READ(IFILE,*) PLANTVAR%SCPB,PLANTVAR%RESPC,PLANTVAR%SQCON,
     + PLANTVAR%FCUT,PLANTVAR%FLAI,PLANTVAR%DDISQ 
      READ(IFILE,*) PLANTVAR%EFINOC,PLANTVAR% EFNFIX 
      READ(IFILE,*) PLANTVAR%RESAMT,PLANTVAR%ATEMP
      CALL GETPUT_PLANTVAR('PUT',PLANTVAR)

      PRINT *, "ABOUT TO LOAD CONTROL"
      READ(IFILE,'(A1,A1,A2,A12)') CONTROL%MESIC, CONTROL%RNMODE,
     + CONTROL%CROP, CONTROL%MODEL
      PRINT *, "LOADING CONTROL"
      READ(IFILE,*) CONTROL%DAS, CONTROL%DYNAMIC, CONTROL%FROP, 
     + CONTROL%MULTI, CONTROL%REPNO, CONTROL%RUN
      PRINT *, "LOADING CONTROL"
      READ(IFILE,*) CONTROL%TRTNO, CONTROL%YRDOY, CONTROL%YRSIM, 
     + CONTROL%NYRS, CONTROL%YRDIF, CONTROL%ROTNUM
C       PRINT *, "LOADING CONTROL"
C       READ(IFILE,*) CONTROL%FILEC, CONTROL%FILEE, CONTROL%FILES,
C      + CONTROL%FILEA,CONTROL%FILET
C       PRINT *, "LOADING CONTROL"
C       READ(IFILE,*) CONTROL%PATHCR,CONTROL%PATHER,CONTROL%PATHSR
      PRINT *, "LOADING CONTROL"
      READ(IFILE,*) CONTROL%EXPER
      PRINT *, "LOADING CONTROL"
      READ(IFILE,*) CONTROL%ENAME
      PRINT *, "LOADING CONTROL"
      READ(IFILE,*) CONTROL%TITLET
      PRINT *, "LOADING CONTROL"
      READ(IFILE,*) CONTROL%YRPLT, CONTROL%IEMRG
      PRINT *, "SAVING CONTROL"
      CALL GETPUT_CONTROL('PUT', CONTROL)
      PRINT *, "ISWITCH: ", ISWITCH
      READ(IFILE,'(21A1,I)') ISWITCH%IDETC,ISWITCH%IDETD,ISWITCH%IDETG, 
     + ISWITCH%IDETL, ISWITCH%IDETN, ISWITCH%IDETO, ISWITCH%IDETR, 
     + ISWITCH%IDETS, ISWITCH%IDETW, ISWITCH%IHARI, ISWITCH%IPLTI, 
     + ISWITCH%IIRRI, ISWITCH%ISWDIS, ISWITCH%ISWNIT, 
     + ISWITCH%ISWSYM, ISWITCH%ISWWAT,
     + ISWITCH%MEEVP, ISWITCH%MEPHO, ISWITCH%MESOM,
     + ISWITCH%IFERI, ISWITCH%IRESI,ISWITCH%NSWI
      PRINT *, "ISWITCH: ", ISWITCH
      CALL GETPUT_ISWITCH('PUT', ISWITCH)
C
C
C    Write each set of common variables in sequence
C
C 
      READ(IFILE,*) CSH(MXNOD),T(MXNOD),SOLTP1(MAXHOR,5),
     +    SOLTP2(MAXSCT,MAXHOR,3) 
      READ(IFILE,*)XLONG,ASPECT,DELZ(MXNOD),ELEV,HORTHK(MAXHOR),SLOPE,
     +    AREA,TL(MXNOD),TLT(MXNOD),XLAT,ZN(MXNOD),NHOR,NN,NNT 
      READ(IFILE,*) AEF,BOTFLX,DRDEP,DRSPAC,DRRAD,CLAT(MAXHOR),
     +    HEAT(MXNOD),HKBAR(MXNOD),QF(MXNOD),SOILHP(13,MAXHOR),HFC,HWP,
     +    THETA(MXNOD),thetai(mxnod),RICH_EPS,IREBOT,ITBL,IDRAIN,
     +    MAXITER_RICH,MAXCYCLE_RICH 
      READ(IFILE,*) AGSZ(MAXHOR),FDEP(MAXHOR),MCPOR(MAXHOR),PI,
     +    PL(MAXHOR),RP(MAXHOR),SFCT,TWOPI,WP(MAXHOR),NHCMP,YESMAC,
     +    EFFWR,EFFWC,XPRESF 
      READ(IFILE,*) PLDEN(MXAPP),PLTDAY(MXAPP,2),ROWSP(MXAPP),
     +    PLDEPTH(MXAPP),sdwtplr(mxapp),sdager(mxapp),sprlapr(mxapp),
     +    PLNTSW(MXAPP),PLNTWD(MXAPP),LAYNDX(MXAPP),NPGS,NPR(MXAPP),
     +    NGPL(MXAPP),iptype(mxapp),iemrg(mxapp) 
      READ(IFILE,*)rzrainfall,rzirrigation,rzrunoff 
      READ(IFILE,*)gleams_clay,gleams_silt,gleams_por,
     +        gleams_om1,gleams_sand,gleams_BulkDn,gleams_Dacre, 
     +        gleams_CHS,gleams_ei,gleams_exrain,thirtyRR,  
     +        IBYEAR,IEYEAR  
      READ(IFILE,*)ErosionActive,UseEnrichment 
      READ(IFILE,*) SOILPP(8,MAXHOR),pori(mxnod) 
      READ(IFILE,*) NDXN2H(MXNOD),NDXH2N(MAXHOR),NDXN2T(MXNOD),
     +    NDXT2N(MXNODT) 
      READ(IFILE,*) HALFF(MXPEST),HALFFP(MXPEST),HALFFB(MXPEST),
     +    HALFR(MXPEST),HALFRP(MXPEST),HALFRB(MXPEST),HALFSSA(MXPEST),
     +    HALFSSV(MXPEST),HALFSSP(MXPEST),HALFSSB(MXPEST),
     +    HALFSA(MXPEST),HALFSN(MXPEST),HALFSB(MXPEST),HALFBD(MXPEST),
     +    XKH(MXPEST),XKOC(MXPEST),XMW(MXPEST),THETAR(MXPEST),
     +    TMPR(MXPEST),EA(MXPEST),EN(MXPEST),WALKERB(MXPEST),
     +    VMAX(MXPEST),DYIELD(4,MXPEST),FREUND(MXPEST),XPKA(MXPEST),
     +    XPKB(MXPEST),REFPH(MXPEST),CATKOC(MXPEST),ANKOC(MXPEST),
     +    PCOEFF(MXPEST),PPOWER(MXPEST),RCOEFF(MXPEST),RPOWER(MXPEST),
     +    XKOW(MXPEST),PBIND(MXPEST),IPCODE(4,MXPEST),IPANC(MXPEST),
     +    IPDEP(MXPEST),IPACTV(MXPEST),NPEST 
      READ(IFILE,*)IDmxH2O,IMmxH2O,IYYYmxH2O,IDmxN,IMmxN,IYYYmxN,
     +              IDmxC,IMmxC,IYYYmxC,IDmxP,IMmxP,IYYYmxP,
     +              DTMASSmxH2O,BalmxN,BalmxC,BalmxP,IWCINIT1
     +            ,ireset1 
      READ(IFILE,*) CONCX2(MXNOD,MXPEST),EK2(MXNOD,MXPEST),
     +    RK2(MXPEST),RDIF(MXPEST),FEK2(MXPEST),IEK2(MXPEST) 
      READ(IFILE,*) RM,RESAGE,CRES,HR,RCN,NADLY,NSDLY,NAREC,NSREC,WORM,
     +               SAI,HSTUBL,WSTUBL 
      READ(IFILE,*) CLSIZE(0:7),PSTATE(9),PWRTS,DMDNIT,TNITUP,GS,
     +    CNUP1(MXSPEC),CNUP2(MXSPEC),UPLUX 
      READ(IFILE,*) R14,R23,R34,R43,R45,R53,R15,R25,EFFMAX,EFFNIT,
     +    EFFDEN,DENC,RPOP(3),ADCAY,ANIT,ADENIT,AUREA,ADEATH(3),CN(9),
     +    ADCAYV(5),XKP(3),AMETH,FRN2O_NIT,FRN2O_DEN,RNO_N2O,RAINNO,
     +    O2LIM,EFFMETH,ISBUG 
      READ(IFILE,*) TSOTP0(MXPEST),TAPAP(MXPEST),TLPRS(MXPEST),
     +    TLPCN(MXPEST),TLPSL(MXPEST),TLPRO(MXPEST),TLPLC(MXPEST),
     +    TDPPLNT(MXPEST),TLPDT(MXPEST),TLPDTD(MXPEST),
     +    TLPDTL(MXPEST),TLPDMA(MXPEST) 
      READ(IFILE,*) ISTAB,IVTAB,ISPLT,IVPLT 
      READ(IFILE,*) A0,AW,AC,ARI,XW,FSUN,COEPAN,rss,RST(MXSPEC)
     +    ,RXANGLE(MXSPEC),RTCCRIT(MXSPEC),RPLEAF0(MXSPEC),
     +      RRSTEXP(MXSPEC),RRLEAF0(MXSPEC) 
      READ(IFILE,*)sumAET,sumCropET,sumPET,sumPT,sumAT,sumrain,deltheta 
      READ(IFILE,*) hrt,hrts,hru,hrh,HRZPAR,HRTH 
      READ(IFILE,*) wsi, alaireset, heightset, iresetlai, iresetht1
C
C     BLOCK DATA BLOCK1
C 
      READ(IFILE,*) DOIMAX(MXAPP),FDOI(MXAPP),VDOI(MXAPP,MXAPP),
     +    XKU(MXAPP,20),XMAD(MXAPP,20),RRATE(MXAPP),amxirr,
     +    totaliw,DOIMONTH(12,200),TOTALMONTH,airrdepth,amirr,
     +    RRDUR(MXAPP),IIPL(MXAPP),ISPT(MXAPP),ITOI(MXAPP),
     +    JDIRRB(MXAPP),JDIRRE(MXAPP),NAPPI,NDAIRR(MXAPP),NKU(MXAPP),
     +    NMAD(MXAPP),JDOI(MXAPP,MXAPP),JKU(MXAPP,20),JMAD(MXAPP,20),
     +    IDOI(MXAPP),id_depth,MONTHIRR 
      READ(IFILE,*) AHLDG(MXSPEC),ALA(MXSPEC),ALNAVL(MXSPEC),
     +    ALNGER(MXSPEC),ALNLW(MXSPEC),ALPHA(MXSPEC),ALX(MXSPEC),
     +    BETA(MXSPEC),BGSEED(MXSPEC),CAA(MXSPEC),CANK(MXSPEC),
     +    CAX(MXSPEC),CONVLA(MXSPEC),CVLBIO(MXSPEC),DEVRAT(2:7,MXSPEC),
     +    DROTOL(MXSPEC),EFFN(MXSPEC),DTSEED(MXSPEC),GITEMP(MXSPEC),
     +    GIWAT(MXSPEC),GMN(MXSPEC),GRMRAT(MXSPEC),GSR(MXSPEC),
     +    HFMAX(MXSPEC),PCLDG(MXSPEC),PGDVRT(MXSPEC),PGNTGT(MXSPEC),
     +    PLALFA(MXSPEC),PLBIO(MXSPEC),PLDIAM(MXSPEC),PLHGHT(MXSPEC),
     +    PLTMNT(MXSPEC),PLTMXT(MXSPEC),PLTOPT(MXSPEC),PMAX(MXSPEC),
     +    PMAXN(MXSPEC),PNRED(MXSPEC),PMNNIT(MXSPEC),PRNLW(MXSPEC),
     +    PTLAMX(MXSPEC),R20(MXSPEC),RATLS(MXSPEC),RATRSX(MXSPEC),
     +    RATRSN(MXSPEC),RDR(MXSPEC),RDX(MXSPEC),RQ10(MXSPEC),
     +    RTNLW(MXSPEC),SDAMAX(MXSPEC),SDDVRT(MXSPEC),SDSVRT(MXSPEC),
     +    SDTMGM(MXSPEC),SDWMAX(MXSPEC),SFREEZ(MXSPEC),SLA1(MXSPEC),
     +    SLA2(MXSPEC),SLA3(MXSPEC),SLA4(MXSPEC),STEND(2:6,MXSPEC),
     +    STNAVL(MXSPEC),STNGER(MXSPEC),STNLW(MXSPEC),TBS(MXSPEC),
     +    TOP(MXSPEC),TOT4WT(MXSPEC),WCG(MXSPEC),WCP(MXSPEC),
     +    WDLDG(MXSPEC),CNST(MXSPEC),PRB(7,7,MXSPEC),GSGDD(2:6,MXSPEC),
     +    GDDFLG(MXSPEC),VRNLZ(MXSPEC),SUFNDX(MXSPEC),IPLTYP(MXSPEC),
     +    LWM(MXSPEC),LWS(MXSPEC),NPL,INFIXN(MXSPEC) 
      READ(IFILE,*) HSTAGE(MXAPP),HPERC(MXAPP),HRVEFF(MXAPP),YIELD(3),
     +    STUBHT(MXAPP),IHTYPE(MXAPP),IHDAY(MXAPP,3),IHARV(MXAPP),
     +    IHCL(MXAPP) 
      READ(IFILE,*) AL,ALOH,ALSO4,CA,CASO4,H,HCO3,SO4,XMG,XMGSO4,XNA,
     +    XNASO4,XNAORG,XNH4,ORG,CO3,ALORG,ALI,ALOHI,ALSO4I,CAI,CO3I,HI,
     +    HCO3I,ORGI,SO4I,XMGI,XNAI,XNH4I,ALIS,ALOHIS,ALSOIS,CAIS,CO3IS,
     +    HIS,HCO3IS,ORGIS,SO4IS,XMGIS,XNAIS,XNASIS,XNH4IS,ALORIS 
      READ(IFILE,*) ECA(MXNOD),ENA(MXNOD),EMG(MXNOD),ENH4(MXNOD),
     +    EAL(MXNOD),SCL(MXNOD,3),CEC(MXNOD) 
      READ(IFILE,*) RAC(11),RRC(11),FERTIR(4),PESTIR(MXPEST),FMNRIR 
      READ(IFILE,*) RO,SWF(MXnod),TR(MXTSTP),CI(MXTSTP),CRFD(MAXBP),
     +    CRFT(MAXBP),RFI(MAXBP),RFDD,RFD 
      READ(IFILE,*) THSMS(MXNOD,MXCHEM),CUPRO,CUPCHM(MXCHEM),CDNCI,
     +    CDNCHM(MXCHEM),CMESO(MXNODT,MXCHEM),CMICR(MXNODT,MXCHEM),
     +    CRO(MXTSTP,MXCHEM) 
      READ(IFILE,*) CDBET(MXNODT,MXCHEM),CFLOW(MXNODT,MXCHEM),
     +    CDFLOW(MXNODT,MXCHEM),CUMCLM(MXTSTP,MXCHEM),
     +    CUMCLR(MXTSTP,MXCHEM),CUMMF(MXTSTP),CUMRO(MXTSTP),
     +    DBET(MXNODT),DFLOW(MXNODT),FLOW(MXNODT),TDFLOW(MXNODT),
     +    TFLOW(MXNODT) 
      READ(IFILE,*) A,ALH(MXNOD,MXCHEM),B,BDH(MAXHOR),DEG(MAXHOR),
     +    BDHR(MAXHOR),MICP(MAXHOR),NMICP 
      READ(IFILE,*) CRUSTK,OCRUST,ICRUST,INFLPD,NHZ,NSLT,POND,RR,
     +    DHB(MAXHOR),NSL(MAXHOR),WI(MXnod),DSL(MXNODT),VWC(MXNODT),
     +    IUGFLW 
      READ(IFILE,*) FLXMAX(MAXHOR),DB(MAXHOR),NPOR(MAXHOR) 
      READ(IFILE,*) AMNH4(MXAPP),AMOW(MXAPP),AMBED(MXAPP),
     +    CNBED(MXAPP),AMCN(15),CNMANR(MXAPP),FCMANR(MXAPP),
     +    IWMANR(MXAPP),IMOFF(MXAPP,2),IMMETH(MXAPP),IMTYPE(MXAPP),
     +    NAPPM,IMPL(MXAPP),IMANDECOMP(MXAPP) 
      READ(IFILE,*) FNH4IN(MXAPP),FNO3IN(MXAPP),FUREIN(MXAPP),
     +    SPLTST(MXAPP),SPLTAP(MXAPP),IFOFF(MXAPP,2),IFMETH(MXAPP),
     +    IWFERT(MXAPP),NAPPF,IBMPAP(MXAPP),IBMPMD(MXAPP),
     +    IDSPLT(MXAPP),IFPL(MXAPP) 
      READ(IFILE,*) APP(MXAPP),PDR(MXAPP),IAPP(MXAPP),IPOFF(MXAPP,2),
     +    IWPEST(MXAPP),IPMETH(MXAPP),NAPP,IPPL(MXAPP) 
      READ(IFILE,*) OBD(2),OFDP(2),TDEPTH(30),TILINT(30,2),
     +    TNDX(MXAPP),UDEPTH(MXAPP), PManureMix(MXAPP), IMP(MXAPP),  
     +    ITL(MXAPP), ITOFF(MXAPP,2),IWTILL(MXAPP),NUMTL, ITPL(MXAPP)
C
C     BLOCK DATA BLKOUT
C 
      READ(IFILE,*) SCASSL,USSSL,VECSSL,UVSSL,ASSSL,AVSSL 
      READ(IFILE,*) SC,CNTRL,SCAPLT,VECPLT,SCATAB,VECTAB,ISCA,IVEC 
      READ(IFILE,*) SCNRIO,SCALAR,VECTOR,HZLABS

C       READ(IFILE,*) RFDD,JDAY,IYYY,TMAX,TMIN,RTS,TPP,W,HEIGHT,LAI,T,
C      +    SOILPP,NDXN2H,RDF,JGS,NSC,PLTSLV,RPOOL,UPNIT,EWP,SDEAD,TLPLNT,
C      +    XNIT,BASE,FIXN,IPL,IPM,JGROW,IMAGIC,ODMDN,CN,RM,RESAGE,RCN,
C      +    SDCN,CORES,COPLNT,NPEST,CHLRFL,TDAY,IQUE,INXPL,IRTYPE,OMSEA,
C      +    TLAI,IPR,SDEAD_HEIGHT,AIRR,CC,RZPAR,JBDAY,IYB,CO2R,ndxt2n,
C      +    iswpar,tmday,iweather,ssurft,IPDEPTH,TUP,DAYL


C
C
C     Close file and exit
C
C
      CLOSE(UNIT=IFILE)
      PRINT *, "All variables loaded ,exiting PLSTATREAD"
      RETURN
C     ..ERROR CONDITIONS FOR OPENNING FILE
   50 PRINT*,'ERROR OPENING THE FILE: INTERMEDIATE.DAT'
      PRINT*
      PRINT*,' CHECK TO MAKE SURE THE FILE IS IN THE CURRENT DIR.'
      STOP
      END SUBROUTINE PLSTATREAD
