! RZinterrupt.for Balaji Pokuri, Jan 2022
C Utility code to save plant state and resume on next run
C 
	     SUBROUTINE PLSTATREAD(RFDD,JDAY,IYYY,TMAX,TMIN,RTS,TPP,W,HEIGHT,LAI,T,
     +    SOILPP,NDXN2H,RDF,JGS,NSC,PLTSLV,RPOOL,UPNIT,EWP,SDEAD,TLPLNT,
     +    XNIT,BASE,FIXN,IPL,IPM,JGROW,IMAGIC,ODMDN,CN,RM,RESAGE,RCN,
     +    SDCN,CORES,COPLNT,NPEST,CHLRFL,TDAY,IQUE,INXPL,IRTYPE,OMSEA,
     +    TLAI,IPR,SDEAD_HEIGHT,AIRR,CC,RZPAR,JBDAY,IYB,CO2R,ndxt2n,
     +    iswpar,tmday,iweather,ssurft,IPDEPTH,TUP,DAYL)
C
C======================================================================
C
C       PURPOSE:  SAVE PLANT GROWTH STATE VARIABLES TO PLSTAT.DAT
C
C
C       VARIABLE DEFINITIONS:
C       VARIABLE  I/O DESCRIPTION
C       --------  --- -----------
C
C       EXTERNAL REFERENCES: None
C
C       CALLED FROM: MAIN
C
C       PROGRAMMER: BALAJI POKURI
C
C       VERSION: 0.1
C		VARIABLE LIST COPIED FROM MAPLNT(), CODE FROM STATOT()
C======================================================================
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
      PARAMETER(MXNOD=300,MAXHOR=12,MXAPP=200,MXPEST=3,MXSPEC=10,
     +    MXANA=135,mxnodt=3001,mhr=24)
C-GH    Liwang Ma
      PARAMETER (PI=3.141592654D0, R2D=180.0D0/PI, MXCHEM=15)
      COMMON /IPOTEV/ A0,AW,AC,ARI,XW,FSUN,COEPAN,rss,RST(MXSPEC)
     +    ,RXANGLE(MXSPEC),RTCCRIT(MXSPEC),RPLEAF0(MXSPEC),
     +      RRSTEXP(MXSPEC),RRLEAF0(MXSPEC)
C-GH     Liwang Ma
C
      COMMON /GEOMTR/XLONG,ASPECT,DELZ(MXNOD),ELEV,HORTHK(MAXHOR),SLOPE,
     +    AREA,TL(MXNOD),TLT(MXNOD),XLAT,ZN(MXNOD),NHOR,NN,NNT
C
      COMMON /HYDROL/ AEF,BOTFLX,DRDEP,DRSPAC,DRRAD,CLAT(MAXHOR),
     +    H(MXNOD),HKBAR(MXNOD),QF(MXNOD),SOILHP(13,MAXHOR),HFC,HWP,
     +    THETA(MXNOD),thetai(mxnod),RICH_EPS,IREBOT,ITBL,IDRAIN,
     +    MAXITER_RICH,MAXCYCLE_RICH
C
      COMMON /NINFO/ TSOTN0,TSOTN,TOTA,TOTL,TAMIN,TANIT,TADRT(2),
     +    TARAIN(2),TAIRR(3),TAFERT(3),TARES(3),TLIMM,TLDEN,TLVOL,
     +    TLRO(3),TLSEP(3),TLDRN(3),TLLAT(3),TAMANR,TMANH4,tamanr_bal
     +    ,TLN2O,TLNXO,TLNITN2O,TLNITNXO,TLGHGADS,TLGHGADSden
C
      COMMON /CINFO/TAMANC,TADRTC(2),TARESC(3),TOTCO2,TACUREA,YIELDC
     +             ,TAMANC_BAL,RCO2,TCAG,TCBG,TOTCH4,TOTCO2NI
C
      COMMON /PLNTDA/ CLSIZE(0:7),PSTATE(9),PWRTS,DMDNIT,TNITUP,GS,
     +    CNUP1(MXSPEC),CNUP2(MXSPEC),UPLUX
C
C-GH Liwang MA
C     ..DSSAT PARAMETERS
C=======================================================================
C
C     VARIABLES PERTAINING TO CROPGRO and CERES Water Balance Calculations
C
C-----------------------------------------------------------------------	
      COMMON /CROPH2O/ ACTEVP,PET,ACTTRN,PER,PES,TOTPUP,PTRANSDAY
     &    ,RET_day_T,RET_day_S,ipet
C     &     ,TTRFD, SMELT,TTRO,DTSEEP,TTIRR
      REAL CGTH(MXNOD), CGT(MXNOD), CGDUL(MXNOD), CGTSHP,
     &   CGLL(MXNOD), CGSAT(MXNOD), RDFR(mxnod), RLVR(mxnod),DSLT(20),
     &  CGNO3(MXNOD), CGNH4(MXNOD), CGTLT(MXNOD), TOTPUPP,
     &  RAIN,RUNOFF,DRAIN,DEPIR,CGANO3,CGANH4,CGTOTO,CGTOTP,CGTOTF,
     &  TLTR(mxnod),cgbd(mxnod),cgph(mxnod),RZOC(MXNOD),CRAINR,
     &  RZON(MXNOD),upnitr(mxnod)
C
      COMMON/WATER_C/TRFDD_C,AIRR_C,SMELT_C,TROI_C,DTSEEP_C,TTRFDD_C,
     +               TTIRR_C
      COMMON/NITROGEN_C/TSNO3_C,TSNH4_C,TSNH4P_C,TSUR_C,TOTO_C,TOTP_C,
     +       TOTF_C,TSHP_C,RZSOILC(mxnod),RZSOILN(mxnod),
     +       totminr,totimm,totden,totvol,TOTFERT,TOTMANU
	common/rootdepth/ IR
      integer Hdate(3)
C-GH Liwang MA
C     DECLARE CONTENTS OF PLNTIN COMMON BLOCK
      DOUBLE PRECISION AHLDG,ALA,ALNAVL,ALNGER,ALNLW,ALPHA,ALX,BETA,
     +    BGSEED,CAA,CANK,CAX,CONVLA,CVLBIO,DEVRAT,DROTOL,DTSEED,GITEMP,
     +    GIWAT,GMN,GRMRAT,GSR,HFMAX,LWM,LWS,PCLDG,PGDVRT,PGNTGT,PLALFA,
     +    PLBIO,PLDIAM,PLHGHT,PLTMNT,PLTMXT,PLTOPT,PMAX,PMNNIT,PRNLW,
     +    PTLAMX,R20,RATLS,RATRSX,RATRSN,RDR,RDX,RQ10,RTNLW,SDAMAX,
     +    SDDVRT,SDSVRT,SDTMGM,SDWMAX,SFREEZ,SLA1,SLA2,SLA3,SLA4,STEND,
     +    STNAVL,STNGER,STNLW,TBS,TOP,TOT4WT,WCG,WCP,WDLDG,EFFN,CNST,
     +    PRB,GSGDD,PMAXN,PNRED,rwl(mxnod),rootn(mxnod),C1(MXNOD)
      INTEGER IPLTYP,NPL,VRNLZ,GDDFLG,EDATE,ADATE,MDATE
      COMMON /PLNTIN/ AHLDG(MXSPEC),ALA(MXSPEC),ALNAVL(MXSPEC),
     +    ALNGER(MXSPEC),ALNLW(MXSPEC),ALPHA(MXSPEC),ALX(MXSPEC),
     +    BETA(MXSPEC),BGSEED(MXSPEC),CAA(MXSPEC),CANK(MXSPEC),
     +    CAX(MXSPEC),CONVLA(MXSPEC),CVLBIO(MXSPEC),DEVRAT(2:7,MXSPEC),
     +    DROTOL(MXSPEC),EFFN(MXSPEC),DTSEED(MXSPEC),GITEMP(MXSPEC),
     +    GIWAT(MXSPEC),GMN(MXSPEC),GRMRAT(MXSPEC),GSR(MXSPEC),
     +    HFMAX(MXSPEC),PCLDG(MXSPEC),PGDVRT(MXSPEC),PGNTGT(MXSPEC),
     +    PLALFA(MXSPEC),PLBIO(MXSPEC),PLDIAM(MXSPEC),PLHGHT(MXSPEC),
     +    PLTMNT(MXSPEC),PLTMXT(MXSPEC),PLTOPT(MXSPEC),PMAX(MXSPEC),
     +    PMAXN(MXSPEC),PNRED(MXSPEC),PMNNIT(MXSPEC),PRNLW(MXSPEC),
     +    PTLAMX(MXSPEC),R20(MXSPEC),RATLS(MXSPEC),RATRSX(MXSPEC),
     +    RATRSN(MXSPEC),RDR(MXSPEC),RDX(MXSPEC),RQ10(MXSPEC),
     +    RTNLW(MXSPEC),SDAMAX(MXSPEC),SDDVRT(MXSPEC),SDSVRT(MXSPEC),
     +    SDTMGM(MXSPEC),SDWMAX(MXSPEC),SFREEZ(MXSPEC),SLA1(MXSPEC),
     +    SLA2(MXSPEC),SLA3(MXSPEC),SLA4(MXSPEC),STEND(2:6,MXSPEC),
     +    STNAVL(MXSPEC),STNGER(MXSPEC),STNLW(MXSPEC),TBS(MXSPEC),
     +    TOP(MXSPEC),TOT4WT(MXSPEC),WCG(MXSPEC),WCP(MXSPEC),
     +    WDLDG(MXSPEC),CNST(MXSPEC),PRB(7,7,MXSPEC),GSGDD(2:6,MXSPEC),
     +    GDDFLG(MXSPEC),VRNLZ(MXSPEC),SUFNDX(MXSPEC),IPLTYP(MXSPEC),
     +    LWM(MXSPEC),LWS(MXSPEC),NPL,INFIXN(MXSPEC)
C
      COMMON /PLNTG/ PLDEN(MXAPP),PLTDAY(MXAPP,2),ROWSP(MXAPP),
     +    PLDEPTH(MXAPP),sdwtplr(mxapp),sdager(mxapp),sprlapr(mxapp),
     +    PLNTSW(MXAPP),PLNTWD(MXAPP),LAYNDX(MXAPP),NPGS,NPR(MXAPP),
     +    NGPL(MXAPP),iptype(mxapp),iemrg(mxapp)
C
      CHARACTER SOLTYP*10,NMPEST*30,PLNAME*30
      COMMON /NAMES/ NMPEST(MXPEST),SOLTYP(MAXHOR),PLNAME(MXSPEC)
C
      COMMON /BMPRC/ YGOAL,OMADJ,USAMDP,UMISCC,ISTATE,ISOYB,BMPIRR,
     +    BMPTIL,FMC,YGSF,SOYYLD
C
      INTEGER IHTYPE,IHDAY,IHARV,IHCL,KOMP(5),NRKOB,DAPCALC
      COMMON /HRVST/ HSTAGE(MXAPP),HPERC(MXAPP),HRVEFF(MXAPP),YIELD(3),
     +    STUBHT(MXAPP),IHTYPE(MXAPP),IHDAY(MXAPP,3),IHARV(MXAPP),
     +    IHCL(MXAPP)
C
C     ..PASSED VARIABLES
      INTEGER JGS(2),NDXN2H(MXNOD),JGST(2),IQUE(4,MXAPP),INXPL(MXSPEC),
     +    IRTYPE(MXSPEC),ndxt2n(mxnodt),LUMDAY
      DOUBLE PRECISION RDF(MXNOD),RPOOL(MXNOD,2),SOILPP(8,MAXHOR),
     +    T(NN),UPNIT(MXNOD),PCN(0:MXNOD),PNIT(9),CN(9),CORES(MXPEST),
     +    COPLNT(MXPEST),OMSEA(MXANA),hrptrans(mhr),hrevap(mhr),
     +    ssurft(mhr),TUP(MXNOD),WORG(5),GORG(5),
     +    DGORG(5),WDORG(5),PE(MXNOD),LAIFKT(10),LUKRIT(10)    !only four plant compartments for now
C
C-GH   Liwang Ma
      DOUBLE PRECISION CC(MXNOD,MXCHEM),RLV(MXNOD),DSTL(20),tnup(mxnod)
C-GH   Liwang Ma
C     ..LOCAL VARIABLES
      DOUBLE PRECISION LAI,LFWT,LFWTS,LFWTSD,ad,lured,LURMAX,
     &     GDUL(MXNOD),GLL(MXNOD),GSAT(MXNOD)
C
      double precision obmas,wumas,wumalt,obalt
C     ..FLAG FOR CROP SWITCHING
C-GH    Liwang Ma
      CHARACTER CROPR*2,VARNOR*6, VRNAME*16,iswpar*1,DAUERKULT*1
      CHARACTER*80 MOW80
      INTEGER YRSIMR,YRSIMRS,wurz,YRPLT,PLYEAR,PLDAY,EDAP,MDAP,ADAP
      INTEGER iresetlai
      common /wsi/ wsi, alaireset, heightset, iresetlai, iresetht1
      DATA VARNOR/'     '/
      DATA VRNAME/'                '/
      save nreps
C-GH   Liwang Ma
      LOGICAL FIRST11,CHLRFL,first15,FHARV,FEXIST
      SAVE FIRST11,first15
      SAVE PCN,TTPLNT,TMPLNT,TXPLNT,IJ
C
      DATA FIRST11 /.TRUE./,istage/1/,lukrit/10*0.0d0/,IPLS/2/,ij/0/
C-MA Liwang
      DATA FIRST15/.TRUE./,FHARV/.FALSE./,NUMORGANS/5/,DAUERKULT/'N'/

      OPEN(IFILE,FILE='PLSTAT.DAT',STATUS='OLD',   ERR=90)

      READ(IFILE,*) RFDD,JDAY,IYYY,TMAX,TMIN,RTS,TPP,W,HEIGHT,LAI,T,
     +    SOILPP,NDXN2H,RDF,JGS,NSC,PLTSLV,RPOOL,UPNIT,EWP,SDEAD,TLPLNT,
     +    XNIT,BASE,FIXN,IPL,IPM,JGROW,IMAGIC,ODMDN,CN,RM,RESAGE,RCN,
     +    SDCN,CORES,COPLNT,NPEST,CHLRFL,TDAY,IQUE,INXPL,IRTYPE,OMSEA,
     +    TLAI,IPR,SDEAD_HEIGHT,AIRR,CC,RZPAR,JBDAY,IYB,CO2R,ndxt2n,
     +    iswpar,tmday,iweather,ssurft,IPDEPTH,TUP,DAYL
      CLOSE(UNIT=IFILE)
	RETURN
C     ..ERROR CONDITIONS FOR OPENNING FILE
   90 PRINT*,'ERROR OPENING THE FILE: PLSTAT.DAT'
	  PRINT*
	  PRINT*,' CHECK TO MAKE SURE THE FILE IS IN THE CURRENT DIR.'
	  STOP
C
     	END SUBROUTINE PLSTATREAD

	     SUBROUTINE PLSTATWRITE(RFDD,JDAY,IYYY,TMAX,TMIN,RTS,TPP,W,HEIGHT,LAI,T,
     +    SOILPP,NDXN2H,RDF,JGS,NSC,PLTSLV,RPOOL,UPNIT,EWP,SDEAD,TLPLNT,
     +    XNIT,BASE,FIXN,IPL,IPM,JGROW,IMAGIC,ODMDN,CN,RM,RESAGE,RCN,
     +    SDCN,CORES,COPLNT,NPEST,CHLRFL,TDAY,IQUE,INXPL,IRTYPE,OMSEA,
     +    TLAI,IPR,SDEAD_HEIGHT,AIRR,CC,RZPAR,JBDAY,IYB,CO2R,ndxt2n,
     +    iswpar,tmday,iweather,ssurft,IPDEPTH,TUP,DAYL)
C
C======================================================================
C
C       PURPOSE:  SAVE PLANT GROWTH STATE VARIABLES TO PLSTAT.DAT
C
C
C       VARIABLE DEFINITIONS:
C       VARIABLE  I/O DESCRIPTION
C       --------  --- -----------
C
C       EXTERNAL REFERENCES: None
C
C       CALLED FROM: MAIN
C
C       PROGRAMMER: BALAJI POKURI
C
C       VERSION: 0.1
C		VARIABLE LIST COPIED FROM MAPLNT(), CODE FROM STATOT()
C======================================================================
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
      PARAMETER(MXNOD=300,MAXHOR=12,MXAPP=200,MXPEST=3,MXSPEC=10,
     +    MXANA=135,mxnodt=3001,mhr=24)
C-GH    Liwang Ma
      PARAMETER (PI=3.141592654D0, R2D=180.0D0/PI, MXCHEM=15)
      COMMON /IPOTEV/ A0,AW,AC,ARI,XW,FSUN,COEPAN,rss,RST(MXSPEC)
     +    ,RXANGLE(MXSPEC),RTCCRIT(MXSPEC),RPLEAF0(MXSPEC),
     +      RRSTEXP(MXSPEC),RRLEAF0(MXSPEC)
C-GH     Liwang Ma
C
      COMMON /GEOMTR/XLONG,ASPECT,DELZ(MXNOD),ELEV,HORTHK(MAXHOR),SLOPE,
     +    AREA,TL(MXNOD),TLT(MXNOD),XLAT,ZN(MXNOD),NHOR,NN,NNT
C
      COMMON /HYDROL/ AEF,BOTFLX,DRDEP,DRSPAC,DRRAD,CLAT(MAXHOR),
     +    H(MXNOD),HKBAR(MXNOD),QF(MXNOD),SOILHP(13,MAXHOR),HFC,HWP,
     +    THETA(MXNOD),thetai(mxnod),RICH_EPS,IREBOT,ITBL,IDRAIN,
     +    MAXITER_RICH,MAXCYCLE_RICH
C
      COMMON /NINFO/ TSOTN0,TSOTN,TOTA,TOTL,TAMIN,TANIT,TADRT(2),
     +    TARAIN(2),TAIRR(3),TAFERT(3),TARES(3),TLIMM,TLDEN,TLVOL,
     +    TLRO(3),TLSEP(3),TLDRN(3),TLLAT(3),TAMANR,TMANH4,tamanr_bal
     +    ,TLN2O,TLNXO,TLNITN2O,TLNITNXO,TLGHGADS,TLGHGADSden
C
      COMMON /CINFO/TAMANC,TADRTC(2),TARESC(3),TOTCO2,TACUREA,YIELDC
     +             ,TAMANC_BAL,RCO2,TCAG,TCBG,TOTCH4,TOTCO2NI
C
      COMMON /PLNTDA/ CLSIZE(0:7),PSTATE(9),PWRTS,DMDNIT,TNITUP,GS,
     +    CNUP1(MXSPEC),CNUP2(MXSPEC),UPLUX
C
C-GH Liwang MA
C     ..DSSAT PARAMETERS
C=======================================================================
C
C     VARIABLES PERTAINING TO CROPGRO and CERES Water Balance Calculations
C
C-----------------------------------------------------------------------	
      COMMON /CROPH2O/ ACTEVP,PET,ACTTRN,PER,PES,TOTPUP,PTRANSDAY
     &    ,RET_day_T,RET_day_S,ipet
C     &     ,TTRFD, SMELT,TTRO,DTSEEP,TTIRR
      REAL CGTH(MXNOD), CGT(MXNOD), CGDUL(MXNOD), CGTSHP,
     &   CGLL(MXNOD), CGSAT(MXNOD), RDFR(mxnod), RLVR(mxnod),DSLT(20),
     &  CGNO3(MXNOD), CGNH4(MXNOD), CGTLT(MXNOD), TOTPUPP,
     &  RAIN,RUNOFF,DRAIN,DEPIR,CGANO3,CGANH4,CGTOTO,CGTOTP,CGTOTF,
     &  TLTR(mxnod),cgbd(mxnod),cgph(mxnod),RZOC(MXNOD),CRAINR,
     &  RZON(MXNOD),upnitr(mxnod)
C
      COMMON/WATER_C/TRFDD_C,AIRR_C,SMELT_C,TROI_C,DTSEEP_C,TTRFDD_C,
     +               TTIRR_C
      COMMON/NITROGEN_C/TSNO3_C,TSNH4_C,TSNH4P_C,TSUR_C,TOTO_C,TOTP_C,
     +       TOTF_C,TSHP_C,RZSOILC(mxnod),RZSOILN(mxnod),
     +       totminr,totimm,totden,totvol,TOTFERT,TOTMANU
	common/rootdepth/ IR
      integer Hdate(3)
C-GH Liwang MA
C     DECLARE CONTENTS OF PLNTIN COMMON BLOCK
      DOUBLE PRECISION AHLDG,ALA,ALNAVL,ALNGER,ALNLW,ALPHA,ALX,BETA,
     +    BGSEED,CAA,CANK,CAX,CONVLA,CVLBIO,DEVRAT,DROTOL,DTSEED,GITEMP,
     +    GIWAT,GMN,GRMRAT,GSR,HFMAX,LWM,LWS,PCLDG,PGDVRT,PGNTGT,PLALFA,
     +    PLBIO,PLDIAM,PLHGHT,PLTMNT,PLTMXT,PLTOPT,PMAX,PMNNIT,PRNLW,
     +    PTLAMX,R20,RATLS,RATRSX,RATRSN,RDR,RDX,RQ10,RTNLW,SDAMAX,
     +    SDDVRT,SDSVRT,SDTMGM,SDWMAX,SFREEZ,SLA1,SLA2,SLA3,SLA4,STEND,
     +    STNAVL,STNGER,STNLW,TBS,TOP,TOT4WT,WCG,WCP,WDLDG,EFFN,CNST,
     +    PRB,GSGDD,PMAXN,PNRED,rwl(mxnod),rootn(mxnod),C1(MXNOD)
      INTEGER IPLTYP,NPL,VRNLZ,GDDFLG,EDATE,ADATE,MDATE
      COMMON /PLNTIN/ AHLDG(MXSPEC),ALA(MXSPEC),ALNAVL(MXSPEC),
     +    ALNGER(MXSPEC),ALNLW(MXSPEC),ALPHA(MXSPEC),ALX(MXSPEC),
     +    BETA(MXSPEC),BGSEED(MXSPEC),CAA(MXSPEC),CANK(MXSPEC),
     +    CAX(MXSPEC),CONVLA(MXSPEC),CVLBIO(MXSPEC),DEVRAT(2:7,MXSPEC),
     +    DROTOL(MXSPEC),EFFN(MXSPEC),DTSEED(MXSPEC),GITEMP(MXSPEC),
     +    GIWAT(MXSPEC),GMN(MXSPEC),GRMRAT(MXSPEC),GSR(MXSPEC),
     +    HFMAX(MXSPEC),PCLDG(MXSPEC),PGDVRT(MXSPEC),PGNTGT(MXSPEC),
     +    PLALFA(MXSPEC),PLBIO(MXSPEC),PLDIAM(MXSPEC),PLHGHT(MXSPEC),
     +    PLTMNT(MXSPEC),PLTMXT(MXSPEC),PLTOPT(MXSPEC),PMAX(MXSPEC),
     +    PMAXN(MXSPEC),PNRED(MXSPEC),PMNNIT(MXSPEC),PRNLW(MXSPEC),
     +    PTLAMX(MXSPEC),R20(MXSPEC),RATLS(MXSPEC),RATRSX(MXSPEC),
     +    RATRSN(MXSPEC),RDR(MXSPEC),RDX(MXSPEC),RQ10(MXSPEC),
     +    RTNLW(MXSPEC),SDAMAX(MXSPEC),SDDVRT(MXSPEC),SDSVRT(MXSPEC),
     +    SDTMGM(MXSPEC),SDWMAX(MXSPEC),SFREEZ(MXSPEC),SLA1(MXSPEC),
     +    SLA2(MXSPEC),SLA3(MXSPEC),SLA4(MXSPEC),STEND(2:6,MXSPEC),
     +    STNAVL(MXSPEC),STNGER(MXSPEC),STNLW(MXSPEC),TBS(MXSPEC),
     +    TOP(MXSPEC),TOT4WT(MXSPEC),WCG(MXSPEC),WCP(MXSPEC),
     +    WDLDG(MXSPEC),CNST(MXSPEC),PRB(7,7,MXSPEC),GSGDD(2:6,MXSPEC),
     +    GDDFLG(MXSPEC),VRNLZ(MXSPEC),SUFNDX(MXSPEC),IPLTYP(MXSPEC),
     +    LWM(MXSPEC),LWS(MXSPEC),NPL,INFIXN(MXSPEC)
C
      COMMON /PLNTG/ PLDEN(MXAPP),PLTDAY(MXAPP,2),ROWSP(MXAPP),
     +    PLDEPTH(MXAPP),sdwtplr(mxapp),sdager(mxapp),sprlapr(mxapp),
     +    PLNTSW(MXAPP),PLNTWD(MXAPP),LAYNDX(MXAPP),NPGS,NPR(MXAPP),
     +    NGPL(MXAPP),iptype(mxapp),iemrg(mxapp)
C
      CHARACTER SOLTYP*10,NMPEST*30,PLNAME*30
      COMMON /NAMES/ NMPEST(MXPEST),SOLTYP(MAXHOR),PLNAME(MXSPEC)
C
      COMMON /BMPRC/ YGOAL,OMADJ,USAMDP,UMISCC,ISTATE,ISOYB,BMPIRR,
     +    BMPTIL,FMC,YGSF,SOYYLD
C
      INTEGER IHTYPE,IHDAY,IHARV,IHCL,KOMP(5),NRKOB,DAPCALC
      COMMON /HRVST/ HSTAGE(MXAPP),HPERC(MXAPP),HRVEFF(MXAPP),YIELD(3),
     +    STUBHT(MXAPP),IHTYPE(MXAPP),IHDAY(MXAPP,3),IHARV(MXAPP),
     +    IHCL(MXAPP)
C
C     ..PASSED VARIABLES
      INTEGER JGS(2),NDXN2H(MXNOD),JGST(2),IQUE(4,MXAPP),INXPL(MXSPEC),
     +    IRTYPE(MXSPEC),ndxt2n(mxnodt),LUMDAY
      DOUBLE PRECISION RDF(MXNOD),RPOOL(MXNOD,2),SOILPP(8,MAXHOR),
     +    T(NN),UPNIT(MXNOD),PCN(0:MXNOD),PNIT(9),CN(9),CORES(MXPEST),
     +    COPLNT(MXPEST),OMSEA(MXANA),hrptrans(mhr),hrevap(mhr),
     +    ssurft(mhr),TUP(MXNOD),WORG(5),GORG(5),
     +    DGORG(5),WDORG(5),PE(MXNOD),LAIFKT(10),LUKRIT(10)    !only four plant compartments for now
C
C-GH   Liwang Ma
      DOUBLE PRECISION CC(MXNOD,MXCHEM),RLV(MXNOD),DSTL(20),tnup(mxnod)
C-GH   Liwang Ma
C     ..LOCAL VARIABLES
      DOUBLE PRECISION LAI,LFWT,LFWTS,LFWTSD,ad,lured,LURMAX,
     &     GDUL(MXNOD),GLL(MXNOD),GSAT(MXNOD)
C
      double precision obmas,wumas,wumalt,obalt
C     ..FLAG FOR CROP SWITCHING
C-GH    Liwang Ma
      CHARACTER CROPR*2,VARNOR*6, VRNAME*16,iswpar*1,DAUERKULT*1
      CHARACTER*80 MOW80
      INTEGER YRSIMR,YRSIMRS,wurz,YRPLT,PLYEAR,PLDAY,EDAP,MDAP,ADAP
      INTEGER iresetlai
      common /wsi/ wsi, alaireset, heightset, iresetlai, iresetht1
      DATA VARNOR/'     '/
      DATA VRNAME/'                '/
      save nreps
C-GH   Liwang Ma
      LOGICAL FIRST11,CHLRFL,first15,FHARV,FEXIST
      SAVE FIRST11,first15
      SAVE PCN,TTPLNT,TMPLNT,TXPLNT,IJ
C
      DATA FIRST11 /.TRUE./,istage/1/,lukrit/10*0.0d0/,IPLS/2/,ij/0/
C-MA Liwang
      DATA FIRST15/.TRUE./,FHARV/.FALSE./,NUMORGANS/5/,DAUERKULT/'N'/

      OPEN(IFILE,FILE='PLSTAT.DAT',STATUS='UNKNOWN',   ERR=50)

      WRITE(IFILE,*) RFDD,JDAY,IYYY,TMAX,TMIN,RTS,TPP,W,HEIGHT,LAI,T,
     +    SOILPP,NDXN2H,RDF,JGS,NSC,PLTSLV,RPOOL,UPNIT,EWP,SDEAD,TLPLNT,
     +    XNIT,BASE,FIXN,IPL,IPM,JGROW,IMAGIC,ODMDN,CN,RM,RESAGE,RCN,
     +    SDCN,CORES,COPLNT,NPEST,CHLRFL,TDAY,IQUE,INXPL,IRTYPE,OMSEA,
     +    TLAI,IPR,SDEAD_HEIGHT,AIRR,CC,RZPAR,JBDAY,IYB,CO2R,ndxt2n,
     +    iswpar,tmday,iweather,ssurft,IPDEPTH,TUP,DAYL
      CLOSE(UNIT=IFILE)
	RETURN
C     ..ERROR CONDITIONS FOR OPENNING FILE
   50 PRINT*,'ERROR OPENING THE FILE: PLSTAT.DAT'
	  PRINT*
	  PRINT*,' CHECK TO MAKE SURE THE FILE IS IN THE CURRENT DIR.'
	  STOP
C
     	END SUBROUTINE PLSTATWRITE
