! RZinterrupt.for Balaji Pokuri, Jan 2022
C Utility code to save plant state and resume on next run
C 
! 	     SUBROUTINE PLSTATREAD(RFDD,JDAY,IYYY,TMAX,TMIN,RTS,TPP,W,HEIGHT,LAI,T,
!      +    SOILPP,NDXN2H,RDF,JGS,NSC,PLTSLV,RPOOL,UPNIT,EWP,SDEAD,TLPLNT,
!      +    XNIT,BASE,FIXN,IPL,IPM,JGROW,IMAGIC,ODMDN,CN,RM,RESAGE,RCN,
!      +    SDCN,CORES,COPLNT,NPEST,CHLRFL,TDAY,IQUE,INXPL,IRTYPE,OMSEA,
!      +    TLAI,IPR,SDEAD_HEIGHT,AIRR,CC,RZPAR,JBDAY,IYB,CO2R,ndxt2n,
!      +    iswpar,tmday,iweather,ssurft,IPDEPTH,TUP,DAYL)
! C
! C======================================================================
! C
! C       PURPOSE:  DUMP ALL VARIABLES TO PLSTAT.DAT
! C
! C
! C       VARIABLE DEFINITIONS:
! C       VARIABLE  I/O DESCRIPTION
! C       --------  --- -----------
! C
! C       EXTERNAL REFERENCES: None
! C
! C       CALLED FROM: MAIN
! C
! C       PROGRAMMER: BALAJI POKURI
! C
! C       VERSION: 0.1
! C		VARIABLE LIST COPIED FROM MAPLNT(), CODE FROM STATIN()
! C======================================================================
! C
!       OPEN(IFILE,FILE='PLSTAT.DAT',STATUS='OLD',   ERR=90)

!       READ(IFILE,*) RFDD,JDAY,IYYY,TMAX,TMIN,RTS,TPP,W,HEIGHT,LAI,T,
!      +    SOILPP,NDXN2H,RDF,JGS,NSC,PLTSLV,RPOOL,UPNIT,EWP,SDEAD,TLPLNT,
!      +    XNIT,BASE,FIXN,IPL,IPM,JGROW,IMAGIC,ODMDN,CN,RM,RESAGE,RCN,
!      +    SDCN,CORES,COPLNT,NPEST,CHLRFL,TDAY,IQUE,INXPL,IRTYPE,OMSEA,
!      +    TLAI,IPR,SDEAD_HEIGHT,AIRR,CC,RZPAR,JBDAY,IYB,CO2R,ndxt2n,
!      +    iswpar,tmday,iweather,ssurft,IPDEPTH,TUP,DAYL
!       CLOSE(UNIT=IFILE)
! 	RETURN
! C     ..ERROR CONDITIONS FOR OPENNING FILE
!    90 PRINT*,'ERROR OPENING THE FILE: PLSTAT.DAT'
! 	  PRINT*
! 	  PRINT*,' CHECK TO MAKE SURE THE FILE IS IN THE CURRENT DIR.'
! 	  STOP
! C
!      	END SUBROUTINE PLSTATREAD

      SUBROUTINE PLSTATWRITE()
C
C======================================================================
C
C       PURPOSE:  SAVE PLANT GROWTH STATE VARIABLES TO PLSTAT.DAT
C
C
C       VARIABLE DEFINITIONS:
C       VARIABLE  I/O DESCRIPTION
C       --------  --- -----------
C
C       EXTERNAL REFERENCES: None
C
C       CALLED FROM: MAIN
C
C       PROGRAMMER: BALAJI POKURI
C
C       VERSION: 0.1
C		VARIABLE LIST COPIED FROM MAPLNT(), CODE FROM STATOT()
C======================================================================
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C     LOAD ALL VARIABLES WE CAN GET
C
C     Variables from RZmain.for
C
      PARAMETER(MXNOD=300,MXNODT=3001,MAXHOR=12,MAXSCT=11,MXCHEM=15,
     +    MXPEST=3,MXAPP=200,MXSPEC=10,MXANA=135,MHR=24)
      PARAMETER(MXTN=39,MXTNC=27,MXTP=19)
      PARAMETER(MXTSTP=5000,rhoi=9.2d2,rhol=1.0d3)
      PARAMETER(R2D=180.0D0/3.141592654D0,FCR=0.4d0)
      PARAMETER(MX2=MXNOD*2,MXC=MXNOD*MXCHEM,MXN=MXNOD*25,MXP=MXNOD*
     +    MXPEST,MAPA=MXAPP*4,MXTPP=MXPEST*MXTP)
      PARAMETER(MAXBP=50)
      PARAMETER(LX2=MAXHOR*13,LX3=MAXHOR*8,LX4=MAXHOR*5,LX5=MXAPP*2,LX6=
     +    MAXHOR*MAXSCT*3,MXPE=MXNOD*MXPEST,LX7=MXNOD*3,LST=5*MXSPEC,LDV
     +    =6*MXSPEC,MXAPP3=MXAPP*3,MXAPP20=MXAPP*20,MXAPP00=MXAPP*200)
      PARAMETER(MXHCH=MXNOD*MXCHEM,MXNCH=MXNODT*MXCHEM,MXTCH=MXTSTP*
     +    MXCHEM)
      PARAMETER(NUMSCN=7,NUMSCA=107,NUMVEC=59,IHZNUM=21,MAXSCA=41,MAXVEC
     +    =23)
      PARAMETER(TTN=-50.0D0,TTX=50.0D0,TUN=45.0D0,TUX=4700.0D0,TRN=
     +    0.0D0,TRX=45.0D0,TRHN=0.0D0,TRHX=100.0D0,UBREEZ=100.0D0)
      PARAMETER(IKEN=8+13+5+3*MAXSCT+8)
      PARAMETER(MXTNCA=9)
      PARAMETER(IFILE=85,CARBCV=1.0D0/0.58D0)


      COMMON /HEAT/ CSH(MXNOD),T(MXNOD),SOLTP1(MAXHOR,5),
     +    SOLTP2(MAXSCT,MAXHOR,3)
      COMMON /GEOMTR/XLONG,ASPECT,DELZ(MXNOD),ELEV,HORTHK(MAXHOR),SLOPE,
     +    AREA,TL(MXNOD),TLT(MXNOD),XLAT,ZN(MXNOD),NHOR,NN,NNT
      COMMON /HYDROL/ AEF,BOTFLX,DRDEP,DRSPAC,DRRAD,CLAT(MAXHOR),
     +    HEAT(MXNOD),HKBAR(MXNOD),QF(MXNOD),SOILHP(13,MAXHOR),HFC,HWP,
     +    THETA(MXNOD),thetai(mxnod),RICH_EPS,IREBOT,ITBL,IDRAIN,
     +    MAXITER_RICH,MAXCYCLE_RICH
      COMMON /IPMACF/ AGSZ(MAXHOR),FDEP(MAXHOR),MCPOR(MAXHOR),PI,
     +    PL(MAXHOR),RP(MAXHOR),SFCT,TWOPI,WP(MAXHOR),NHCMP,YESMAC,
     +    EFFWR,EFFWC,XPRESF
      COMMON /PLNTG/ PLDEN(MXAPP),PLTDAY(MXAPP,2),ROWSP(MXAPP),
     +    PLDEPTH(MXAPP),sdwtplr(mxapp),sdager(mxapp),sprlapr(mxapp),
     +    PLNTSW(MXAPP),PLNTWD(MXAPP),LAYNDX(MXAPP),NPGS,NPR(MXAPP),
     +    NGPL(MXAPP),iptype(mxapp),iemrg(mxapp)
      common /gleams/rzrainfall,rzirrigation,rzrunoff
      common /Gleams_hydsol/gleams_clay,gleams_silt,gleams_por,
     +        gleams_om1,gleams_sand,gleams_BulkDn,gleams_Dacre, 
     +        gleams_CHS,gleams_ei,gleams_exrain,thirtyRR,  
     +        IBYEAR,IEYEAR 
      common /po4log/ErosionActive,UseEnrichment
      COMMON /SOIL/ SOILPP(8,MAXHOR),pori(mxnod)
      COMMON /NDEX/ NDXN2H(MXNOD),NDXH2N(MAXHOR),NDXN2T(MXNOD),
     +    NDXT2N(MXNODT)
      COMMON /RZPEST/ HALFF(MXPEST),HALFFP(MXPEST),HALFFB(MXPEST),
     +    HALFR(MXPEST),HALFRP(MXPEST),HALFRB(MXPEST),HALFSSA(MXPEST),
     +    HALFSSV(MXPEST),HALFSSP(MXPEST),HALFSSB(MXPEST),
     +    HALFSA(MXPEST),HALFSN(MXPEST),HALFSB(MXPEST),HALFBD(MXPEST),
     +    XKH(MXPEST),XKOC(MXPEST),XMW(MXPEST),THETAR(MXPEST),
     +    TMPR(MXPEST),EA(MXPEST),EN(MXPEST),WALKERB(MXPEST),
     +    VMAX(MXPEST),DYIELD(4,MXPEST),FREUND(MXPEST),XPKA(MXPEST),
     +    XPKB(MXPEST),REFPH(MXPEST),CATKOC(MXPEST),ANKOC(MXPEST),
     +    PCOEFF(MXPEST),PPOWER(MXPEST),RCOEFF(MXPEST),RPOWER(MXPEST),
     +    XKOW(MXPEST),PBIND(MXPEST),IPCODE(4,MXPEST),IPANC(MXPEST),
     +    IPDEP(MXPEST),IPACTV(MXPEST),NPEST
      common /maxbal/IDmxH2O,IMmxH2O,IYYYmxH2O,IDmxN,IMmxN,IYYYmxN,
     +              IDmxC,IMmxC,IYYYmxC,IDmxP,IMmxP,IYYYmxP,
     +              DTMASSmxH2O,BalmxN,BalmxC,BalmxP,IWCINIT1
     +            ,ireset1
      COMMON /KNTCS/ CONCX2(MXNOD,MXPEST),EK2(MXNOD,MXPEST),
     +    RK2(MXPEST),RDIF(MXPEST),FEK2(MXPEST),IEK2(MXPEST)
      COMMON /RESID/ RM,RESAGE,CRES,HR,RCN,NADLY,NSDLY,NAREC,NSREC,WORM,
     +               SAI,HSTUBL,WSTUBL
      COMMON /PLNTDA/ CLSIZE(0:7),PSTATE(9),PWRTS,DMDNIT,TNITUP,GS,
     +    CNUP1(MXSPEC),CNUP2(MXSPEC),UPLUX
      COMMON /NUTPAR/ R14,R23,R34,R43,R45,R53,R15,R25,EFFMAX,EFFNIT,
     +    EFFDEN,DENC,RPOP(3),ADCAY,ANIT,ADENIT,AUREA,ADEATH(3),CN(9),
     +    ADCAYV(5),XKP(3),AMETH,FRN2O_NIT,FRN2O_DEN,RNO_N2O,RAINNO,
     +    O2LIM,EFFMETH,ISBUG
      COMMON /PINFO/ TSOTP0(MXPEST),TAPAP(MXPEST),TLPRS(MXPEST),
     +    TLPCN(MXPEST),TLPSL(MXPEST),TLPRO(MXPEST),TLPLC(MXPEST),
     +    TDPPLNT(MXPEST),TLPDT(MXPEST),TLPDTD(MXPEST),
     +    TLPDTL(MXPEST),TLPDMA(MXPEST)
      COMMON /SC1/ ISTAB,IVTAB,ISPLT,IVPLT
      COMMON /IPOTEV/ A0,AW,AC,ARI,XW,FSUN,COEPAN,rss,RST(MXSPEC)
     +    ,RXANGLE(MXSPEC),RTCCRIT(MXSPEC),RPLEAF0(MXSPEC),
     +      RRSTEXP(MXSPEC),RRLEAF0(MXSPEC)
      common /sumet/sumAET,sumCropET,sumPET,sumPT,sumAT,sumrain,deltheta
      common /hourweather/ hrt,hrts,hru,hrh,HRZPAR,HRTH
      common /wsi/ wsi, alaireset, heightset, iresetlai, iresetht1
C
C     BLOCK DATA BLOCK1
C
      COMMON /IRRIG/ DOIMAX(MXAPP),FDOI(MXAPP),VDOI(MXAPP,MXAPP),
     +    XKU(MXAPP,20),XMAD(MXAPP,20),RRATE(MXAPP),amxirr,
     +    totaliw,DOIMONTH(12,200),TOTALMONTH,airrdepth,amirr,
     +    RRDUR(MXAPP),IIPL(MXAPP),ISPT(MXAPP),ITOI(MXAPP),
     +    JDIRRB(MXAPP),JDIRRE(MXAPP),NAPPI,NDAIRR(MXAPP),NKU(MXAPP),
     +    NMAD(MXAPP),JDOI(MXAPP,MXAPP),JKU(MXAPP,20),JMAD(MXAPP,20),
     +    IDOI(MXAPP),id_depth,MONTHIRR
      COMMON /PLNTIN/ AHLDG(MXSPEC),ALA(MXSPEC),ALNAVL(MXSPEC),
     +    ALNGER(MXSPEC),ALNLW(MXSPEC),ALPHA(MXSPEC),ALX(MXSPEC),
     +    BETA(MXSPEC),BGSEED(MXSPEC),CAA(MXSPEC),CANK(MXSPEC),
     +    CAX(MXSPEC),CONVLA(MXSPEC),CVLBIO(MXSPEC),DEVRAT(2:7,MXSPEC),
     +    DROTOL(MXSPEC),EFFN(MXSPEC),DTSEED(MXSPEC),GITEMP(MXSPEC),
     +    GIWAT(MXSPEC),GMN(MXSPEC),GRMRAT(MXSPEC),GSR(MXSPEC),
     +    HFMAX(MXSPEC),PCLDG(MXSPEC),PGDVRT(MXSPEC),PGNTGT(MXSPEC),
     +    PLALFA(MXSPEC),PLBIO(MXSPEC),PLDIAM(MXSPEC),PLHGHT(MXSPEC),
     +    PLTMNT(MXSPEC),PLTMXT(MXSPEC),PLTOPT(MXSPEC),PMAX(MXSPEC),
     +    PMAXN(MXSPEC),PNRED(MXSPEC),PMNNIT(MXSPEC),PRNLW(MXSPEC),
     +    PTLAMX(MXSPEC),R20(MXSPEC),RATLS(MXSPEC),RATRSX(MXSPEC),
     +    RATRSN(MXSPEC),RDR(MXSPEC),RDX(MXSPEC),RQ10(MXSPEC),
     +    RTNLW(MXSPEC),SDAMAX(MXSPEC),SDDVRT(MXSPEC),SDSVRT(MXSPEC),
     +    SDTMGM(MXSPEC),SDWMAX(MXSPEC),SFREEZ(MXSPEC),SLA1(MXSPEC),
     +    SLA2(MXSPEC),SLA3(MXSPEC),SLA4(MXSPEC),STEND(2:6,MXSPEC),
     +    STNAVL(MXSPEC),STNGER(MXSPEC),STNLW(MXSPEC),TBS(MXSPEC),
     +    TOP(MXSPEC),TOT4WT(MXSPEC),WCG(MXSPEC),WCP(MXSPEC),
     +    WDLDG(MXSPEC),CNST(MXSPEC),PRB(7,7,MXSPEC),GSGDD(2:6,MXSPEC),
     +    GDDFLG(MXSPEC),VRNLZ(MXSPEC),SUFNDX(MXSPEC),IPLTYP(MXSPEC),
     +    LWM(MXSPEC),LWS(MXSPEC),NPL,INFIXN(MXSPEC)
      COMMON /HRVST/ HSTAGE(MXAPP),HPERC(MXAPP),HRVEFF(MXAPP),YIELD(3),
     +    STUBHT(MXAPP),IHTYPE(MXAPP),IHDAY(MXAPP,3),IHARV(MXAPP),
     +    IHCL(MXAPP)
      COMMON /SCCONC/ AL,ALOH,ALSO4,CA,CASO4,H,HCO3,SO4,XMG,XMGSO4,XNA,
     +    XNASO4,XNAORG,XNH4,ORG,CO3,ALORG,ALI,ALOHI,ALSO4I,CAI,CO3I,HI,
     +    HCO3I,ORGI,SO4I,XMGI,XNAI,XNH4I,ALIS,ALOHIS,ALSOIS,CAIS,CO3IS,
     +    HIS,HCO3IS,ORGIS,SO4IS,XMGIS,XNAIS,XNASIS,XNH4IS,ALORIS
      COMMON /SCHMIN/ ECA(MXNOD),ENA(MXNOD),EMG(MXNOD),ENH4(MXNOD),
     +    EAL(MXNOD),SCL(MXNOD,3),CEC(MXNOD)
      COMMON /INFILC/ RAC(11),RRC(11),FERTIR(4),PESTIR(MXPEST),FMNRIR
      COMMON /OPINF/ RO,SWF(MXnod),TR(MXTSTP),CI(MXTSTP),CRFD(MAXBP),
     +    CRFT(MAXBP),RFI(MAXBP),RFDD,RFD
      COMMON /OPCHEM/ THSMS(MXNOD,MXCHEM),CUPRO,CUPCHM(MXCHEM),CDNCI,
     +    CDNCHM(MXCHEM),CMESO(MXNODT,MXCHEM),CMICR(MXNODT,MXCHEM),
     +    CRO(MXTSTP,MXCHEM)
      COMMON /OPMACF/ CDBET(MXNODT,MXCHEM),CFLOW(MXNODT,MXCHEM),
     +    CDFLOW(MXNODT,MXCHEM),CUMCLM(MXTSTP,MXCHEM),
     +    CUMCLR(MXTSTP,MXCHEM),CUMMF(MXTSTP),CUMRO(MXTSTP),
     +    DBET(MXNODT),DFLOW(MXNODT),FLOW(MXNODT),TDFLOW(MXNODT),
     +    TFLOW(MXNODT)
      COMMON /IPCHEM/ A,ALH(MXNOD,MXCHEM),B,BDH(MAXHOR),DEG(MAXHOR),
     +    BDHR(MAXHOR),MICP(MAXHOR),NMICP
      COMMON /IPINF/ CRUSTK,OCRUST,ICRUST,INFLPD,NHZ,NSLT,POND,RR,
     +    DHB(MAXHOR),NSL(MAXHOR),WI(MXnod),DSL(MXNODT),VWC(MXNODT),
     +    IUGFLW
      COMMON /INTMCF/ FLXMAX(MAXHOR),DB(MAXHOR),NPOR(MAXHOR)
      COMMON /MMNUR/ AMNH4(MXAPP),AMOW(MXAPP),AMBED(MXAPP),
     +    CNBED(MXAPP),AMCN(15),CNMANR(MXAPP),FCMANR(MXAPP),
     +    IWMANR(MXAPP),IMOFF(MXAPP,2),IMMETH(MXAPP),IMTYPE(MXAPP),
     +    NAPPM,IMPL(MXAPP),IMANDECOMP(MXAPP)
      COMMON /MFERT/ FNH4IN(MXAPP),FNO3IN(MXAPP),FUREIN(MXAPP),
     +    SPLTST(MXAPP),SPLTAP(MXAPP),IFOFF(MXAPP,2),IFMETH(MXAPP),
     +    IWFERT(MXAPP),NAPPF,IBMPAP(MXAPP),IBMPMD(MXAPP),
     +    IDSPLT(MXAPP),IFPL(MXAPP)
      COMMON /MPEST/ APP(MXAPP),PDR(MXAPP),IAPP(MXAPP),IPOFF(MXAPP,2),
     +    IWPEST(MXAPP),IPMETH(MXAPP),NAPP,IPPL(MXAPP)
      COMMON /TILLIN/ OBD(2),OFDP(2),TDEPTH(30),TILINT(30,2),
     +    TNDX(MXAPP),UDEPTH(MXAPP), PManureMix(MXAPP), IMP(MXAPP),  
     +    ITL(MXAPP), ITOFF(MXAPP,2),IWTILL(MXAPP),NUMTL, ITPL(MXAPP)
C
C     BLOCK DATA BLKOUT
C
      COMMON /SSLIST/ SCASSL,USSSL,VECSSL,UVSSL,ASSSL,AVSSL
      COMMON /FUNIT/ SC,CNTRL,SCAPLT,VECPLT,SCATAB,VECTAB,ISCA,IVEC
      COMMON /LABLS/ SCNRIO,SCALAR,VECTOR,HZLABS


C
C
C    Now Open the dat file to write
C
C
      OPEN(IFILE,FILE='INTERMEDIATE.DAT',STATUS='UNKNOWN', ERR=50)
C
C
C    Write each set of common variables in sequence
C
C
      WRITE(IFILE,*) CSH(MXNOD),T(MXNOD),SOLTP1(MAXHOR,5),
     +    SOLTP2(MAXSCT,MAXHOR,3)
      WRITE(IFILE,*)XLONG,ASPECT,DELZ(MXNOD),ELEV,HORTHK(MAXHOR),SLOPE,
     +    AREA,TL(MXNOD),TLT(MXNOD),XLAT,ZN(MXNOD),NHOR,NN,NNT
      WRITE(IFILE,*) AEF,BOTFLX,DRDEP,DRSPAC,DRRAD,CLAT(MAXHOR),
     +    HEAT(MXNOD),HKBAR(MXNOD),QF(MXNOD),SOILHP(13,MAXHOR),HFC,HWP,
     +    THETA(MXNOD),thetai(mxnod),RICH_EPS,IREBOT,ITBL,IDRAIN,
     +    MAXITER_RICH,MAXCYCLE_RICH
      WRITE(IFILE,*) AGSZ(MAXHOR),FDEP(MAXHOR),MCPOR(MAXHOR),PI,
     +    PL(MAXHOR),RP(MAXHOR),SFCT,TWOPI,WP(MAXHOR),NHCMP,YESMAC,
     +    EFFWR,EFFWC,XPRESF
      WRITE(IFILE,*) PLDEN(MXAPP),PLTDAY(MXAPP,2),ROWSP(MXAPP),
     +    PLDEPTH(MXAPP),sdwtplr(mxapp),sdager(mxapp),sprlapr(mxapp),
     +    PLNTSW(MXAPP),PLNTWD(MXAPP),LAYNDX(MXAPP),NPGS,NPR(MXAPP),
     +    NGPL(MXAPP),iptype(mxapp),iemrg(mxapp)
      WRITE(IFILE,*)rzrainfall,rzirrigation,rzrunoff
      WRITE(IFILE,*)gleams_clay,gleams_silt,gleams_por,
     +        gleams_om1,gleams_sand,gleams_BulkDn,gleams_Dacre, 
     +        gleams_CHS,gleams_ei,gleams_exrain,thirtyRR,  
     +        IBYEAR,IEYEAR 
      WRITE(IFILE,*)ErosionActive,UseEnrichment
      WRITE(IFILE,*) SOILPP(8,MAXHOR),pori(mxnod)
      WRITE(IFILE,*) NDXN2H(MXNOD),NDXH2N(MAXHOR),NDXN2T(MXNOD),
     +    NDXT2N(MXNODT)
      WRITE(IFILE,*) HALFF(MXPEST),HALFFP(MXPEST),HALFFB(MXPEST),
     +    HALFR(MXPEST),HALFRP(MXPEST),HALFRB(MXPEST),HALFSSA(MXPEST),
     +    HALFSSV(MXPEST),HALFSSP(MXPEST),HALFSSB(MXPEST),
     +    HALFSA(MXPEST),HALFSN(MXPEST),HALFSB(MXPEST),HALFBD(MXPEST),
     +    XKH(MXPEST),XKOC(MXPEST),XMW(MXPEST),THETAR(MXPEST),
     +    TMPR(MXPEST),EA(MXPEST),EN(MXPEST),WALKERB(MXPEST),
     +    VMAX(MXPEST),DYIELD(4,MXPEST),FREUND(MXPEST),XPKA(MXPEST),
     +    XPKB(MXPEST),REFPH(MXPEST),CATKOC(MXPEST),ANKOC(MXPEST),
     +    PCOEFF(MXPEST),PPOWER(MXPEST),RCOEFF(MXPEST),RPOWER(MXPEST),
     +    XKOW(MXPEST),PBIND(MXPEST),IPCODE(4,MXPEST),IPANC(MXPEST),
     +    IPDEP(MXPEST),IPACTV(MXPEST),NPEST
      WRITE(IFILE,*)IDmxH2O,IMmxH2O,IYYYmxH2O,IDmxN,IMmxN,IYYYmxN,
     +              IDmxC,IMmxC,IYYYmxC,IDmxP,IMmxP,IYYYmxP,
     +              DTMASSmxH2O,BalmxN,BalmxC,BalmxP,IWCINIT1
     +            ,ireset1
      WRITE(IFILE,*) CONCX2(MXNOD,MXPEST),EK2(MXNOD,MXPEST),
     +    RK2(MXPEST),RDIF(MXPEST),FEK2(MXPEST),IEK2(MXPEST)
      WRITE(IFILE,*) RM,RESAGE,CRES,HR,RCN,NADLY,NSDLY,NAREC,NSREC,WORM,
     +               SAI,HSTUBL,WSTUBL
      WRITE(IFILE,*) CLSIZE(0:7),PSTATE(9),PWRTS,DMDNIT,TNITUP,GS,
     +    CNUP1(MXSPEC),CNUP2(MXSPEC),UPLUX
      WRITE(IFILE,*) R14,R23,R34,R43,R45,R53,R15,R25,EFFMAX,EFFNIT,
     +    EFFDEN,DENC,RPOP(3),ADCAY,ANIT,ADENIT,AUREA,ADEATH(3),CN(9),
     +    ADCAYV(5),XKP(3),AMETH,FRN2O_NIT,FRN2O_DEN,RNO_N2O,RAINNO,
     +    O2LIM,EFFMETH,ISBUG
      WRITE(IFILE,*) TSOTP0(MXPEST),TAPAP(MXPEST),TLPRS(MXPEST),
     +    TLPCN(MXPEST),TLPSL(MXPEST),TLPRO(MXPEST),TLPLC(MXPEST),
     +    TDPPLNT(MXPEST),TLPDT(MXPEST),TLPDTD(MXPEST),
     +    TLPDTL(MXPEST),TLPDMA(MXPEST)
      WRITE(IFILE,*) ISTAB,IVTAB,ISPLT,IVPLT
      WRITE(IFILE,*) A0,AW,AC,ARI,XW,FSUN,COEPAN,rss,RST(MXSPEC)
     +    ,RXANGLE(MXSPEC),RTCCRIT(MXSPEC),RPLEAF0(MXSPEC),
     +      RRSTEXP(MXSPEC),RRLEAF0(MXSPEC)
      WRITE(IFILE,*)sumAET,sumCropET,sumPET,sumPT,sumAT,sumrain,deltheta
      WRITE(IFILE,*) hrt,hrts,hru,hrh,HRZPAR,HRTH
      WRITE(IFILE,*) wsi, alaireset, heightset, iresetlai, iresetht1
C
C     BLOCK DATA BLOCK1
C
      WRITE(IFILE,*) DOIMAX(MXAPP),FDOI(MXAPP),VDOI(MXAPP,MXAPP),
     +    XKU(MXAPP,20),XMAD(MXAPP,20),RRATE(MXAPP),amxirr,
     +    totaliw,DOIMONTH(12,200),TOTALMONTH,airrdepth,amirr,
     +    RRDUR(MXAPP),IIPL(MXAPP),ISPT(MXAPP),ITOI(MXAPP),
     +    JDIRRB(MXAPP),JDIRRE(MXAPP),NAPPI,NDAIRR(MXAPP),NKU(MXAPP),
     +    NMAD(MXAPP),JDOI(MXAPP,MXAPP),JKU(MXAPP,20),JMAD(MXAPP,20),
     +    IDOI(MXAPP),id_depth,MONTHIRR
      WRITE(IFILE,*) AHLDG(MXSPEC),ALA(MXSPEC),ALNAVL(MXSPEC),
     +    ALNGER(MXSPEC),ALNLW(MXSPEC),ALPHA(MXSPEC),ALX(MXSPEC),
     +    BETA(MXSPEC),BGSEED(MXSPEC),CAA(MXSPEC),CANK(MXSPEC),
     +    CAX(MXSPEC),CONVLA(MXSPEC),CVLBIO(MXSPEC),DEVRAT(2:7,MXSPEC),
     +    DROTOL(MXSPEC),EFFN(MXSPEC),DTSEED(MXSPEC),GITEMP(MXSPEC),
     +    GIWAT(MXSPEC),GMN(MXSPEC),GRMRAT(MXSPEC),GSR(MXSPEC),
     +    HFMAX(MXSPEC),PCLDG(MXSPEC),PGDVRT(MXSPEC),PGNTGT(MXSPEC),
     +    PLALFA(MXSPEC),PLBIO(MXSPEC),PLDIAM(MXSPEC),PLHGHT(MXSPEC),
     +    PLTMNT(MXSPEC),PLTMXT(MXSPEC),PLTOPT(MXSPEC),PMAX(MXSPEC),
     +    PMAXN(MXSPEC),PNRED(MXSPEC),PMNNIT(MXSPEC),PRNLW(MXSPEC),
     +    PTLAMX(MXSPEC),R20(MXSPEC),RATLS(MXSPEC),RATRSX(MXSPEC),
     +    RATRSN(MXSPEC),RDR(MXSPEC),RDX(MXSPEC),RQ10(MXSPEC),
     +    RTNLW(MXSPEC),SDAMAX(MXSPEC),SDDVRT(MXSPEC),SDSVRT(MXSPEC),
     +    SDTMGM(MXSPEC),SDWMAX(MXSPEC),SFREEZ(MXSPEC),SLA1(MXSPEC),
     +    SLA2(MXSPEC),SLA3(MXSPEC),SLA4(MXSPEC),STEND(2:6,MXSPEC),
     +    STNAVL(MXSPEC),STNGER(MXSPEC),STNLW(MXSPEC),TBS(MXSPEC),
     +    TOP(MXSPEC),TOT4WT(MXSPEC),WCG(MXSPEC),WCP(MXSPEC),
     +    WDLDG(MXSPEC),CNST(MXSPEC),PRB(7,7,MXSPEC),GSGDD(2:6,MXSPEC),
     +    GDDFLG(MXSPEC),VRNLZ(MXSPEC),SUFNDX(MXSPEC),IPLTYP(MXSPEC),
     +    LWM(MXSPEC),LWS(MXSPEC),NPL,INFIXN(MXSPEC)
      WRITE(IFILE,*) HSTAGE(MXAPP),HPERC(MXAPP),HRVEFF(MXAPP),YIELD(3),
     +    STUBHT(MXAPP),IHTYPE(MXAPP),IHDAY(MXAPP,3),IHARV(MXAPP),
     +    IHCL(MXAPP)
      WRITE(IFILE,*) AL,ALOH,ALSO4,CA,CASO4,H,HCO3,SO4,XMG,XMGSO4,XNA,
     +    XNASO4,XNAORG,XNH4,ORG,CO3,ALORG,ALI,ALOHI,ALSO4I,CAI,CO3I,HI,
     +    HCO3I,ORGI,SO4I,XMGI,XNAI,XNH4I,ALIS,ALOHIS,ALSOIS,CAIS,CO3IS,
     +    HIS,HCO3IS,ORGIS,SO4IS,XMGIS,XNAIS,XNASIS,XNH4IS,ALORIS
      WRITE(IFILE,*) ECA(MXNOD),ENA(MXNOD),EMG(MXNOD),ENH4(MXNOD),
     +    EAL(MXNOD),SCL(MXNOD,3),CEC(MXNOD)
      WRITE(IFILE,*) RAC(11),RRC(11),FERTIR(4),PESTIR(MXPEST),FMNRIR
      WRITE(IFILE,*) RO,SWF(MXnod),TR(MXTSTP),CI(MXTSTP),CRFD(MAXBP),
     +    CRFT(MAXBP),RFI(MAXBP),RFDD,RFD
      WRITE(IFILE,*) THSMS(MXNOD,MXCHEM),CUPRO,CUPCHM(MXCHEM),CDNCI,
     +    CDNCHM(MXCHEM),CMESO(MXNODT,MXCHEM),CMICR(MXNODT,MXCHEM),
     +    CRO(MXTSTP,MXCHEM)
      WRITE(IFILE,*) CDBET(MXNODT,MXCHEM),CFLOW(MXNODT,MXCHEM),
     +    CDFLOW(MXNODT,MXCHEM),CUMCLM(MXTSTP,MXCHEM),
     +    CUMCLR(MXTSTP,MXCHEM),CUMMF(MXTSTP),CUMRO(MXTSTP),
     +    DBET(MXNODT),DFLOW(MXNODT),FLOW(MXNODT),TDFLOW(MXNODT),
     +    TFLOW(MXNODT)
      WRITE(IFILE,*) A,ALH(MXNOD,MXCHEM),B,BDH(MAXHOR),DEG(MAXHOR),
     +    BDHR(MAXHOR),MICP(MAXHOR),NMICP
      WRITE(IFILE,*) CRUSTK,OCRUST,ICRUST,INFLPD,NHZ,NSLT,POND,RR,
     +    DHB(MAXHOR),NSL(MAXHOR),WI(MXnod),DSL(MXNODT),VWC(MXNODT),
     +    IUGFLW
      WRITE(IFILE,*) FLXMAX(MAXHOR),DB(MAXHOR),NPOR(MAXHOR)
      WRITE(IFILE,*) AMNH4(MXAPP),AMOW(MXAPP),AMBED(MXAPP),
     +    CNBED(MXAPP),AMCN(15),CNMANR(MXAPP),FCMANR(MXAPP),
     +    IWMANR(MXAPP),IMOFF(MXAPP,2),IMMETH(MXAPP),IMTYPE(MXAPP),
     +    NAPPM,IMPL(MXAPP),IMANDECOMP(MXAPP)
      WRITE(IFILE,*) FNH4IN(MXAPP),FNO3IN(MXAPP),FUREIN(MXAPP),
     +    SPLTST(MXAPP),SPLTAP(MXAPP),IFOFF(MXAPP,2),IFMETH(MXAPP),
     +    IWFERT(MXAPP),NAPPF,IBMPAP(MXAPP),IBMPMD(MXAPP),
     +    IDSPLT(MXAPP),IFPL(MXAPP)
      WRITE(IFILE,*) APP(MXAPP),PDR(MXAPP),IAPP(MXAPP),IPOFF(MXAPP,2),
     +    IWPEST(MXAPP),IPMETH(MXAPP),NAPP,IPPL(MXAPP)
      WRITE(IFILE,*) OBD(2),OFDP(2),TDEPTH(30),TILINT(30,2),
     +    TNDX(MXAPP),UDEPTH(MXAPP), PManureMix(MXAPP), IMP(MXAPP),  
     +    ITL(MXAPP), ITOFF(MXAPP,2),IWTILL(MXAPP),NUMTL, ITPL(MXAPP)
C
C     BLOCK DATA BLKOUT
C
      WRITE(IFILE,*) SCASSL,USSSL,VECSSL,UVSSL,ASSSL,AVSSL
      WRITE(IFILE,*) SC,CNTRL,SCAPLT,VECPLT,SCATAB,VECTAB,ISCA,IVEC
      WRITE(IFILE,*) SCNRIO,SCALAR,VECTOR,HZLABS

C       WRITE(IFILE,*) RFDD,JDAY,IYYY,TMAX,TMIN,RTS,TPP,W,HEIGHT,LAI,T,
C      +    SOILPP,NDXN2H,RDF,JGS,NSC,PLTSLV,RPOOL,UPNIT,EWP,SDEAD,TLPLNT,
C      +    XNIT,BASE,FIXN,IPL,IPM,JGROW,IMAGIC,ODMDN,CN,RM,RESAGE,RCN,
C      +    SDCN,CORES,COPLNT,NPEST,CHLRFL,TDAY,IQUE,INXPL,IRTYPE,OMSEA,
C      +    TLAI,IPR,SDEAD_HEIGHT,AIRR,CC,RZPAR,JBDAY,IYB,CO2R,ndxt2n,
C      +    iswpar,tmday,iweather,ssurft,IPDEPTH,TUP,DAYL


C
C
C     Close file and exit
C
C
      CLOSE(UNIT=IFILE)
      RETURN
C     ..ERROR CONDITIONS FOR OPENNING FILE
   50 PRINT*,'ERROR OPENING THE FILE: INTERMEDIATE.DAT'
      PRINT*
      PRINT*,' CHECK TO MAKE SURE THE FILE IS IN THE CURRENT DIR.'
      STOP
     	END SUBROUTINE PLSTATWRITE

      SUBROUTINE PLSTATREAD()
C
C======================================================================
C
C       PURPOSE:  SAVE PLANT GROWTH STATE VARIABLES TO PLSTAT.DAT
C
C
C       VARIABLE DEFINITIONS:
C       VARIABLE  I/O DESCRIPTION
C       --------  --- -----------
C
C       EXTERNAL REFERENCES: None
C
C       CALLED FROM: MAIN
C
C       PROGRAMMER: BALAJI POKURI
C
C       VERSION: 0.1
C           VARIABLE LIST COPIED FROM MAPLNT(), CODE FROM STATOT()
C======================================================================
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C     LOAD ALL VARIABLES WE CAN GET
C
C     Variables from RZmain.for
C
      PARAMETER(MXNOD=300,MXNODT=3001,MAXHOR=12,MAXSCT=11,MXCHEM=15,
     +    MXPEST=3,MXAPP=200,MXSPEC=10,MXANA=135,MHR=24)
      PARAMETER(MXTN=39,MXTNC=27,MXTP=19)
      PARAMETER(MXTSTP=5000,rhoi=9.2d2,rhol=1.0d3)
      PARAMETER(R2D=180.0D0/3.141592654D0,FCR=0.4d0)
      PARAMETER(MX2=MXNOD*2,MXC=MXNOD*MXCHEM,MXN=MXNOD*25,MXP=MXNOD*
     +    MXPEST,MAPA=MXAPP*4,MXTPP=MXPEST*MXTP)
      PARAMETER(MAXBP=50)
      PARAMETER(LX2=MAXHOR*13,LX3=MAXHOR*8,LX4=MAXHOR*5,LX5=MXAPP*2,LX6=
     +    MAXHOR*MAXSCT*3,MXPE=MXNOD*MXPEST,LX7=MXNOD*3,LST=5*MXSPEC,LDV
     +    =6*MXSPEC,MXAPP3=MXAPP*3,MXAPP20=MXAPP*20,MXAPP00=MXAPP*200)
      PARAMETER(MXHCH=MXNOD*MXCHEM,MXNCH=MXNODT*MXCHEM,MXTCH=MXTSTP*
     +    MXCHEM)
      PARAMETER(NUMSCN=7,NUMSCA=107,NUMVEC=59,IHZNUM=21,MAXSCA=41,MAXVEC
     +    =23)
      PARAMETER(TTN=-50.0D0,TTX=50.0D0,TUN=45.0D0,TUX=4700.0D0,TRN=
     +    0.0D0,TRX=45.0D0,TRHN=0.0D0,TRHX=100.0D0,UBREEZ=100.0D0)
      PARAMETER(IKEN=8+13+5+3*MAXSCT+8)
      PARAMETER(MXTNCA=9)
      PARAMETER(IFILE=85,CARBCV=1.0D0/0.58D0)

      COMMON /HEAT/ CSH(MXNOD),T(MXNOD),SOLTP1(MAXHOR,5),
     +    SOLTP2(MAXSCT,MAXHOR,3)
      COMMON /GEOMTR/XLONG,ASPECT,DELZ(MXNOD),ELEV,HORTHK(MAXHOR),SLOPE,
     +    AREA,TL(MXNOD),TLT(MXNOD),XLAT,ZN(MXNOD),NHOR,NN,NNT
      COMMON /HYDROL/ AEF,BOTFLX,DRDEP,DRSPAC,DRRAD,CLAT(MAXHOR),
     +    HEAT(MXNOD),HKBAR(MXNOD),QF(MXNOD),SOILHP(13,MAXHOR),HFC,HWP,
     +    THETA(MXNOD),thetai(mxnod),RICH_EPS,IREBOT,ITBL,IDRAIN,
     +    MAXITER_RICH,MAXCYCLE_RICH
      COMMON /IPMACF/ AGSZ(MAXHOR),FDEP(MAXHOR),MCPOR(MAXHOR),PI,
     +    PL(MAXHOR),RP(MAXHOR),SFCT,TWOPI,WP(MAXHOR),NHCMP,YESMAC,
     +    EFFWR,EFFWC,XPRESF
      COMMON /PLNTG/ PLDEN(MXAPP),PLTDAY(MXAPP,2),ROWSP(MXAPP),
     +    PLDEPTH(MXAPP),sdwtplr(mxapp),sdager(mxapp),sprlapr(mxapp),
     +    PLNTSW(MXAPP),PLNTWD(MXAPP),LAYNDX(MXAPP),NPGS,NPR(MXAPP),
     +    NGPL(MXAPP),iptype(mxapp),iemrg(mxapp)
      common /gleams/rzrainfall,rzirrigation,rzrunoff
      common /Gleams_hydsol/gleams_clay,gleams_silt,gleams_por,
     +        gleams_om1,gleams_sand,gleams_BulkDn,gleams_Dacre, 
     +        gleams_CHS,gleams_ei,gleams_exrain,thirtyRR,  
     +        IBYEAR,IEYEAR 
      common /po4log/ErosionActive,UseEnrichment
      COMMON /SOIL/ SOILPP(8,MAXHOR),pori(mxnod)
      COMMON /NDEX/ NDXN2H(MXNOD),NDXH2N(MAXHOR),NDXN2T(MXNOD),
     +    NDXT2N(MXNODT)
      COMMON /RZPEST/ HALFF(MXPEST),HALFFP(MXPEST),HALFFB(MXPEST),
     +    HALFR(MXPEST),HALFRP(MXPEST),HALFRB(MXPEST),HALFSSA(MXPEST),
     +    HALFSSV(MXPEST),HALFSSP(MXPEST),HALFSSB(MXPEST),
     +    HALFSA(MXPEST),HALFSN(MXPEST),HALFSB(MXPEST),HALFBD(MXPEST),
     +    XKH(MXPEST),XKOC(MXPEST),XMW(MXPEST),THETAR(MXPEST),
     +    TMPR(MXPEST),EA(MXPEST),EN(MXPEST),WALKERB(MXPEST),
     +    VMAX(MXPEST),DYIELD(4,MXPEST),FREUND(MXPEST),XPKA(MXPEST),
     +    XPKB(MXPEST),REFPH(MXPEST),CATKOC(MXPEST),ANKOC(MXPEST),
     +    PCOEFF(MXPEST),PPOWER(MXPEST),RCOEFF(MXPEST),RPOWER(MXPEST),
     +    XKOW(MXPEST),PBIND(MXPEST),IPCODE(4,MXPEST),IPANC(MXPEST),
     +    IPDEP(MXPEST),IPACTV(MXPEST),NPEST
      common /maxbal/IDmxH2O,IMmxH2O,IYYYmxH2O,IDmxN,IMmxN,IYYYmxN,
     +              IDmxC,IMmxC,IYYYmxC,IDmxP,IMmxP,IYYYmxP,
     +              DTMASSmxH2O,BalmxN,BalmxC,BalmxP,IWCINIT1
     +            ,ireset1
      COMMON /KNTCS/ CONCX2(MXNOD,MXPEST),EK2(MXNOD,MXPEST),
     +    RK2(MXPEST),RDIF(MXPEST),FEK2(MXPEST),IEK2(MXPEST)
      COMMON /RESID/ RM,RESAGE,CRES,HR,RCN,NADLY,NSDLY,NAREC,NSREC,WORM,
     +               SAI,HSTUBL,WSTUBL
      COMMON /PLNTDA/ CLSIZE(0:7),PSTATE(9),PWRTS,DMDNIT,TNITUP,GS,
     +    CNUP1(MXSPEC),CNUP2(MXSPEC),UPLUX
      COMMON /NUTPAR/ R14,R23,R34,R43,R45,R53,R15,R25,EFFMAX,EFFNIT,
     +    EFFDEN,DENC,RPOP(3),ADCAY,ANIT,ADENIT,AUREA,ADEATH(3),CN(9),
     +    ADCAYV(5),XKP(3),AMETH,FRN2O_NIT,FRN2O_DEN,RNO_N2O,RAINNO,
     +    O2LIM,EFFMETH,ISBUG
      COMMON /PINFO/ TSOTP0(MXPEST),TAPAP(MXPEST),TLPRS(MXPEST),
     +    TLPCN(MXPEST),TLPSL(MXPEST),TLPRO(MXPEST),TLPLC(MXPEST),
     +    TDPPLNT(MXPEST),TLPDT(MXPEST),TLPDTD(MXPEST),
     +    TLPDTL(MXPEST),TLPDMA(MXPEST)
      COMMON /SC1/ ISTAB,IVTAB,ISPLT,IVPLT
      COMMON /IPOTEV/ A0,AW,AC,ARI,XW,FSUN,COEPAN,rss,RST(MXSPEC)
     +    ,RXANGLE(MXSPEC),RTCCRIT(MXSPEC),RPLEAF0(MXSPEC),
     +      RRSTEXP(MXSPEC),RRLEAF0(MXSPEC)
      common /sumet/sumAET,sumCropET,sumPET,sumPT,sumAT,sumrain,deltheta
      common /hourweather/ hrt,hrts,hru,hrh,HRZPAR,HRTH
      common /wsi/ wsi, alaireset, heightset, iresetlai, iresetht1
C
C     BLOCK DATA BLOCK1
C
      COMMON /IRRIG/ DOIMAX(MXAPP),FDOI(MXAPP),VDOI(MXAPP,MXAPP),
     +    XKU(MXAPP,20),XMAD(MXAPP,20),RRATE(MXAPP),amxirr,
     +    totaliw,DOIMONTH(12,200),TOTALMONTH,airrdepth,amirr,
     +    RRDUR(MXAPP),IIPL(MXAPP),ISPT(MXAPP),ITOI(MXAPP),
     +    JDIRRB(MXAPP),JDIRRE(MXAPP),NAPPI,NDAIRR(MXAPP),NKU(MXAPP),
     +    NMAD(MXAPP),JDOI(MXAPP,MXAPP),JKU(MXAPP,20),JMAD(MXAPP,20),
     +    IDOI(MXAPP),id_depth,MONTHIRR
      COMMON /PLNTIN/ AHLDG(MXSPEC),ALA(MXSPEC),ALNAVL(MXSPEC),
     +    ALNGER(MXSPEC),ALNLW(MXSPEC),ALPHA(MXSPEC),ALX(MXSPEC),
     +    BETA(MXSPEC),BGSEED(MXSPEC),CAA(MXSPEC),CANK(MXSPEC),
     +    CAX(MXSPEC),CONVLA(MXSPEC),CVLBIO(MXSPEC),DEVRAT(2:7,MXSPEC),
     +    DROTOL(MXSPEC),EFFN(MXSPEC),DTSEED(MXSPEC),GITEMP(MXSPEC),
     +    GIWAT(MXSPEC),GMN(MXSPEC),GRMRAT(MXSPEC),GSR(MXSPEC),
     +    HFMAX(MXSPEC),PCLDG(MXSPEC),PGDVRT(MXSPEC),PGNTGT(MXSPEC),
     +    PLALFA(MXSPEC),PLBIO(MXSPEC),PLDIAM(MXSPEC),PLHGHT(MXSPEC),
     +    PLTMNT(MXSPEC),PLTMXT(MXSPEC),PLTOPT(MXSPEC),PMAX(MXSPEC),
     +    PMAXN(MXSPEC),PNRED(MXSPEC),PMNNIT(MXSPEC),PRNLW(MXSPEC),
     +    PTLAMX(MXSPEC),R20(MXSPEC),RATLS(MXSPEC),RATRSX(MXSPEC),
     +    RATRSN(MXSPEC),RDR(MXSPEC),RDX(MXSPEC),RQ10(MXSPEC),
     +    RTNLW(MXSPEC),SDAMAX(MXSPEC),SDDVRT(MXSPEC),SDSVRT(MXSPEC),
     +    SDTMGM(MXSPEC),SDWMAX(MXSPEC),SFREEZ(MXSPEC),SLA1(MXSPEC),
     +    SLA2(MXSPEC),SLA3(MXSPEC),SLA4(MXSPEC),STEND(2:6,MXSPEC),
     +    STNAVL(MXSPEC),STNGER(MXSPEC),STNLW(MXSPEC),TBS(MXSPEC),
     +    TOP(MXSPEC),TOT4WT(MXSPEC),WCG(MXSPEC),WCP(MXSPEC),
     +    WDLDG(MXSPEC),CNST(MXSPEC),PRB(7,7,MXSPEC),GSGDD(2:6,MXSPEC),
     +    GDDFLG(MXSPEC),VRNLZ(MXSPEC),SUFNDX(MXSPEC),IPLTYP(MXSPEC),
     +    LWM(MXSPEC),LWS(MXSPEC),NPL,INFIXN(MXSPEC)
      COMMON /HRVST/ HSTAGE(MXAPP),HPERC(MXAPP),HRVEFF(MXAPP),YIELD(3),
     +    STUBHT(MXAPP),IHTYPE(MXAPP),IHDAY(MXAPP,3),IHARV(MXAPP),
     +    IHCL(MXAPP)
      COMMON /SCCONC/ AL,ALOH,ALSO4,CA,CASO4,H,HCO3,SO4,XMG,XMGSO4,XNA,
     +    XNASO4,XNAORG,XNH4,ORG,CO3,ALORG,ALI,ALOHI,ALSO4I,CAI,CO3I,HI,
     +    HCO3I,ORGI,SO4I,XMGI,XNAI,XNH4I,ALIS,ALOHIS,ALSOIS,CAIS,CO3IS,
     +    HIS,HCO3IS,ORGIS,SO4IS,XMGIS,XNAIS,XNASIS,XNH4IS,ALORIS
      COMMON /SCHMIN/ ECA(MXNOD),ENA(MXNOD),EMG(MXNOD),ENH4(MXNOD),
     +    EAL(MXNOD),SCL(MXNOD,3),CEC(MXNOD)
      COMMON /INFILC/ RAC(11),RRC(11),FERTIR(4),PESTIR(MXPEST),FMNRIR
      COMMON /OPINF/ RO,SWF(MXnod),TR(MXTSTP),CI(MXTSTP),CRFD(MAXBP),
     +    CRFT(MAXBP),RFI(MAXBP),RFDD,RFD
      COMMON /OPCHEM/ THSMS(MXNOD,MXCHEM),CUPRO,CUPCHM(MXCHEM),CDNCI,
     +    CDNCHM(MXCHEM),CMESO(MXNODT,MXCHEM),CMICR(MXNODT,MXCHEM),
     +    CRO(MXTSTP,MXCHEM)
      COMMON /OPMACF/ CDBET(MXNODT,MXCHEM),CFLOW(MXNODT,MXCHEM),
     +    CDFLOW(MXNODT,MXCHEM),CUMCLM(MXTSTP,MXCHEM),
     +    CUMCLR(MXTSTP,MXCHEM),CUMMF(MXTSTP),CUMRO(MXTSTP),
     +    DBET(MXNODT),DFLOW(MXNODT),FLOW(MXNODT),TDFLOW(MXNODT),
     +    TFLOW(MXNODT)
      COMMON /IPCHEM/ A,ALH(MXNOD,MXCHEM),B,BDH(MAXHOR),DEG(MAXHOR),
     +    BDHR(MAXHOR),MICP(MAXHOR),NMICP
      COMMON /IPINF/ CRUSTK,OCRUST,ICRUST,INFLPD,NHZ,NSLT,POND,RR,
     +    DHB(MAXHOR),NSL(MAXHOR),WI(MXnod),DSL(MXNODT),VWC(MXNODT),
     +    IUGFLW
      COMMON /INTMCF/ FLXMAX(MAXHOR),DB(MAXHOR),NPOR(MAXHOR)
      COMMON /MMNUR/ AMNH4(MXAPP),AMOW(MXAPP),AMBED(MXAPP),
     +    CNBED(MXAPP),AMCN(15),CNMANR(MXAPP),FCMANR(MXAPP),
     +    IWMANR(MXAPP),IMOFF(MXAPP,2),IMMETH(MXAPP),IMTYPE(MXAPP),
     +    NAPPM,IMPL(MXAPP),IMANDECOMP(MXAPP)
      COMMON /MFERT/ FNH4IN(MXAPP),FNO3IN(MXAPP),FUREIN(MXAPP),
     +    SPLTST(MXAPP),SPLTAP(MXAPP),IFOFF(MXAPP,2),IFMETH(MXAPP),
     +    IWFERT(MXAPP),NAPPF,IBMPAP(MXAPP),IBMPMD(MXAPP),
     +    IDSPLT(MXAPP),IFPL(MXAPP)
      COMMON /MPEST/ APP(MXAPP),PDR(MXAPP),IAPP(MXAPP),IPOFF(MXAPP,2),
     +    IWPEST(MXAPP),IPMETH(MXAPP),NAPP,IPPL(MXAPP)
      COMMON /TILLIN/ OBD(2),OFDP(2),TDEPTH(30),TILINT(30,2),
     +    TNDX(MXAPP),UDEPTH(MXAPP), PManureMix(MXAPP), IMP(MXAPP),  
     +    ITL(MXAPP), ITOFF(MXAPP,2),IWTILL(MXAPP),NUMTL, ITPL(MXAPP)
C
C     BLOCK DATA BLKOUT
C
      COMMON /SSLIST/ SCASSL,USSSL,VECSSL,UVSSL,ASSSL,AVSSL
      COMMON /FUNIT/ SC,CNTRL,SCAPLT,VECPLT,SCATAB,VECTAB,ISCA,IVEC
      COMMON /LABLS/ SCNRIO,SCALAR,VECTOR,HZLABS


C
C
C    Now Open the dat file to write
C
C
      OPEN(IFILE,FILE='INTERMEDIATE.DAT',STATUS='UNKNOWN', ERR=50)
C
C
C    Write each set of common variables in sequence
C
C
      READ(IFILE,*) CSH(MXNOD),T(MXNOD),SOLTP1(MAXHOR,5),
     +    SOLTP2(MAXSCT,MAXHOR,3)
      READ(IFILE,*)XLONG,ASPECT,DELZ(MXNOD),ELEV,HORTHK(MAXHOR),SLOPE,
     +    AREA,TL(MXNOD),TLT(MXNOD),XLAT,ZN(MXNOD),NHOR,NN,NNT
      READ(IFILE,*) AEF,BOTFLX,DRDEP,DRSPAC,DRRAD,CLAT(MAXHOR),
     +    HEAT(MXNOD),HKBAR(MXNOD),QF(MXNOD),SOILHP(13,MAXHOR),HFC,HWP,
     +    THETA(MXNOD),thetai(mxnod),RICH_EPS,IREBOT,ITBL,IDRAIN,
     +    MAXITER_RICH,MAXCYCLE_RICH
      READ(IFILE,*) AGSZ(MAXHOR),FDEP(MAXHOR),MCPOR(MAXHOR),PI,
     +    PL(MAXHOR),RP(MAXHOR),SFCT,TWOPI,WP(MAXHOR),NHCMP,YESMAC,
     +    EFFWR,EFFWC,XPRESF
      READ(IFILE,*) PLDEN(MXAPP),PLTDAY(MXAPP,2),ROWSP(MXAPP),
     +    PLDEPTH(MXAPP),sdwtplr(mxapp),sdager(mxapp),sprlapr(mxapp),
     +    PLNTSW(MXAPP),PLNTWD(MXAPP),LAYNDX(MXAPP),NPGS,NPR(MXAPP),
     +    NGPL(MXAPP),iptype(mxapp),iemrg(mxapp)
      READ(IFILE,*)rzrainfall,rzirrigation,rzrunoff
      READ(IFILE,*)gleams_clay,gleams_silt,gleams_por,
     +        gleams_om1,gleams_sand,gleams_BulkDn,gleams_Dacre, 
     +        gleams_CHS,gleams_ei,gleams_exrain,thirtyRR,  
     +        IBYEAR,IEYEAR 
      READ(IFILE,*)ErosionActive,UseEnrichment
      READ(IFILE,*) SOILPP(8,MAXHOR),pori(mxnod)
      READ(IFILE,*) NDXN2H(MXNOD),NDXH2N(MAXHOR),NDXN2T(MXNOD),
     +    NDXT2N(MXNODT)
      READ(IFILE,*) HALFF(MXPEST),HALFFP(MXPEST),HALFFB(MXPEST),
     +    HALFR(MXPEST),HALFRP(MXPEST),HALFRB(MXPEST),HALFSSA(MXPEST),
     +    HALFSSV(MXPEST),HALFSSP(MXPEST),HALFSSB(MXPEST),
     +    HALFSA(MXPEST),HALFSN(MXPEST),HALFSB(MXPEST),HALFBD(MXPEST),
     +    XKH(MXPEST),XKOC(MXPEST),XMW(MXPEST),THETAR(MXPEST),
     +    TMPR(MXPEST),EA(MXPEST),EN(MXPEST),WALKERB(MXPEST),
     +    VMAX(MXPEST),DYIELD(4,MXPEST),FREUND(MXPEST),XPKA(MXPEST),
     +    XPKB(MXPEST),REFPH(MXPEST),CATKOC(MXPEST),ANKOC(MXPEST),
     +    PCOEFF(MXPEST),PPOWER(MXPEST),RCOEFF(MXPEST),RPOWER(MXPEST),
     +    XKOW(MXPEST),PBIND(MXPEST),IPCODE(4,MXPEST),IPANC(MXPEST),
     +    IPDEP(MXPEST),IPACTV(MXPEST),NPEST
      READ(IFILE,*)IDmxH2O,IMmxH2O,IYYYmxH2O,IDmxN,IMmxN,IYYYmxN,
     +              IDmxC,IMmxC,IYYYmxC,IDmxP,IMmxP,IYYYmxP,
     +              DTMASSmxH2O,BalmxN,BalmxC,BalmxP,IWCINIT1
     +            ,ireset1
      READ(IFILE,*) CONCX2(MXNOD,MXPEST),EK2(MXNOD,MXPEST),
     +    RK2(MXPEST),RDIF(MXPEST),FEK2(MXPEST),IEK2(MXPEST)
      READ(IFILE,*) RM,RESAGE,CRES,HR,RCN,NADLY,NSDLY,NAREC,NSREC,WORM,
     +               SAI,HSTUBL,WSTUBL
      READ(IFILE,*) CLSIZE(0:7),PSTATE(9),PWRTS,DMDNIT,TNITUP,GS,
     +    CNUP1(MXSPEC),CNUP2(MXSPEC),UPLUX
      READ(IFILE,*) R14,R23,R34,R43,R45,R53,R15,R25,EFFMAX,EFFNIT,
     +    EFFDEN,DENC,RPOP(3),ADCAY,ANIT,ADENIT,AUREA,ADEATH(3),CN(9),
     +    ADCAYV(5),XKP(3),AMETH,FRN2O_NIT,FRN2O_DEN,RNO_N2O,RAINNO,
     +    O2LIM,EFFMETH,ISBUG
      READ(IFILE,*) TSOTP0(MXPEST),TAPAP(MXPEST),TLPRS(MXPEST),
     +    TLPCN(MXPEST),TLPSL(MXPEST),TLPRO(MXPEST),TLPLC(MXPEST),
     +    TDPPLNT(MXPEST),TLPDT(MXPEST),TLPDTD(MXPEST),
     +    TLPDTL(MXPEST),TLPDMA(MXPEST)
      READ(IFILE,*) ISTAB,IVTAB,ISPLT,IVPLT
      READ(IFILE,*) A0,AW,AC,ARI,XW,FSUN,COEPAN,rss,RST(MXSPEC)
     +    ,RXANGLE(MXSPEC),RTCCRIT(MXSPEC),RPLEAF0(MXSPEC),
     +      RRSTEXP(MXSPEC),RRLEAF0(MXSPEC)
      READ(IFILE,*)sumAET,sumCropET,sumPET,sumPT,sumAT,sumrain,deltheta
      READ(IFILE,*) hrt,hrts,hru,hrh,HRZPAR,HRTH
      READ(IFILE,*) wsi, alaireset, heightset, iresetlai, iresetht1
C
C     BLOCK DATA BLOCK1
C
      READ(IFILE,*) DOIMAX(MXAPP),FDOI(MXAPP),VDOI(MXAPP,MXAPP),
     +    XKU(MXAPP,20),XMAD(MXAPP,20),RRATE(MXAPP),amxirr,
     +    totaliw,DOIMONTH(12,200),TOTALMONTH,airrdepth,amirr,
     +    RRDUR(MXAPP),IIPL(MXAPP),ISPT(MXAPP),ITOI(MXAPP),
     +    JDIRRB(MXAPP),JDIRRE(MXAPP),NAPPI,NDAIRR(MXAPP),NKU(MXAPP),
     +    NMAD(MXAPP),JDOI(MXAPP,MXAPP),JKU(MXAPP,20),JMAD(MXAPP,20),
     +    IDOI(MXAPP),id_depth,MONTHIRR
      READ(IFILE,*) AHLDG(MXSPEC),ALA(MXSPEC),ALNAVL(MXSPEC),
     +    ALNGER(MXSPEC),ALNLW(MXSPEC),ALPHA(MXSPEC),ALX(MXSPEC),
     +    BETA(MXSPEC),BGSEED(MXSPEC),CAA(MXSPEC),CANK(MXSPEC),
     +    CAX(MXSPEC),CONVLA(MXSPEC),CVLBIO(MXSPEC),DEVRAT(2:7,MXSPEC),
     +    DROTOL(MXSPEC),EFFN(MXSPEC),DTSEED(MXSPEC),GITEMP(MXSPEC),
     +    GIWAT(MXSPEC),GMN(MXSPEC),GRMRAT(MXSPEC),GSR(MXSPEC),
     +    HFMAX(MXSPEC),PCLDG(MXSPEC),PGDVRT(MXSPEC),PGNTGT(MXSPEC),
     +    PLALFA(MXSPEC),PLBIO(MXSPEC),PLDIAM(MXSPEC),PLHGHT(MXSPEC),
     +    PLTMNT(MXSPEC),PLTMXT(MXSPEC),PLTOPT(MXSPEC),PMAX(MXSPEC),
     +    PMAXN(MXSPEC),PNRED(MXSPEC),PMNNIT(MXSPEC),PRNLW(MXSPEC),
     +    PTLAMX(MXSPEC),R20(MXSPEC),RATLS(MXSPEC),RATRSX(MXSPEC),
     +    RATRSN(MXSPEC),RDR(MXSPEC),RDX(MXSPEC),RQ10(MXSPEC),
     +    RTNLW(MXSPEC),SDAMAX(MXSPEC),SDDVRT(MXSPEC),SDSVRT(MXSPEC),
     +    SDTMGM(MXSPEC),SDWMAX(MXSPEC),SFREEZ(MXSPEC),SLA1(MXSPEC),
     +    SLA2(MXSPEC),SLA3(MXSPEC),SLA4(MXSPEC),STEND(2:6,MXSPEC),
     +    STNAVL(MXSPEC),STNGER(MXSPEC),STNLW(MXSPEC),TBS(MXSPEC),
     +    TOP(MXSPEC),TOT4WT(MXSPEC),WCG(MXSPEC),WCP(MXSPEC),
     +    WDLDG(MXSPEC),CNST(MXSPEC),PRB(7,7,MXSPEC),GSGDD(2:6,MXSPEC),
     +    GDDFLG(MXSPEC),VRNLZ(MXSPEC),SUFNDX(MXSPEC),IPLTYP(MXSPEC),
     +    LWM(MXSPEC),LWS(MXSPEC),NPL,INFIXN(MXSPEC)
      READ(IFILE,*) HSTAGE(MXAPP),HPERC(MXAPP),HRVEFF(MXAPP),YIELD(3),
     +    STUBHT(MXAPP),IHTYPE(MXAPP),IHDAY(MXAPP,3),IHARV(MXAPP),
     +    IHCL(MXAPP)
      READ(IFILE,*) AL,ALOH,ALSO4,CA,CASO4,H,HCO3,SO4,XMG,XMGSO4,XNA,
     +    XNASO4,XNAORG,XNH4,ORG,CO3,ALORG,ALI,ALOHI,ALSO4I,CAI,CO3I,HI,
     +    HCO3I,ORGI,SO4I,XMGI,XNAI,XNH4I,ALIS,ALOHIS,ALSOIS,CAIS,CO3IS,
     +    HIS,HCO3IS,ORGIS,SO4IS,XMGIS,XNAIS,XNASIS,XNH4IS,ALORIS
      READ(IFILE,*) ECA(MXNOD),ENA(MXNOD),EMG(MXNOD),ENH4(MXNOD),
     +    EAL(MXNOD),SCL(MXNOD,3),CEC(MXNOD)
      READ(IFILE,*) RAC(11),RRC(11),FERTIR(4),PESTIR(MXPEST),FMNRIR
      READ(IFILE,*) RO,SWF(MXnod),TR(MXTSTP),CI(MXTSTP),CRFD(MAXBP),
     +    CRFT(MAXBP),RFI(MAXBP),RFDD,RFD
      READ(IFILE,*) THSMS(MXNOD,MXCHEM),CUPRO,CUPCHM(MXCHEM),CDNCI,
     +    CDNCHM(MXCHEM),CMESO(MXNODT,MXCHEM),CMICR(MXNODT,MXCHEM),
     +    CRO(MXTSTP,MXCHEM)
      READ(IFILE,*) CDBET(MXNODT,MXCHEM),CFLOW(MXNODT,MXCHEM),
     +    CDFLOW(MXNODT,MXCHEM),CUMCLM(MXTSTP,MXCHEM),
     +    CUMCLR(MXTSTP,MXCHEM),CUMMF(MXTSTP),CUMRO(MXTSTP),
     +    DBET(MXNODT),DFLOW(MXNODT),FLOW(MXNODT),TDFLOW(MXNODT),
     +    TFLOW(MXNODT)
      READ(IFILE,*) A,ALH(MXNOD,MXCHEM),B,BDH(MAXHOR),DEG(MAXHOR),
     +    BDHR(MAXHOR),MICP(MAXHOR),NMICP
      READ(IFILE,*) CRUSTK,OCRUST,ICRUST,INFLPD,NHZ,NSLT,POND,RR,
     +    DHB(MAXHOR),NSL(MAXHOR),WI(MXnod),DSL(MXNODT),VWC(MXNODT),
     +    IUGFLW
      READ(IFILE,*) FLXMAX(MAXHOR),DB(MAXHOR),NPOR(MAXHOR)
      READ(IFILE,*) AMNH4(MXAPP),AMOW(MXAPP),AMBED(MXAPP),
     +    CNBED(MXAPP),AMCN(15),CNMANR(MXAPP),FCMANR(MXAPP),
     +    IWMANR(MXAPP),IMOFF(MXAPP,2),IMMETH(MXAPP),IMTYPE(MXAPP),
     +    NAPPM,IMPL(MXAPP),IMANDECOMP(MXAPP)
      READ(IFILE,*) FNH4IN(MXAPP),FNO3IN(MXAPP),FUREIN(MXAPP),
     +    SPLTST(MXAPP),SPLTAP(MXAPP),IFOFF(MXAPP,2),IFMETH(MXAPP),
     +    IWFERT(MXAPP),NAPPF,IBMPAP(MXAPP),IBMPMD(MXAPP),
     +    IDSPLT(MXAPP),IFPL(MXAPP)
      READ(IFILE,*) APP(MXAPP),PDR(MXAPP),IAPP(MXAPP),IPOFF(MXAPP,2),
     +    IWPEST(MXAPP),IPMETH(MXAPP),NAPP,IPPL(MXAPP)
      READ(IFILE,*) OBD(2),OFDP(2),TDEPTH(30),TILINT(30,2),
     +    TNDX(MXAPP),UDEPTH(MXAPP), PManureMix(MXAPP), IMP(MXAPP),  
     +    ITL(MXAPP), ITOFF(MXAPP,2),IWTILL(MXAPP),NUMTL, ITPL(MXAPP)
C
C     BLOCK DATA BLKOUT
C
      READ(IFILE,*) SCASSL,USSSL,VECSSL,UVSSL,ASSSL,AVSSL
      READ(IFILE,*) SC,CNTRL,SCAPLT,VECPLT,SCATAB,VECTAB,ISCA,IVEC
      READ(IFILE,*) SCNRIO,SCALAR,VECTOR,HZLABS

C       READ(IFILE,*) RFDD,JDAY,IYYY,TMAX,TMIN,RTS,TPP,W,HEIGHT,LAI,T,
C      +    SOILPP,NDXN2H,RDF,JGS,NSC,PLTSLV,RPOOL,UPNIT,EWP,SDEAD,TLPLNT,
C      +    XNIT,BASE,FIXN,IPL,IPM,JGROW,IMAGIC,ODMDN,CN,RM,RESAGE,RCN,
C      +    SDCN,CORES,COPLNT,NPEST,CHLRFL,TDAY,IQUE,INXPL,IRTYPE,OMSEA,
C      +    TLAI,IPR,SDEAD_HEIGHT,AIRR,CC,RZPAR,JBDAY,IYB,CO2R,ndxt2n,
C      +    iswpar,tmday,iweather,ssurft,IPDEPTH,TUP,DAYL


C
C
C     Close file and exit
C
C
      CLOSE(UNIT=IFILE)
      RETURN
C     ..ERROR CONDITIONS FOR OPENNING FILE
   50 PRINT*,'ERROR OPENING THE FILE: INTERMEDIATE.DAT'
      PRINT*
      PRINT*,' CHECK TO MAKE SURE THE FILE IS IN THE CURRENT DIR.'
      STOP
      END SUBROUTINE PLSTATREAD
